### ISSUE TITLE
Failure to update in different browser during concurrent usage

### ISSUE THREAD

**Issue by jaycee** [juju/juju-gui#1067]
_From Uros_: I had two browsers open on the same model. The first one had uncommitted state. The second one was empty. Once i committed the changes, the environment switcher in the second one failed to respond or switch between models until i reloaded the gui in the browser.

_From Frankban_: I wonder if that's related to the fact that we never close the mega-watcher, and so there is a race between switching connections and incoming data from the mega-watcher (as a result of a change in the state, like committing a bundle). By closing the mega-watcher I mean sending a request like `{Type: 'AllWatcher', Request: 'Stop', Id: ...}`. Anyway, this is just an idea, might be totally unrelated.

**Comment by hatched** [comment]
I haven't been able to reproduce this with the latest GUI/Juju. Feel free to re-open if you find it's still an issue.
