### ISSUE TITLE
Clicking on search should put auto-focus in search text box

### ISSUE THREAD

**Issue by urosj** [juju/juju-gui#1074]
We currently require two clicks to do search. First to open the dialog, second to put focus on the search text box. Users should be able to just start typing what they want to search.

**Comment by Lucapaulina** [comment]
If they click on search it should open the search dialogue. If they click on store the search dialogue should be minimised.

**Comment by huwshimi** [comment]
Fixed in https://github.com/juju/juju-gui/pull/1077
