### ISSUE TITLE
Export bundle?

### ISSUE THREAD

**Issue by urosj** [juju/juju-gui#1076]
We've lost functionality to export bundles in new GUI.

**Comment by Lucapaulina** [comment]
Yeah, in Chicago we planned out a better export journey for the sandbox but we haven't had time to design it. Our fall back was going to be adding "Import" and "Export" at the top of the UI but haven't had time to get designs for that made either.

**Comment by urosj** [comment]
For now, we will just implement the functionality same way as we have it in the old GUI until we get new designs.
