### ISSUE TITLE
Search for 'mysql' results in fatal JS error

### ISSUE THREAD

**Issue by bac** [juju/juju-gui#1082]
When processing "cs:~uros-jovanovic/wordpress-multi-0" there is a JS error as the computed id is nil which causes `parts` to be undefined, which throws an uncaught exception in app/models/charm.js:162

**Comment by urosj** [comment]
This happens to the public multi series charms currently. Those will be addressed in following GUI releases. Let's keep this issue open to verify behaviour once new charm store is released.

**Comment by hatched** [comment]
It doesn't look like this charm exists any longer to see if it's indeed been fixed in develop. Are there any others which we can test with?

**Comment by hatched** [comment]
I believe this was fixed by a branch which fails gracefully for MSR's
