### ISSUE TITLE
Design of resolve button

### ISSUE THREAD

**Issue by urosj** [juju/juju-gui#1089]
<img width="1270" alt="resolve-button" src="https://cloud.githubusercontent.com/assets/8036113/11836982/5e5ca996-a3de-11e5-8b4a-b7b890d0d715.png">

**Comment by urosj** [comment]
Resolve & retry button should be same size as Remove. Increase remove button height in this case so that they are aligned.

**Comment by hatched** [comment]
I think that the Remove button is the proper height, we may have to let them have more fluid widths so that the Resolve & Retry can push the Remove button smaller.

**Comment by huwshimi** [comment]
The left and right padding on the button just needs to be reduced a little, for some reason the font is being rendered slightly larger in Firefox.
