### ISSUE TITLE
Revert whitebox close functionality

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#1103]
Hitting the x in the header should close the whitebox instead of just the search field. 
Move the X to the far right.

**Comment by anthonydillon** [comment]
Has this been discussed with design as Luca was sure this is how it should be even though I ran it by him a number of times.

**Comment by urosj** [comment]
We're reversing it as it makes search hard to use. No other UI component works like that. In case we get feedback from testers stating "we didn't want to close the search by [x]", we will enable it back.

**Comment by anthonydillon** [comment]
Sure and for what it is worth I wasnt a fan of the change too. That is why
I had Luca QA the branch before creating a pull request.
