### ISSUE TITLE
Export stops working when unit is placed to a machine/container

### ISSUE THREAD

**Issue by urosj** [juju/juju-gui#1110]
Add unit, place it to machine/container. Leave uncommitted. Try to export. 

I was using mv flag.

**Comment by hatched** [comment]
The GUI has never exported uncommitted items. Can you elaborate a bit, was there an error in the browser console? Or did it just not export that unit?

**Comment by hatched** [comment]
Because the GUI never did export uncommitted items we will need to discuss further about if we should and any issues that will arise because of that.
