### ISSUE TITLE
Add list of other series to charm details

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#1127]
The charm details pages need a list of other available series for that charm which link to the details for that series.

I think this will require a new API endpoint to provide us with the details or those other series.

**Comment by Lucapaulina** [comment]
Is there any update on when the endpoint will be made?

**Comment by hatched** [comment]
@Lucapaulina We'll try and get it into 2.2.0 as it's now available on the api at `/meta/supported-series` or `include=supported-series`

**Comment by Lucapaulina** [comment]
Awesome, thanks Jeff.

**Comment by huwshimi** [comment]
We're a little confused about what this should actually show. Should it only show the other series for mult-series charms or should it collapse all series for a charm like the search results do? What happens if there are two charms, one multi-series and then say another with an older series?

**Comment by kadams54** [comment]
After talking about this in IRC, I agree we need more clarification. There's a whole layer of complexity around handling single vs. multi series charms.

**Comment by kadams54** [comment]
Filed https://github.com/CanonicalLtd/juju-design/issues/90; per Mark's response, the series will be focused on multi-series charms. In the storefront we show the list of series for multi-series charms, but not older charms. We should implement the same on the GUI side.
