### ISSUE TITLE
Cannot connect to the enviornment

### ISSUE THREAD

**Issue by jamesbeedy** [juju/juju-gui#1157]
Juju-gui does not connect to juju environment. After a deploy, this is all I get:

![screen shot 2015-12-23 at 3 42 55 pm](https://cloud.githubusercontent.com/assets/5590546/11986983/f256145e-a98b-11e5-80ba-63283f4c49f0.png)

**Comment by marcoceppi** [comment]
It'd be helpful if you could include any [Console Logs](https://developer.chrome.com/devtools/docs/console#opening-the-console). Open the console, load the page, and record any output here

**Comment by mitechie** [comment]
This is usually a sign that the GU cannot communicate with the Juju state server over the websocket API. 

@urosj this is something we should try to find a day or two to handle more gracefully. We know what it means, but timing out or catching the failure with a global message would be most useful as it's almost always that connection.

**Comment by urosj** [comment]
@jamesbeedy Sorry for the inconvenience. Yesterday's updates introduced a regression that broke connectivity. We'll revert the changes and publish new revision of the GUI in a few hours. In case you want to use GUI now, you can get a working version with:

juju deploy cs:~yellow/trusty/juju-gui-4

Also, with the local provider there's a known bug in some versions of FireFox, could you please try with Chrome? 

Thanks for feedback.

**Comment by urosj** [comment]
Updated charm and revision 6 available. "juju deploy cs:~yellow/juju-gui"

**Comment by hatched** [comment]
@jamesbeedy The latest beta release of the gui can be found here cs:~bac/development/trusty/juju-gui-0 would you be able to give this one a try and see if this issue has been resolved?

**Comment by jamesbeedy** [comment]
@hatched Thanks for following up. I can't seem to find cs:~bac/development/trusty/juju-gui-0 might you of moved it?

**Comment by jamesbeedy** [comment]
@hatched cs:~yellow/trusty/juju-gui-7 is the new stable repo for trusty/juju-gui?

**Comment by urosj** [comment]
@jamesbeedy the cs:~yellow/trusty/juju-gui is team's namespace. The official still stays as it is. We are very close to the 2.0 release, and there will be new revision ready in cs:~yellow/trusty/juju-gui tomorrow, which is the final 2.0. Once we check everything, it will replace cs:trusty/juju-gui as well.

Feel free to test the new one in cs:~yellow tomorrow.

**Comment by jamesbeedy** [comment]
Thats great! Thanks!
