### ISSUE TITLE
Switching models between bundle deployment might end up with incomplete deploy

### ISSUE THREAD

**Issue by urosj** [juju/juju-gui#1175]
Solution:
quick: warn user that switching might end up in inconsistent state (same as with uncommitted state)
proper: queue API calls, leave socket open and execute the calls in the background

**Comment by hatched** [comment]
We queue up and send all of the commands rapidly. It's trivial to check if we have an uncommitted state or if something is active in the queue. This means that we can pop up the warning and then give them the ability to 'wait until complete' and move on.

**Comment by hatched** [comment]
I just ran into this issue while qa'ing 2.1.0. It's trivial to reproduce when using multiple models and even medium sized deployments. At the very least I think we should block the user from switching to another model if the ecs isn't empty.
