### ISSUE TITLE
In the inspector, the icons of the added services should be squircles, not circles

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#1181]

**Comment by urosj** [comment]
Why is that? Why mix two styles?

**Comment by elvirafigueras** [comment]
We just want to keep it consistent to what we have at the moment. Circles are only used to represent services in the GUI, whereas squircles are used everywhere else

**Comment by hatched** [comment]
The machine view also has circles for the icons of the services. So right now everywhere in the GUI we use circles for the icons except for the charmbrowser.

**Comment by Lucapaulina** [comment]
We originally only wanted to use circles for the canvas. We'll make a
decision on this early this week and get back to you.

**Comment by huwshimi** [comment]
Ah, that's my fault, I saw circles in this mockup and update the icons:
![inspector-10](https://cloud.githubusercontent.com/assets/361637/12341961/c148bc86-bb79-11e5-82aa-0bc95591fb2e.png)

**Comment by huwshimi** [comment]
It sounds like they will now all be circles.
