### ISSUE TITLE
Add the ability to log out of the GUI

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#1190]
We appear to have lost this functionality in the new UI

**Comment by anthonydillon** [comment]
I believe UX decided to leave logout only on the profile page. Therefore
the user must click the profile from the GUI and click log out.

**Comment by hatched** [comment]
For the 2.0 release we will add a "Log out" link in the top right-most position of the header

**Comment by Lucapaulina** [comment]
That's good for now. We'll rely on the profile page logout link once it's
all integrated. Jeff, did you see the image I sent over earlier?

**Comment by hatched** [comment]
@Lucapaulina Yup, just before I commented here :)
