### ISSUE TITLE
Remove repeated macaroon warning.

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#1206]
When loading the gui there is a long stream of console messages "No macaroon found to get username from." This message can probably be suppressed.

**Comment by jaycee** [comment]
We should actually selectively suppress it--in JES and sandbox mode, suppress. In JEM, we don't want to suppress it. 

•••
Sent from a mobile device with a tiny keyboard. Pardon my typos.




On Wed, Jan 13, 2016 at 2:11 PM -0800, "Jeff Pihach" <notifications@github.com> wrote:












When loading the gui there is a long stream of console messages "No macaroon found to get username from." This message can probably be suppressed.

**Comment by hatched** [comment]
That sounds like a good plan.
