### ISSUE TITLE
Visiting IP of deployed GUI doesn't open the canvas but a bunch of large icons

### ISSUE THREAD

**Issue by urosj** [juju/juju-gui#1225]
After make dist, copying to charm and running make deploy to local provider, visiting the IP address returns a bunch of icons on top of each other instead of connecting to the model. I had to visit correct URL to connect to the model and get login dialog. 

Using: "agent-version": "1.26-alpha4.1" and tip of development branch in GUI (commit 81ea3965c65e176d04400e701ed1695f34bb10df)

**Comment by urosj** [comment]
It might be a cache thing (suggestion by @frankban )

**Comment by hatched** [comment]
This happens when you visit a url the browser thinks is the GUI but cannot actually load any of the stylesheet assets so it displays the icons at full screen size. I'm not really clear on what you'd like fixed here? Do you want the styles included inline so it doesn't display the icons in this case?

**Comment by jaycee** [comment]
Ah, so it's not a cached spritesheet, but rather the cached index.html for the
gui? I'm assuming for the stylesheets to not be available this has to be case
of browser cache.

**Comment by hatched** [comment]
This appears to happen in rare situations where the browser, for whatever reason, has visited the GUI at this IP before, but is not able to complete a connection so it just shows the unstyled raw html. To 'fix' typically the user just needs to refresh the browser and it will be able to fetch all of the new assets.

We can do a couple things to make this a little more friendly though. By including a few styles inline in the html we can avoid the large ugly icons and instead show the loading spinner. If it doesn't load in a certain amount of time we could then refresh the page for the user.

**Comment by huwshimi** [comment]
The icons are now hidden, the loading messages now appear and it even looks like we keep trying to load the GUI (https://github.com/juju/juju-gui/blob/develop/jujugui/templates/index.html.mako#L274), so think we can close this. Feel free to reopen if we need to do more.
