### ISSUE TITLE
The configure icon in the inspector is the wrong colour

### ISSUE THREAD

**Issue by faooful** [juju/juju-gui#1257]
It should be #888888.

<img width="314" alt="screen shot 2016-01-19 at 15 43 37" src="https://cloud.githubusercontent.com/assets/2169216/12423592/19e0e6a0-bec4-11e5-8e54-fa48b2c4f8a5.png">

**Comment by kadams54** [comment]
Closed in https://github.com/juju/juju-gui/issues/1259
