### ISSUE TITLE
Local charms still have broken image instead of default icon

### ISSUE THREAD

**Issue by bac** [juju/juju-gui#1262]
When deploying horizon-juju-charm there are several charms that are deployed from a local repo and they render ugly.

<img width="1109" alt="screen shot 2016-01-19 at 16 37 47" src="https://cloud.githubusercontent.com/assets/617845/12431326/4b57e07e-becb-11e5-90e5-96613da4ffe3.png">

**Comment by hatched** [comment]
Looking into this - If you include an icon with the local charm archive that you drop on the GUI it should display that one. I'm assuming that this wasn't in the charm so I'm looking into why it's not showing the default.

**Comment by hatched** [comment]
This appears to have been resolved. If you're still able to reproduce this feel free to re-open the bug.

**Comment by deephack1982** [comment]
This is happening for me on juju gui 2.9.2.

![juju-missing](https://user-images.githubusercontent.com/6213936/30857528-53f3a732-a2bc-11e7-9574-7224552bd172.png)

I deployed this charm from a local repo with the command `juju deploy ~/charms/paradox-buildslave-linux-puppet`

That folder contains a file called icon.svg. Also if I right click on the missing icon and select copy image location and visit that location in another browser tab the icon is displayed correctly.
