### ISSUE TITLE
GUI raises errors when deploying to Azure provider in Juju 1.25

### ISSUE THREAD

**Issue by axw** [juju/juju-gui#1286]
This was originally reported by a user in https://github.com/juju/juju/issues/3313#issuecomment-175390857. If you just deploy any old service in the GUI with Azure in Juju 1.25, you'll get a warning popup saying:

> "Could not add the requested machine. Server responded with: cannot add a new machine: unit placement is not supported with availability-sets-enabled"

I _think_ this is because the GUI is decomposing the deployment into the equivalent of:
1. juju add-machine
2. juju deploy service -n0
3. juju add-unit service --to <machine-created-in-step-1>

With Azure in Juju 1.25, we do not support "add-machine" or "add-unit --to" if you have availability-sets-enabled, which is the default. We don't have this limitation in the new Azure provider in Juju 2.0, but I'm told we're still supporting Juju 1.25 for a while longer.

![screenshot from 2016-01-27 13 55 15](https://cloud.githubusercontent.com/assets/843579/12605291/8f91db1c-c4fe-11e5-8917-37c02559cb1b.png)

**Comment by urosj** [comment]
Thanks, @axw .

@frankban, @makyo PTAL.

**Comment by tomck** [comment]
Is there a solution for 1.25 or is this a wait for 2.0 situation?

**Comment by urosj** [comment]
@hatched for 2.NEXT, investigate how to detect availability zones status. Implementation and fix is still marked as Future.
