### ISSUE TITLE
Adding a charm to the canvas twice sets an invalid service name

### ISSUE THREAD

**Issue by axw** [juju/juju-gui#1287]
If you add the "ubuntu" charm to the canvas, then add it again, you'll have one with the service name "ubuntu", and one with "ubuntu-2". The latter is not a valid service name, according to Juju.

![screenshot from 2016-01-27 13 55 15](https://cloud.githubusercontent.com/assets/843579/12605330/fd724734-c4fe-11e5-9fd1-654844d41dc2.png)

Also, when I deleted the second service from the canvas after that failure came up, references to "21018070$" started showing up in the UI.

![screenshot from 2016-01-27 13 55 09](https://cloud.githubusercontent.com/assets/843579/12605356/3fc80ab0-c4ff-11e5-9736-6b18e5d74354.png)

**Comment by hatched** [comment]
It is the '-#' that's causing the issue, removing the '-' should resolve this when incrementing service names.

The regexp used by Juju to validate service names `(?:[a-z][a-z0-9]*(?:-[a-z0-9]*[a-z][a-z0-9]*)*)`

**Comment by hatched** [comment]
Thanks for the bug report @axw ! A fix has been committed and will be in the next GUI release 2.0.1

**Comment by axw** [comment]
Thanks, @hatched.
