### ISSUE TITLE
When you search a tag and then perform another search the 2 queries merge into 1

### ISSUE THREAD

**Issue by Lucapaulina** [juju/juju-gui#1288]
Visit jujucharms.com
Click on search
Click on the tag: app-servers
Open search and type in MySQL
URL should read: https://jujucharms.com/q/mysql?tags=app-servers

"On demo.jujucharms.com

Scenario 1: If a search is performed while viewing another search thats indication from the user that they want a new search.

Scenario 2: If a user searches and then clicks on a tag viewable in the search results or a filter it should merge the queries to produce better results.

Currently we aren't supporting either. The behaviour currently implemented allows people to merge queries outside of the search results which is odd because they could be just browsing but are unwittingly refining search as they click through the site."

**Comment by huwshimi** [comment]
Is this a GUI or a storefront bug?

**Comment by frankban** [comment]
This has been fixed in the GUI.
