### ISSUE TITLE
Units in error don't show IP even if one exists

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#1295]
If a unit is in error it doesn't show the IP address of the unit in the inspector even though it has one in `juju status`

![screenshot from 2016-01-27 20 38 12](https://cloud.githubusercontent.com/assets/532033/12633297/fea3adf0-c535-11e5-9384-6627051551b1.png)

**Comment by frankban** [comment]
Closing in favor of https://github.com/juju/juju-gui/issues/2307
