### ISSUE TITLE
Unit icons in MV should have more status borders

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#1296]
When a unit has a status which makes the service icon change colour such as 'error' or 'pending' it should also be indicated in the machine view. We already show a blue outline to indicate uncommitted. This would be helpful especially when a unit is in error. One of these wordpress units is in error...

![screenshot from 2016-01-27 20 42 07](https://cloud.githubusercontent.com/assets/532033/12633343/945751ee-c536-11e5-8e98-46d6bc191dba.png)

**Comment by Lucapaulina** [comment]
+1 Thats a great idea.

**Comment by hatched** [comment]
Thanks @Lucapaulina
