### ISSUE TITLE
Deploy entity link takes a long time and auto deploys

### ISSUE THREAD

**Issue by anthonydillon** [juju/juju-gui#1305]
If you open https://demo.jujucharms.com/?deploy-target=cs:trusty/wordpress-4 it takes a very long time for the wordpress service to appear on the canvas without any feedback to the user. Then the charm or bundle is deployed which I believe is wrong. Charms and bundles should land uncommitted.

**Comment by hatched** [comment]
deploy-target's intention has always been to automatically add a bundle/charm to the canvas then deploy it. This can be changed of course if we can get a consensus from the stakeholders about what the best course of action is. 

But regardless to what comes of that we should definitely pop a notification saying that we're fetching the charm data.

**Comment by Lucapaulina** [comment]
If you add a bundle from the store it adds it the canvas uncommitted, this
is the desired functionality.

**Comment by hatched** [comment]
@Lucapaulina hmm right, what about charms, they auto-deploy. I'd imagine they should be similar. So maybe we should not auto deploy the charms as well?

**Comment by Lucapaulina** [comment]
When I add a bundle from the store it is added to the GUI as uncommitted,
the same goes for charms. I think this is great because it gives users a
chance to review everything before it potentially starts costing them
money. I think we have to be really careful about committing stuff off the
bat without the user reviewing the changes.

**Comment by frankban** [comment]
I'd like to escalate this, as it affect places in which the GUI is not yet connected to the model (disconnected mode) and still we have deploy-target trying to commit the charm, resulting in a API operation (Application.Deploy) not supported error and consequent bad experience for the user.
To be clear, deploy-target should not assume the model is connected, and therefore should only add the target (charm or bundle) to the canvas without trying to deploy it.
