### ISSUE TITLE
Bundle services are added to the db before deploy

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#1316]
When adding a bundle the services are created using `this.db.services.ghostService(charm);` but that creates a reference in the db before the service is deployed. See: https://github.com/juju/juju-gui/pull/1310/files#diff-1dcaa888078db4ae76c5fb071e2ead75R432

**Comment by frankban** [comment]
Not sure I understand this bug. Why do we want to prevent ghost services from being included in the db?

**Comment by huwshimi** [comment]
@hatch any comments on this? I think this was something you noticed, but I can't remember the details around it.

**Comment by hatched** [comment]
Heh, I can't remember exactly, but I think it might be this: https://github.com/juju/juju-gui/pull/1310/files#r51444887

**Comment by frankban** [comment]
No feedback, closing.
