### ISSUE TITLE
Scaling via the inspector duplicates units

### ISSUE THREAD

**Issue by Lucapaulina** [juju/juju-gui#1318]
1. open demo. and add wordpress
2. commit the change and auto place the unit
3. open inspector for wordpress
4. units > scale service
5. add 2
6. leave manually place selected
7. click confirm
8. you should now have 4 units to be placed
9. if you scale the service using the inspector it doubles the input, if you scale the service using MV it works as expected

**Comment by hatched** [comment]
Confirmed, it is adding double the units to the db.
