### ISSUE TITLE
Placement of units not kept before commit

### ISSUE THREAD

**Issue by SaMnCo** [juju/juju-gui#1321]
On Juju 1.25.3 - Ubuntun 15.10 and 15.04 / Deploying on Trusty series 

Workflow: 
1. Deploy a bundle, made of ~10 machines
2. Add 2 services (uncommitted)
3. Hit Commit button
4. realize I want to colocate to other services, so go to "view machines" from the link provide
5. Collocate my services to machines until green checkbox "You have placed all your units"
6. Hit "commit changes" again
==> still says I have unplaced units and says if can automatically place. 
Then I confirm deployment

Then at deployment, as many machines as requested new services are created (unused as placement already done), generating cost for nothing. 

I realize it may be a user workflow problem and I could be blamed for this, but the GUI should help the user on that one.

**Comment by hatched** [comment]
Hi @SaMnCo Thanks for the bug report. I haven't been able to reproduce this issue. Were you able to reproduce this? Could you reply (or contact me if the information is sensitive) with the bundle and the two additional services you added so that I can be sure I reproduce it exactly.

**Comment by hatched** [comment]
I'm going to close this issue for now - if you are able to reproduce this or happen to see it again feel free to re-open.
