### ISSUE TITLE
Charm icon masks are offset by one or two pixels in firefox/Chrome

### ISSUE THREAD

**Issue by makyo** [juju/juju-gui#1322]
<img width="218" alt="juju_admin" src="https://cloud.githubusercontent.com/assets/303761/12880869/2e548e80-ce45-11e5-818a-1e302d21eddb.png">

**Comment by hatched** [comment]
This also happens in the machine view in Chrome it's because of the border radius used to make everything a circle. Of course the proper fix would be to update the icons to be round instead of squircles with the drop shadow.

**Comment by anthonydillon** [comment]
We need the squircles to be displayed everywhere instead of on the canvas.
So I think we need to just fix this crop instead of adding another image to
the API.

Might be worth confirming with design.

**Comment by makyo** [comment]
@anthonydillon Oh, yes, I mean the crop, not the icon itself.  I'll update the title with that
