### ISSUE TITLE
Resolve, Retry and Remove buttons seems to have a grey active state

### ISSUE THREAD

**Issue by Lucapaulina** [juju/juju-gui#1330]
For some reason when you click on the button it stays grey.

![screen shot 2016-02-09 at 16 59 25](https://cloud.githubusercontent.com/assets/5873394/12921716/bc7246d0-cf4e-11e5-9743-4fa910571a15.png)

**Comment by hatched** [comment]
Thanks for this report - looks like we have fixed it already in the develop branch so it'll be resolved in the 2.1.0 release.
