### ISSUE TITLE
Charm deployment fails with an error 

### ISSUE THREAD

**Issue by saad-ngnware** [juju/juju-gui#1349]
Charm deployment fails when a charm of size around 90MB is dragged and dropped onto the canvas. It contains a tar.gz file. 
When I deploy my charm that does not contain the tar file it succeeds in deploying the charm. 
Now the error is somewhat unrealistic. My juju version is 1.25.0 while when I deploy my charm (the one which contains tar file), it throws me an error which is and I quote "Import from *.zip failed. Your version of juju does not support local charm uploads. Please use at least version 1.18.0".

I've been stuck on this error ever since.

**Comment by hatched** [comment]
That error is shown when there is an error uploading the local charm to Juju, Juju is returning a status code greater than 400. It's possible that there is an upload limit that we were yet unaware of and need to investigate.

In the mean time you can deploy your local charm using the instructions found here: https://jujucharms.com/docs/1.25/charms-deploying#deploying-from-a-local-repository

**Comment by hatched** [comment]
Associated AU question: http://askubuntu.com/questions/732498/juju-local-charm-deploy-using-juju-gui-problem
