### ISSUE TITLE
Disable autocomplete for scale-up input in inspector

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#1352]
When scaling up in the inspector the input will pop up a list of options to autocomplete from (in chrome). To dismiss it you have to select an option (which submits the form) or click somewhere else in the inspector (most of which is covered by the options). Clicking outside of the inspector closes the inspector.

**Comment by anthonydillon** [comment]
Will handle this with a branch to auto focus on the input when the view is loaded.
