### ISSUE TITLE
The constraints specified when adding a new machine should be reflected on the machine once it is created

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#1379]

**Comment by hatched** [comment]
What you're specifying are indeed constraints, this means that Juju will fetch you the 'best' machine available that matches what you have specified. This means that when you create a machine with constraints we don't really know what the actual machine will be. We could of course display these values in the same place as the actual machine values but this may cause some confusion, maybe we should have some indicator that they are constraints and not the 'actual' machine specs.

**Comment by elvirafigueras** [comment]
Ok. This means that the machine you have added will have those constraints even though it wasn't created with those exact ones, right? 
It would be good to show the constraints that users have specified on the machine as otherwise they can't refere back to them. We might need design for this? @Lucapaulina

**Comment by Lucapaulina** [comment]
Do constraints have any ramification on the machine?

There has been some talk about providing users with sizes instead of constraints, maybe we should look into that.
