### ISSUE TITLE
Add a hover state to the tags and 'More information' section on charm details

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#1380]

**Comment by huwshimi** [comment]
Hi @elvirafigueras what should that hover state look like?

**Comment by anthonydillon** [comment]
These links have underlines when hovered which I believe is correct.

**Comment by Lucapaulina** [comment]
Heya,

I don't get the hover overs.

https://demo.jujucharms.com/?store=trusty/wordpress

![image](https://cloud.githubusercontent.com/assets/5873394/13391095/5675c4de-deca-11e5-906d-580ef7d54c84.png)

**Comment by elvirafigueras** [comment]
I don't get them either

**Comment by anthonydillon** [comment]
This has been fixed and will land with the next release.
