### ISSUE TITLE
Drag and drop instructions in the second column of MV should be moved to the first

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#1381]

**Comment by huwshimi** [comment]
Hi @elvirafigueras, two questions:
1. Where abouts should be message be? At the top or the bottom?
2. Should this message always be visible or should it disappear after you have at least one placed unit or something?

**Comment by elvirafigueras** [comment]
At the top, under "Auto place or manually place" 
The message should disappear after the action of dragging and dropping has been performed once.

**Comment by spencerbygraves** [comment]
Currently 'Manually place' means to drag and drop the unplaced units. Perhaps we should combine or rewrite the message rather than duplicate it.

**Comment by elvirafigueras** [comment]
Yes, we could go for something like this: 

![img_2494](https://cloud.githubusercontent.com/assets/12827541/13599872/521ba45e-e51d-11e5-92aa-73558cdb28d0.JPG)

Where the text under the 'Auto place' CTA becomes: "You can also drag and drop unplaced units to customise your deployment."

**Comment by spencerbygraves** [comment]
Thanks

**Comment by spencerbygraves** [comment]
You can see the designs in issue #37

**Comment by spencerbygraves** [comment]
The designs can be seen here:

https://www.dropbox.com/sh/l0ixgvcifm02b1v/AAA2nE_8oE1s3FpkAMTWa-Sua?dl=0

**Comment by hatched** [comment]
As I mentioned in doing the review for juju/juju-gui#2902 it doesn't make much sense to tell the users that they can drag and drop units, when they have any applications or units, or even know what a unit is. 

So I asked @huwshimi to remove the "Drag and drop unplaced units to customise your deployment" from machine-view-01.png
