### ISSUE TITLE
The status symbol in the relations tab needs an uncommitted tooltip

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#1383]

**Comment by hatched** [comment]
Can you elaborate on what you mean here? Is there a design outlining what it should look like?

**Comment by Lucapaulina** [comment]
Duplicate issue of #1383

**Comment by Lucapaulina** [comment]
We are clarifying the the design at the moment and will add it back once completed.

**Comment by frankban** [comment]
@elvirafigueras should we kill this bug?
