### ISSUE TITLE
Make unrelated charms transparent when clicking and dragging a charm

### ISSUE THREAD

**Issue by nevrax** [juju/juju-gui#1386]
I would be nice that when clicking and dragging a particular charm in the Juju GUI to only highlight the charm we are currently dragging and its related charms making all other charms and relations transparent.

This would filter all the background noise when dealing with large OpenStack deployments.

**Comment by hatched** [comment]
Modifying the visibility of services on the canvas has been something we've been working on for a while. In the most recent release of the GUI (2.0.3) when you hover over the services in the list on the left of the screen you'll see icons pop up. Clicking these will modify the visibility of the service icons on the canvas. 

We have had feedback that this isn't working well and are going to remove it in the next release (2.1.0) but will add the functionality back in sometime in the near future. We haven't thought about modifying it when you drag, definitely something to explore. 

Thanks for the feedback!

**Comment by frankban** [comment]
This has been done, months ago :-)
