### ISSUE TITLE
Model switcher menu does not play nice with user profile panel

### ISSUE THREAD

**Issue by kadams54** [juju/juju-gui#1396]
Open the panel from the menu and you can see the menu is still open behind the panel. Additionally, if you trigger the user profile menu (by visiting `/profile/` directly) and then click on the model switcher menu, it pops open behind the profile panel.

**Comment by huwshimi** [comment]
The behaviour for the profile is going to change, it won't be an overlay as such but rather a step before viewing your model. So, if you click More in the env switcher, or click your username in the breadcrumb you'll be taken a step back up the hierarchy and to get back to your model you'll need to select it from the list of models.

**Comment by hatched** [comment]
As @huwshimi mentioned, this becomes a non-issue with #1399; closing.
