### ISSUE TITLE
The login screen find password text should be split onto two lines

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#1418]
When logging into a Juju 2.0 model.

![screenshot from 2016-03-02 14 33 06](https://cloud.githubusercontent.com/assets/532033/13474473/c5c570ea-e083-11e5-8029-aa453ff25259.png)

**Comment by hatched** [comment]
Also the username is shown as `admin@local` but you actually use just `admin` to log into the GUI.

**Comment by frankban** [comment]
FYI admin@local works as well on Juju 2.0 so that's not a problem IMHO.

**Comment by hatched** [comment]
Confirmed, thanks for pointing that out @frankban

**Comment by hatched** [comment]
Turns out they changed the command, it's now.
`juju show-controller --show-passwords`
