### ISSUE TITLE
No models listed on ec2

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#1424]
When running the GUI on ec2 I viewed the profile page and it didn't list any models.

There was an error in the console:

operation not supported by API server: {"Type":"EnvironmentManager","Request":"ListEnvironments","Params":{"Tag":"user-admin"}}

I also did not have a login button in the profile header.

**Comment by hatched** [comment]
This was using 1.25.3-wily-amd64 without any dev flags. We should handle the profile view more gracefully when you can only have a single model.
