### ISSUE TITLE
Destroy service doesn't seem to shut down machines

### ISSUE THREAD

**Issue by buggtb** [juju/juju-gui#1426]
I did a demo today using EC2, the last thing I did was destroy the service. Which according to juju status went away, but the machines are still running when I came back 3 hours later..... Using Juju 2.0-beta1-trusty-amd64 and the GUI cut on Monday

**Comment by hatched** [comment]
Hi thanks for the report.

Destroying a service never destroys a machine, even if it's the only service on a machine. This is actually a feature of Juju, not the GUI. If you want to be sure you have completely cleaned up you can switch to the Machine View in the GUI and see what machines are still up and then delete them from there. Even from there you won't be able to destroy your controller. You'll have to do that from the CLI using `juju destroy-controller <controllerName>`.

**Comment by buggtb** [comment]
You learn something new every day. Because:

juju deploy .....

juju destroy-service ....

Will tear down my instances for me.

**Comment by hatched** [comment]
@buggtb Sorry I was confused :)

Yes in Juju 2.0 it will try and destroy the machines as well if it's the last service on the machine. 1.2x however will not. Because the GUI needs to work across multiple platforms we are trying to make sure that there is a consistent experience.

**Comment by buggtb** [comment]
Phew makes more sense! Thanks :)

**Comment by hatched** [comment]
I'm going to re-open this one for discussion to see if we want to mirror the Juju 2.0 experience.

**Comment by marcoceppi** [comment]
+1 to mirroring 2.0 experience in a 2.0 environment.

**Comment by frankban** [comment]
I think this should be done server side. So if Juju decides to remove a machine as a contextual action when removing a unit, that's ok for us. But doing that from the client, not atomically, can be racy. Feel free to reopen this bug if you disagree.
