### ISSUE TITLE
After logging into the CS when deployed via the charm the profile doesn't refresh

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#1436]
Using develop
set `interactive-login` to `true` 
log in to CS via the profile page 
the profile doesn't refresh, you have to close the profile view and open it again for it to work.

**Comment by huwshimi** [comment]
With a clean-all and logging in in a private browser I get a profile refresh but I can't get the charms and bundles to appear at all. Something seems quite busted, but I can't track down how this is even supposed to work any more. Might be related to #1427.

**Comment by hatched** [comment]
I just deployed with the latest develop and the main issue still persists. I was able to get my charms and bundles after closing and opening the profile view. Lets chat about this to see if we can find out why it's not working for you.
