### ISSUE TITLE
interactive property is undefined

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#1437]
Even when the `interactive-login` is false the value that ends up being passed to the profile component is `undefined`. It does properly pass `true` but `false` ends up being passed as `undefined`. This still works as it's a truthy check but we should ivnestigate as this may be a symptom of a larger issue.

**Comment by huwshimi** [comment]
I wasn't able to reproduce this locally. I changed the property to `jujugui.interactive_login = false` in development.ini and was able to see that the value was false in app.js and user-profile.js.

However, I did notice that the profile header is passed an interactiveMethod function or `undefined` depending on the value of `interactiveLogin`: https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/components/user-profile/user-profile.js#L591 could that possibly have caused what you saw?
