### ISSUE TITLE
username shown is prefixed with 'user-'

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#1438]
Because of how we log the user in whenever the user data is requested with `getCredentials` we prefix it with user. This means that in the breadcrumb and in the profile view we show things like `user-admin` and `user-admin@local` which imho is quite ugly and not representative of how the user actually logged into the GUI. I feel like we should display the username that they used to login which is without `user-`

**Comment by Lucapaulina** [comment]
+1
