### ISSUE TITLE
Subordinate handle doesn't display the number of subordinate units

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#1448]
AIUI This should show the number of subordinate units that are deployed elsewhere.
![screenshot from 2016-03-07 17 54 37](https://cloud.githubusercontent.com/assets/532033/13587409/b77fc43c-e48d-11e5-827f-fc7720c6ab53.png)

Is this still a feature @Lucapaulina can you outline exactly what count this is supposed to be showing, Thanks!

**Comment by huwshimi** [comment]
I think it shows the number of services it is being used with. It does actually have the number there but for some reason it is not visible. I'll take a look.
