### ISSUE TITLE
System Z juju-gui Charm install hook failure

### ISSUE THREAD

**Issue by arosales** [juju/juju-gui#1455]
We are testing juju (1.25.0-xenial-s390x) local provider in a Ubuntu Xenial zVM. 

    Linux s3lp1-juju01 4.4.0-7-generic #22-Ubuntu SMP Thu Feb 18 21:13:28 UTC 2016 s390x s390x s390x GNU/Linux

Note all installs are pulled for the Xenial archive. The charm was the only source branched locally.

I was able to bootstrap local provider by setting:
    
    image-stream: "daily"  

in ~/.juju/environments.yaml
ref = http://paste.ubuntu.com/15206412/

I branched the juju-gui charm locally by:

    bzr branch lp:~juju-gui/charms/trusty/juju-gui/trunk juju-gui

and deployed it locally on Xenial by:

    juju deploy local:xenial/juju-gui

The juju-gui charm fails on an install hook:

Collecting backports.ssl-match-hostname==3.4.0.2 (from -r /var/lib/juju/agents/unit-juju-gui-0/charm/server-requirements.pip (line 26))
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools

More info @ http://paste.ubuntu.com/15328258/

I can provide access to the zVM if folks would like to take a look at the environment as this may be specific to s390 arch.

**Comment by hatched** [comment]
Thanks for the report @arosales I've moved it to the charm repo here: https://github.com/juju/juju-gui-charm/issues/43
