### ISSUE TITLE
Long environment names are not handled well

### ISSUE THREAD

**Issue by anthonydillon** [juju/juju-gui#1468]
Creating a environment with a long name causes the header to wrap may cause a horizontal scroll bar.

![juju admin](https://cloud.githubusercontent.com/assets/1413534/13684130/3a35bfaa-e702-11e5-9d41-df752e648104.png)

**Comment by anthonydillon** [comment]
Same with long usernames is they are not limited on creation.

![juju admin](https://cloud.githubusercontent.com/assets/1413534/13684322/1946fd58-e703-11e5-8f6f-b6dc0c1ff34c.png)

**Comment by hatched** [comment]
We'll need to get details on what restrictions juju-core puts on these names and then find a way to display them accordingly.

**Comment by huwshimi** [comment]
Looks like neither of these have  an enforced length. See: https://github.com/juju/names/blob/v2/user.go#L20 and https://github.com/juju/names/blob/v2/model.go#L20.

We'll probably need to set an arbitrary limit and maybe add the full names as tooltips.

**Comment by huwshimi** [comment]
This was fixed by #2975.
