### ISSUE TITLE
Deploying services/units broken

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#1491]
- load https://demo.jujucharms.com/
- add wordpress first
- add mariadb
- relate the services
- deploy and automatically place the units
- you will get an error in your browser console: `Uncaught TypeError: Cannot read property 'get' of null`
- refresh the gui
- add wordpress first
- add mariadb
- relate the services
- deploy and leave the units unplaced
- deploy and automatically place the units
- you will get an error notification in the GUI `Could not add the requested unit. Server responded with: Service "mariadb" does not exist.` (this could be because of the get error)

**Comment by hatched** [comment]
At this time demo is on 2.0.3 not 2.1 - we should see if this persists in 2.1

**Comment by huwshimi** [comment]
I can reproduce this with the latest develop

**Comment by frankban** [comment]
I am pretty sure we can deploy related applications from the GUI now.
