### ISSUE TITLE
"Change version" should be accessible before deployment.

### ISSUE THREAD

**Issue by Lucapaulina** [juju/juju-gui#1496]
At the moment "Change version" in the inspector is only accessible once you have deployed a service but many users want to see the version pre-deployment. It would be good if this functionality can be added.

**Comment by hatched** [comment]
This change is quite large and would essentially require us to destroy and re-create the service pre-deployment. @Lucapaulina Could we instead have the ability to choose the version to deploy from the charm browser when clicking deploy?

**Comment by Lucapaulina** [comment]
I think it's quite important that this feature is in the inspector because
that's where we want people to go for this sort of stuff. I'm also not sure
that we want to interrupt adding to a canvas to choose a version.

Is there also a use case where someone with a bundle will need to upgrade
one of the charms?

**Comment by hatched** [comment]
Yeah that does bring up a good point. Right now we've always told people to destroy and deploy the charm that they are interested in, however you can't actually choose the version when you hit 'add to canvas'. The only way to visit a different version is to actually load the GUI with a url for a specific charm. So I think that there is a missing feature here for the charmstore still.

This could be an ancillary feature so it doesn't actually interrupt the deploy flow, but if you choose a different version from a dropdown in the header pre-clicking 'add to canvas' then it would instead add that version.

**Comment by Lucapaulina** [comment]
Can we get change version in the inspector pre-deploy added to the roadmap
so it can be implemented at some point?

**Comment by hatched** [comment]
Definitely but it'll be after 2.2 for sure.

**Comment by Lucapaulina** [comment]
Thanks!
