### ISSUE TITLE
Safari pop-up blocker prevents login tab from showing

### ISSUE THREAD

**Issue by bac** [juju/juju-gui#1499]
If you hit http://<yourhost>:6543/:flags:/blues/ in Safari no login tab is shown and the GUI just shows the spinner indefinitely.

This happens if Preferences -> Security -> Block pop-up windows is turned on.

Perhaps there is nothing that can be done but it adversely affects our user experience as there is no way to even know the GUI is waiting on action.

**Comment by hatched** [comment]
On loading the GUI it shouldn't be popping up anything. If the cookies it has are invalid it should be failing silently and then giving the user the option to log in after loading.

**Comment by huwshimi** [comment]
We now have a notification with a link that can be clicked to open the popup, I think that's probably all we can reasonably do. Feel free to reopen if there is an issue remaining.
