### ISSUE TITLE
Disable SSLv3 and RC4 by default

### ISSUE THREAD

**Issue by BryanQuigley** [juju/juju-gui#1501]
A default deployed (on 14.04) Juju gui is vulnerable to both SSLv3 attacks and RC4.

The Juju-gui says it supports recent releases of web browsers which would mean we don't support below IE8, etc.
https://jujucharms.com/juju-gui/

RC4 looks ok too, as most people will not be going through bad proxies to reach the juju-gui:
https://blog.cloudflare.com/the-web-is-world-wide-or-who-still-needs-rc4/

In both cases major websites will not be working for them if they use a web browser - and likely the juju-gui won't be working correctly either.

Discussion about this taking place on ML here: https://lists.ubuntu.com/archives/juju/2016-March/006936.html

For example, see:
(must ignore warnings and mismatches to run) https://www.ssllabs.com/ssltest/analyze.html?d=15.35.213.162.lcy-02.canonistack.canonical.com&hideResults=on
https://15.35.213.162.lcy-02.canonistack.canonical.com/

A similar issue was recently fixed by the OpenStack dashboard:
https://github.com/openstack/charm-openstack-dashboard/commit/106f418f13c073b1e7d4c57483f423d5f4d0dd10

(forwarded from https://bugs.launchpad.net/juju-gui/+bug/1563333)

**Comment by BryanQuigley** [comment]
Steps to reproduce:
juju deploy trusty/juju-gui trusty-gui
wait for deployment then get IP
download [testssl.sh](testssl.sh) and run it against https://IP//

**Comment by hatched** [comment]
This will be resolved with this PR: https://github.com/juju/juju-gui-charm/pull/71

**Comment by BryanQuigley** [comment]
Thanks! This works perfectly on Trusty.

If you load this up on Xenial, it appears to stop TLS1.2 from working though.  (Although maybe that's blocked somewhere else?).   Which is very odd because on Trusty it appears to enable TLS1.2 where it wasn't before (awesome!).  Did I do something wrong or is that a regression?

**Comment by hatched** [comment]
@BryanQuigley Glad it's working for you.

The GUI charm is not officially supported on any platform newer than Trusty. On Xenial we recommend using the embedded version of the GUI which can be accessed by running `juju gui --show-credentials` This will open up the GUI in a new browser window and display your username and password in the terminal.

**Comment by frankban** [comment]
@hatched I think the issue here is not related to the Juju version being used: and by the way I am not sure we should drop support for juju2 in the charm. The issue here is the Tornado server configuration regarding supported cert protocols and ciphers.

@BryanQuigley ok I investigated this more and I see a different behavior: in both trusty and xenial cases only TLSv1 is supported. I can fix this on xenial, and I'll do. The trusty case is more tricky, as the Python version there is quite old (2.7.6) and doesn't support just disabling SSLv3 easily.
So with my next fix we will have both xenial and trusty only using secure ciphers, but then:
- xenial will support TLSv1, TLSv1.1. and TLSv1.2;
- trusty will support only TLSv1.
Is that good enough?

**Comment by frankban** [comment]
The change is now proposed at https://github.com/juju/juju-gui-charm/pull/72

@BryanQuigley thanks a lot for your help and feedback!

**Comment by BryanQuigley** [comment]
trusty will support only TLSv1. Is that good enough?

Unfortunately that would actually be a regression in what we provide by default, going from supporting up to  TLS1.2 to TLS1.0 only.  Unfortunately, given those options I'd actually vote for leaving SSLv3 enabled.     I'll see if I can come up with an alternate solution...

**Comment by BryanQuigley** [comment]
Talked with mdeslaur from security team about this.

I thought there were 3 options: 1) leave it as with SSLv3 enabled     2)  only enable TLS1.0 causing a regression for browsers which we're doing 1.2 before    3) only enable TLS1.2 which could break command line tools

2) is a bad idea, 3) isn't feasible... it isn't supported on trusty
mdeslaur: so you can either do 1), or SRU a bazillion lines of code to python2.7 in trusty

I think just changing the ciphers a bit (disable RC4,etc) will be all we can do for this.

**Comment by frankban** [comment]
Ok then, I'll go with disabling the ciphers in both but with disabling SSLv3 only on xenial.

**Comment by BryanQuigley** [comment]
Thanks!  I don't think Xenial has SSLv3 enabled though, so you can just drop that part.

**Comment by hatched** [comment]
I'm going to keep this open until fully resolved.

**Comment by frankban** [comment]
@BryanQuigley ok so the fix has been committed, we'll go ahead and also push the new charm to the store asap. Thanks again for your help!

**Comment by BryanQuigley** [comment]
Thank you!  Latest commit looks great to me.

**Comment by bac** [comment]
The charm has been updated at https://jujucharms.com/juju-gui/
