### ISSUE TITLE
Deploying from cli using Juju 2.0beta3 icons don't show up in canvas

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#1505]
Juju version: Juju 2.0beta3
Juju-gui: 2.0
Ubuntu: 14.04
MAAS: 1.9.1

When executing juju deploy cs:~landscape/bundle/landscape-dense-maas-15 and the charms are deployed, the icons don't show up on the juju-gui canvas, even after a browser refresh

[Services]
NAME STATUS EXPOSED CHARM
haproxy unknown false cs:trusty/haproxy-10
landscape-server unknown false cs:trusty/landscape-server-13
postgresql unknown false cs:trusty/postgresql-27
rabbitmq-server maintenance false cs:trusty/rabbitmq-server-26

[Relations]
SERVICE1 SERVICE2 RELATION TYPE
haproxy haproxy peer peer
haproxy landscape-server website regular
landscape-server postgresql db-admin regular
landscape-server rabbitmq-server amqp regular
postgresql postgresql replication peer
rabbitmq-server rabbitmq-server cluster peer

[Units]
ID WORKLOAD-STATUS JUJU-STATUS VERSION MACHINE PORTS PUBLIC-ADDRESS MESSAGE
haproxy/3 unknown idle 2.0-beta3.1 3/lxc/0 80/tcp,443/tcp,10000/tcp 172.27.32.56
landscape-server/3 unknown idle 2.0-beta3.1 3/lxc/1 172.27.32.57
postgresql/3 unknown idle 2.0-beta3.1 3/lxc/2 5432/tcp 172.27.32.58
rabbitmq-server/3 maintenance executing 2.0-beta3.1 3/lxc/3 172.27.32.59 (config-changed) installing charm software

[Machines]
ID STATE DNS INS-ID SERIES AZ
3 started 172.27.32.55 /MAAS/api/1.0/nodes/node-7f3c687e-ea36-11e5-861b-8cae4cfda585/ trusty

copied from https://bugs.launchpad.net/juju-gui/+bug/1564978

**Comment by urosj** [comment]
Did not test with beta3, however could not reproduce with beta4 and gui from devel.
