### ISSUE TITLE
Missing content from bundle details

### ISSUE THREAD

**Issue by Lucapaulina** [juju/juju-gui#1514]
When comparing 2 bundle details side by side it shows we are missing the following content which should be added:
- [x] Revisions data under the files box
- [x] Contribute link on the right hand side of the readme
- [x] Bundle configuration under the readme
- [ ] Embed this bundle box on the right hand side of the readme
- [x] Charms, machines, units information in the bundle header at the top, this should go next to the charm author information so it read "By charmers • 5 charms, 5 machines, 5 units"

The comparison URLs are:

https://demo.jujucharms.com/?store=mediawiki-scalable
https://jujucharms.com/mediawiki-scalable/bundle/10

**Comment by hatched** [comment]
The same question about the juju-cards dependency applies here #1516

**Comment by frankban** [comment]
The two pages have been updated a lot since this bug was opened, and we have other bugs opened for the specific requests here.
