### ISSUE TITLE
Invalid absolute profile page URL

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#1528]
I am playing with my GUI in Juju at https://10.0.42.12:17070/gui/2e4ebfd0-8d2e-48ce-8a30-5694bcc1e748/
When I click to go to the profile page, this is the resulting URL: https://10.0.42.12:17070/profile/
So profile page link ignores the base URL for the application.

**Comment by kadams54** [comment]
I'm currently mucking about in that code and I noticed that the profile link in the breadcrumb is just a plain link. It may need to trigger a `changeState` call instead.
