### ISSUE TITLE
Validation error when adding credentials

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#1532]
When I added credentials for AWS I had a credential name with an underscore in it, but when I click Add credentials it took me to the summary but had an error in the console:

`Unable to add template cannot unmarshal parameters: cannot unmarshal into field: invalid name "huwshimi_test"`

**Comment by huwshimi** [comment]
Does anyone know what characters are valid for template names?

**Comment by hatched** [comment]
Here is the regex that's currently used to validate: `^[a-zA-Z0-9]([a-zA-Z0-9.-]*[a-zA-Z0-9])?$`
