### ISSUE TITLE
Add model UI in firefox is awry

### ISSUE THREAD

**Issue by bac** [juju/juju-gui#1539]
![screen shot 2016-04-11 at 17 07 56](https://cloud.githubusercontent.com/assets/617845/14442774/8ae389f8-0009-11e6-9ac1-9c849c8dd5c0.png)

This is with juju gui 2.1.2 (61926107003) running with GI Joe on wily, lxd, juju from today's master.

**Comment by bac** [comment]
On Chrome OS X it looks good:

![screen shot 2016-04-11 at 17 33 21](https://cloud.githubusercontent.com/assets/617845/14443190/a7ec1036-000b-11e6-899e-21da9e88e755.png)

**Comment by hatched** [comment]
Fixed in #1541
