### ISSUE TITLE
gtm-enabled is false on production

### ISSUE THREAD

**Issue by bac** [juju/juju-gui#1562]
If this value needs to be set to true on production then an update to mojo will be required.  Opening this issue to track and reach a decision.

**Comment by urosj** [comment]
@bac Please add RT to enable this on production for now.

**Comment by Lucapaulina** [comment]
Has this been cowboy'ed?

**Comment by bac** [comment]
This paste from today indicates it has not been update:
https://pastebin.canonical.com/155128/

I will do a mojo update now and get it applied.

**Comment by bac** [comment]
The change to staging has been blocked by ODS and will be unblocked on 2-May.

**Comment by bac** [comment]
This change has been rolled out to production.
