### ISSUE TITLE
The charm icon in the inspector disappears on 3rd level

### ISSUE THREAD

**Issue by Lucapaulina** [juju/juju-gui#1566]
If you navigate to any 3rd level page in the inspectors the charm icon disappears:

![image](https://cloud.githubusercontent.com/assets/5873394/14601194/a7715e52-0558-11e6-8990-96f161c01812.png)

![image](https://cloud.githubusercontent.com/assets/5873394/14601196/abb00c2a-0558-11e6-8424-d5c601ac7c94.png)

Chrome (v 45.0.2454.93)

**Comment by hatched** [comment]
Thanks for the report @Lucapaulina - This has already been fixed in develop but missed the 2.1.2 release.
