### ISSUE TITLE
Should sandbox mode show UUID in title

### ISSUE THREAD

**Issue by anthonydillon** [juju/juju-gui#1568]
If you go to https://demo.jujucharms.com/ the title of the page contains the environment UUID. This should show the environment name. Which in this case would be sandbox?

**Comment by Lucapaulina** [comment]
Yeah, it should show the name of the model not the UUID.

**Comment by hatched** [comment]
Related #1560

**Comment by huwshimi** [comment]
I believe this was fixed in #1596. Please reopen this if it can still be reproduced.
