### ISSUE TITLE
Exporting bundle fails with Javascript error

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#1576]
Originally reported by xtian muirhead at https://bugs.launchpad.net/juju-gui/+bug/1573021/
I confirm the JS error, seems to be related to relations handling when exporting the bundle.

Original report:
(This was pointed out to me by someone whose name I didn't catch - from going through the directory I think it might have been Maarten Ectors. He asked me to report the bug, he seemed like he was in a hurry to get to a demo.)

In the Juju GUI demo, add the Dataart Telco-Demo bundle (https://demo.jujucharms.com/inspector/drop-conference/?store=~dataart.telco/dataart-telco-demo).

Deploy the changes, then click the Export link - no bundle.yaml is downloaded.
Other bundles can be exported fine. We saw the same behaviour in Safari, Chrome on Mac and Chrome on Ubuntu.

In the Chrome console I see the following errors:

WebSocket connection to 'wss://demo.jujucharms.com/ws' failed: Invalid frame header
Uncaught TypeError: Cannot read property 'indexOf' of null

(Stack trace below)
(anonymous function)	@	combo?app/assets/javascripts/yui/promise/promise-min.js&app/models/models-min.js&app/store/endpoint…:5
e.ModelList.e.extend.each	@	combo?app/assets/javascripts/yui/querystring-parse/querystring-parse-min.js&app/assets/javascripts/…:16
_generateRelationSpec	@	combo?app/assets/javascripts/yui/promise/promise-min.js&app/models/models-min.js&app/store/endpoint…:5
exportDeployer	@	combo?app/assets/javascripts/yui/promise/promise-min.js&app/models/models-min.js&app/store/endpoint…:5
utils.exportEnvironmentFile	@	combo?app/assets/javascripts/yui/datatype-date-format/datatype-date-format-min.js&app/views/utils-m…:5
_handleExport	@	combo?app/components/entity-content/entity-content-revisions-min.js&app/components/entity-files/ent…:32
r	@	combo?app/assets/javascripts/react-with-addons.min.js&app/assets/javascripts/react-dom.min.js&app/a…:15
i	@	combo?app/assets/javascripts/react-with-addons.min.js&app/assets/javascripts/react-dom.min.js&app/a…:13
u	@	combo?app/assets/javascripts/react-with-addons.min.js&app/assets/javascripts/react-dom.min.js&app/a…:13
p	@	combo?app/assets/javascripts/react-with-addons.min.js&app/assets/javascripts/react-dom.min.js&app/a…:13
f	@	combo?app/assets/javascripts/react-with-addons.min.js&app/assets/javascripts/react-dom.min.js&app/a…:13
r	@	combo?app/assets/javascripts/react-with-addons.min.js&app/assets/javascripts/react-dom.min.js&app/a…:17
v.processEventQueue	@	combo?app/assets/javascripts/react-with-addons.min.js&app/assets/javascripts/react-dom.min.js&app/a…:13
r	@	combo?app/assets/javascripts/react-with-addons.min.js&app/assets/javascripts/react-dom.min.js&app/a…:15
a.handleTopLevel	@	combo?app/assets/javascripts/react-with-addons.min.js&app/assets/javascripts/react-dom.min.js&app/a…:15
i	@	combo?app/assets/javascripts/react-with-addons.min.js&app/assets/javascripts/react-dom.min.js&app/a…:15
a	@	combo?app/assets/javascripts/react-with-addons.min.js&app/assets/javascripts/react-dom.min.js&app/a…:15
o.perform	@	combo?app/assets/javascripts/react-with-addons.min.js&app/assets/javascripts/react-dom.min.js&app/a…:17
d.batchedUpdates	@	combo?app/assets/javascripts/react-with-addons.min.js&app/assets/javascripts/react-dom.min.js&app/a…:15
a	@	combo?app/assets/javascripts/react-with-addons.min.js&app/assets/javascripts/react-dom.min.js&app/a…:16
g.dispatchEvent	@	combo?app/assets/javascripts/react-with-addons.min.js&app/assets/javascripts/react-dom.min.js&app/a…:15

**Comment by huwshimi** [comment]
This is strange, it's clearly having a problem with one of the relations. It ends up with data for a relation being `display_name: ":"` and endpoints with uncommitted ids.

I noticed that in the bundle.yaml (https://api.jujucharms.com/charmstore/v5/~dataart.telco/bundle/dataart-telco-demo-6/archive/bundle.yaml) it has juju-info and wonder if this could be related to #1483.
