### ISSUE TITLE
UX required for destroyed models and the action of destroying a model

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#1581]
We need:
- [x] a button to destroy the current model. Note that only the current model can be destroyed via the Juju API, and also we want users to switch to the model the want to destroy, so that they double check before proceeding with exterminating every units and services;
- [x] a confirmation dialog like "are you sure you want to destroy the "foo" model?;
- [x] something that shows that the model is being destroyed in the profile page: after removing a model, it takes a while for really going away, and in the meanwhile we want to show that "the model is being destroyed" and prevent users from switching to zombie models.

**Comment by Lucapaulina** [comment]
@frankban we've been working on https://github.com/CanonicalLtd/juju-design/issues/65, it would solve issues 1 and 2 in your list above. In issue one it sort of seems like a user can only destroy a model from within the canvas, is that true? I think it would be better from the profile page.

We'll work on the third point.

**Comment by hatched** [comment]
@Lucapaulina due to technical limitations the user has to be connected to the model that they want to destroy. So if the user clicks the destroy button in the profile page we have to switch them into that model, show a confirmation dialogue and then destroy it.

**Comment by Lucapaulina** [comment]
Ok, thats not a bad compromise. I guess we would have to have a permanent notification in the canvas to notify users that the model is being destroyed too.

Can we show progress on the destroy? Is it based on number of units?

**Comment by hatched** [comment]
The deltas come in as Juju cleans up so we'll know that the model is being destroyed and the deltas will be removing things.

**Comment by Lucapaulina** [comment]
So, we can do a progress bar?

**Comment by hatched** [comment]
We....could.... :)

**Comment by huwshimi** [comment]
Awaiting JEM to provide the model lifecycle.

**Comment by huwshimi** [comment]
The new controller API has implemented the lifecycle methods and this is now complete.
