### ISSUE TITLE
Replace base64 SVGs

### ISSUE THREAD

**Issue by anthonydillon** [juju/juju-gui#1597]
If you load the GUI and look at the source. There are very large base65 images which cannot be optimised by the SVG sprite tool. These SVGs should be replaced with true vectors and if not available we should use a rasterised image like a PNG.

**Comment by anthonydillon** [comment]
One of the culprits is gcp.svg (Google cloud platform logo).

**Comment by hatched** [comment]
@anthonydillon is this still an issue?

**Comment by Lukewh** [comment]
Done
