### ISSUE TITLE
https://jujucharms.com/docs/devel/commands missing add-model

### ISSUE THREAD

**Issue by mthaddon** [juju/juju-gui#1598]
As the subject suggests, https://jujucharms.com/docs/devel/commands is missing the add-model command.

**Comment by mthaddon** [comment]
Actually, it looks like the command is create-model, and https://jujucharms.com/docs/devel/models-adding is wrong.

**Comment by hatched** [comment]
Thanks for the bug report, docs are actually handled by another team and so docs issues can be filed in the docs repository: https://github.com/juju/docs/issues
