### ISSUE TITLE
Juju GUI in Juju 2.0 uses a self-signed SSL certificate

### ISSUE THREAD

**Issue by mthaddon** [juju/juju-gui#1599]
The version of the Juju GUI embedded withing Juju 2.0 beta6 uses a self-signed certificate, and has no option to use a proper certificate (I'm also not sure if you could assign a hostname to the GUI and it would work as expected).

**Comment by frankban** [comment]
The embedded GUI is served by Juju and therefore uses the same certificate used by Juju API server. So I guess the option is the same already used for changing the controller/model certificate.
