### ISSUE TITLE
Store console errors

### ISSUE THREAD

**Issue by anthonydillon** [juju/juju-gui#1611]
I spotted there are quiet a few console errors when displaying the store. For example:
`flattenChildren(...): Encountered two children with the same key, .$bigdata. Child keys must be unique; when two children share a key, only the first child will be used.`

**Comment by hatched** [comment]
I'm not able to reproduce this, can you add reproduction steps  please.

**Comment by huwshimi** [comment]
This can be reproduced by searching for "big data".
