### ISSUE TITLE
Bundle importing does not surface errors from juju-bundlelib well enough

### ISSUE THREAD

**Issue by makyo** [juju/juju-gui#1614]
A bundle with errors in it produces errors in juju-bundlelib, but those errors aren't surfaced in the GUI when a bundle is deployed there.  Instead, some services are deployed but without config values or misplaced on units

```
firl_: “1.25.5-trusty-amd64” juju cli
firl_: juju-gui = latest charm
firl_: juju tools on state machine = https://streams.canonical.com/juju/tools/agent/1.25.5/juju-1.25.5-trusty-amd64.tgz
```

**Comment by hatched** [comment]
Do you have a bundle in question that this can be demonstrated with?

**Comment by frankban** [comment]
@makyo is this still the case with the new bundle service?

**Comment by frankban** [comment]
No feedback from quite a while, I guess this has been addressed in the meanwhile. Feel free to reopen otherwise.
