### ISSUE TITLE
Error loading models on profile in sandbox mode

### ISSUE THREAD

**Issue by anthonydillon** [juju/juju-gui#1639]
I am getting a continuous loader and an error in the console on the profile page:

```
HandleModelManagerModelInfo has not yet been implemented in the sandbox.
You can add the method in sandbox.js.
```

Running locally.

**Comment by huwshimi** [comment]
This error is due to the GUI not being connected to JEM with the default sandbox setup. I'm not sure if we should ignore this error and say that we now need to always connect to JEM or add some code for the sandbox case to ignore this error.

**Comment by anthonydillon** [comment]
I think the best thing would be to check if we are connected and if not hide the model section or show a message to the user. I will pick this up with UX today as I'm working on the profile.

**Comment by huwshimi** [comment]
I think this scenario is something that will only ever present it to us developers when we're working in the sandbox (which has less and less functionality as time goes on) with no JEM set up in development.ini so I'm not sure it's something we need to spend much time on (if at all).

**Comment by anthonydillon** [comment]
If JEM is not set up correctly or down. It would be nice to give a notice
to the user instead of a console error.
