### ISSUE TITLE
not all models shown in switcher for shared user account

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#1647]
I first created a controller and 5 models. I then did an add-user, and granted write access to two models of the 5. 

I went to another machine (lxd container) and setup Juju and ran the register command. I was told by Juju I had access to two models. I switched to one of them, and then ran "juju gui" and got an open GUI to that model. 

However, the second one, that I did not switch to, is not listed in the switcher and I'd expect it to be?

**Comment by hatched** [comment]
As discussed this was due to an old version of the GUI
