### ISSUE TITLE
Clicking on the midpoint closes the profile

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#1652]
If you have the profile open and click on the midpoint the profile closes. I'm not sure what the correct interaction should be, but it probably shouldn't be this.

**Comment by Lucapaulina** [comment]
The profile shouldn't close but the midpoint should open on top as it
technically sits a layer above.

**Comment by Lucapaulina** [comment]
I guess the question is, if you navigate to a charm and click add to
canvas, where does it add?

This would be good to implement the combo button where you can choose a
model to add to from the add to canvas button. I'll attach designs once I'm
in.

**Comment by Lucapaulina** [comment]
![combo-button-01](https://cloud.githubusercontent.com/assets/5873394/15251427/40577c42-1921-11e6-9231-cd9143fb8e24.png)
![combo-button-02](https://cloud.githubusercontent.com/assets/5873394/15251425/40553c52-1921-11e6-9114-2bc657241df8.png)
![combo-button-03](https://cloud.githubusercontent.com/assets/5873394/15251426/40554972-1921-11e6-8c97-e7394276ea90.png)

**Comment by huwshimi** [comment]
Thanks @Lucapaulina!

**Comment by huwshimi** [comment]
This has been fixed.
