### ISSUE TITLE
Connecting a service twice results in an error

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#1654]
- add 2 x wordpress services
- add apache2
- connect apache2 to the first wordpress
- connect apache2 to the second wordpress
- in your browser console should be `Uncaught TypeError: Cannot read property '_isYUIModelList' of undefined`

**Comment by frankban** [comment]
Does this issue still exist Huw?

**Comment by huwshimi** [comment]
@frankban I couldn't reproduce this.
