### ISSUE TITLE
New model not created

### ISSUE THREAD

**Issue by jogeo** [juju/juju-gui#1683]
I tried adding a new model from the services page but clicking the 'new' button seems to do nothing.
(e.g. https://192.168.2.150:17070/gui/eb669c14-ac04-4318-85ac-c402a03a9bff/services/ )

cdoqa@maas-node-2:~$ juju --version
2.0-beta7-xenial-amd64
cdoqa@maas-node-2:~$ juju list-models
NAME      OWNER        STATUS     LAST CONNECTION
admin     admin@local  available  3 minutes ago
default*  admin@local  available  3 minutes ago

![gui_new_model_does_nothing](https://cloud.githubusercontent.com/assets/8658422/15405741/07b25df8-1db8-11e6-9fc0-de6d2b00e8f1.png)

**Comment by hatched** [comment]
Thanks for the report @jogeo 

This is a regression and we're hoping to get a fix out next week.

**Comment by hatched** [comment]
In the develop branch this feature has been removed and replaced by a "create" button in the profile page which can be viewed by clicking "Profile" in the new model switcher or by clicking your user name in the top left of the page. This will land in the next GUI release.
