### ISSUE TITLE
The profile page only shows the current user

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#1690]
From what I understand we should be able to use the profile page to display the details for all users and not just the currently logged in one e.g. here: https://github.com/juju/juju-gui/pull/1688#discussion_r64198271

I'm not sure about the navigation/urls around displaying the profile.

**Comment by Lucapaulina** [comment]
I should be able to see my profile at www.jujucharms.com and I should be
able to see your profile at www.jujucharms.com/u/huwshimi

If I'm viewing someone else's profile then when I click on a bundle or
charm it should take me to the relevant bundle or charm details. If I'm on
my own then when I click them they should expand to show more information.

**Comment by huwshimi** [comment]
So maybe we should link to jujucharms.com for other people's profiles?

**Comment by Lucapaulina** [comment]
That would work I think. @urosj, @anthonydillon and @hatched what do you think?

**Comment by anthonydillon** [comment]
Yea I think that is best. It makes it easier to maintain one profile
visitors template. Once we have persistence it will be seamless.

I think we should think about which templates will we need to duplicate in
the GUI once we have persistence.

**Comment by hatched** [comment]
I don't agree with this, I believe that we should leave the user in the GUI once they are in the GUI. It would be too easy to click the username in the GUI, end up on jujucharms.com then click another charm and then have to load back into the GUI to deploy it. This introduces the issue of what the url should be for this but at first glance I'm thinking something like `/profile/u/huwshimi` this would allow us to have additional nestings in the `/profile` namespace for the logged in user. For example `/profile/bundles` would show you only your bundles, `profile/u/huwshimi/bundles` would show you only the bundles from that user.

**Comment by anthonydillon** [comment]
If we are to build the full profile system in the GUI then I think we
should try and keep the URLs consistent. So I propose /u/huwshimi for
visitors profile and /profile for your own profile.

**Comment by Lucapaulina** [comment]
Jeff i think you raise good use cases to make the profile in the GUI, might
need to discuss this with @urulama. I agree with Ant in that we should aim
for consistency, so /u/huwshimi for someone else's profile. I wonder if
/profile is right...

**Comment by huwshimi** [comment]
This has now been implemented.
