### ISSUE TITLE
'juju gui --no-browser --show-credentials' as the help text to get password

### ISSUE THREAD

**Issue by arosales** [juju/juju-gui#1691]
Suggest that we use:
`juju gui --no-browser --show-credentials`

as the help text below the login for the Juju GUI.  It is currently set to `juju show-controllers --show-passwords` which isn't as intuitive as the `juju gui ` command.

**Comment by hatched** [comment]
We display different messages for different versions of Juju so this would have to be updated for just the Juju 2 version.

**Comment by nobuto-m** [comment]
Agreed. `juju show-controller --show-password` outputs 51 lines in my case, thus it's hard to find username and password.

> We display different messages for different versions of Juju so this would have to be updated for just the Juju 2 version.

It looks like already possible. "juju api-info" for legacy one, "juju show-controller" for 2.0 at this moment.
https://github.com/juju/juju-gui/blob/2.1.8/jujugui/static/gui/src/app/app.js#L714-L735

**Comment by lathiat** [comment]
The current text is also wrong, it says "--show-passwords" when the correct text is "--show-password" so this needs to be fixed in any case.  Obvious fix is to change it as agreed here - it's much more friendly.

Because the current text is wrong, I propose the priority on this is raised and handled as release critical.

**Comment by hatched** [comment]
Hello all, a new version of the GUI has been released which resolves this issue. It can be downloaded from Github here: https://github.com/juju/juju-gui/releases/download/2.1.9/jujugui-2.1.9.tar.bz2 

At the time I'm writing, it isn't yet in simplestreams so the default version of the GUI installed with Juju will still be 2.1.8 but that should be remedied in about a week when Ubuntu Xenial gets Juju 2.0.0-Beta 14

To use the latest version of the GUI:

``` bash
wget https://github.com/juju/juju-gui/releases/download/2.1.9/jujugui-2.1.9.tar.bz2
juju upgrade-gui /path/to/jujugui-2.1.0.tar.bz2
juju gui --show-credentials
```
