### ISSUE TITLE
Add directly to canvas from search results

### ISSUE THREAD

**Issue by Lucapaulina** [juju/juju-gui#1692]
See here for design: https://github.com/CanonicalLtd/juju-design/blob/master/Store/Search_add_to_canvas.png

**Comment by Lucapaulina** [comment]
@faooful can you provide assets here for this?

**Comment by faooful** [comment]
https://www.dropbox.com/s/dsdtf3uie6v3go7/plus-icon.svg?dl=0

**Comment by Lucapaulina** [comment]
@faooful Can you add assets to gdrive, the devs don't have access to dropbox.

**Comment by hatched** [comment]
we can access that one - but the asset is broken - the + is way off centre according to the display in DB

**Comment by Lucapaulina** [comment]
yeah, that is odd.

**Comment by faooful** [comment]
https://drive.google.com/open?id=0Bx4cmJeOod4icG9zcTM3VXRkUnc
