### ISSUE TITLE
500 error design

### ISSUE THREAD

**Issue by Lucapaulina** [juju/juju-gui#1694]
This design: https://github.com/CanonicalLtd/juju-design/blob/master/Extraneous%20pages/500_error_store.png

Should show when this error appears: https://demo.jujucharms.com/?store=kubernetes-core

**Comment by Lucapaulina** [comment]
@faooful can you provide assets here for this?

**Comment by faooful** [comment]
![500-img](https://cloud.githubusercontent.com/assets/2169216/15534602/7543f518-2261-11e6-8091-4a7e3eab96e7.png)

**Comment by huwshimi** [comment]
This looks like it's for jujucharms.com and the mockup is no longer valid.
