### ISSUE TITLE
New 404 design

### ISSUE THREAD

**Issue by Lucapaulina** [juju/juju-gui#1695]
See here: https://github.com/CanonicalLtd/juju-design/blob/master/Extraneous%20pages/404.png

**Comment by Lucapaulina** [comment]
@faooful can you provide assets here for this?

**Comment by faooful** [comment]
![404-img](https://cloud.githubusercontent.com/assets/2169216/15534482/f5795a76-2260-11e6-8b5d-24e33973e5ad.png)

**Comment by ClaraLavina** [comment]
Support > Ask for support page has an old design.

<img width="957" alt="screen shot 2017-05-04 at 11 02 49" src="https://cloud.githubusercontent.com/assets/22299251/25699215/329e09f2-30ba-11e7-894c-31c9e225767b.png">

**Comment by hatched** [comment]
@ClaraLavina that image is one returned by jujucharms.com not the GUI fyi.

**Comment by ClaraLavina** [comment]
Thanks!

**Comment by huwshimi** [comment]
This has been moved to CanonicalLtd/jujucharms.com#461.
