### ISSUE TITLE
New notifications in the GUI

### ISSUE THREAD

**Issue by Lucapaulina** [juju/juju-gui#1696]
We've revamped notifications in the GUI. They no longer appear as bubbles in the bottom left but as snackbar notifications at the top of the screen.

https://github.com/CanonicalLtd/juju-design/tree/master/Notifications

Spec: https://docs.google.com/document/d/1l3G2TwpzI17iEXJFLz2-w3W5Wl8CigiuTgw8Eijo7es/edit#bookmark=id.bey8jffqidql

Super error: Red, has to be dismissed, does not fade away. (Only used for small window)
Error: Red, fades away after 5 seconds.
Blocked: Orange, fades after 3 seconds.
Success: Green, fades after 3 seconds.
Feedback: White, fades away after 3 seconds.

You can see the list of things which should trigger the snackbar here: https://docs.google.com/document/d/1l3G2TwpzI17iEXJFLz2-w3W5Wl8CigiuTgw8Eijo7es/edit#heading=h.1q82kh5nqdvr

**Comment by hatched** [comment]
Closing this bug as a new-new notification spec is coming down the pipe
