### ISSUE TITLE
Change the icon on the relation tooltips

### ISSUE THREAD

**Issue by Lucapaulina** [juju/juju-gui#1698]
When you click on a relation we show the status of the relation. We've changed the icons, the new designs can be seen here:

https://github.com/CanonicalLtd/juju-design/tree/master/Inspector/Relations

@faooful can you add the new icons to this issue please?

**Comment by faooful** [comment]
Error - https://dl.dropboxusercontent.com/content_link/nNWWPJAHw6ZIwk6mJNNKcWFyt3dkZM4nermcq7lUDWis3ciJwWYkzhI2EU26s7VF/file

Pending - https://dl.dropboxusercontent.com/content_link/J2hnv2ofLmVxQ9tFlcbEilbwrbBsoerqnsGGBSw2v5aP1ZixcjAW2PUxruXrbm0f/file

Uncommitted - https://dl.dropboxusercontent.com/content_link/Z45n6W46gPOOiCCURKN4l14hLZWyYWoFBT17DLGFQyvlassLixysg27qdcX42btz/file

**Comment by faooful** [comment]
https://drive.google.com/open?id=0Bx4cmJeOod4iTUp4TU9qbDA0VUE

**Comment by huwshimi** [comment]
What icon should we use when in the normal committed state? The current one doesn't use the same style as the new icons.

**Comment by ClaraLavina** [comment]
maybe @spencerbygraves could help here

**Comment by spencerbygraves** [comment]
I've discussed this with @cassiocassio who first wants to better understand how relation errors work.

**Comment by spencerbygraves** [comment]
@huwshimi do you mean the grey circle with white tick, or the green icon with white triangle shown when you click the relation?

**Comment by huwshimi** [comment]
@spencerbygraves the green icon when you click the relation.

**Comment by spencerbygraves** [comment]
As we don't have a green state for working in the GUI, perhaps an icon for a normal committed state is unnecessary?

**Comment by huwshimi** [comment]
@spencerbygraves thanks, I'll remove it.
