### ISSUE TITLE
Show unit status in the inspector units master listing

### ISSUE THREAD

**Issue by Lucapaulina** [juju/juju-gui#1699]
On request we've added status to the units master list. This is shown with a status icon for each unit, the design can be seen here:

https://github.com/CanonicalLtd/juju-design/blob/master/Inspector/Inspector_unit_status.png

@faooful can you add assets? :)

**Comment by faooful** [comment]
Error - https://dl.dropboxusercontent.com/content_link/nNWWPJAHw6ZIwk6mJNNKcWFyt3dkZM4nermcq7lUDWis3ciJwWYkzhI2EU26s7VF/file

Pending - https://dl.dropboxusercontent.com/content_link/J2hnv2ofLmVxQ9tFlcbEilbwrbBsoerqnsGGBSw2v5aP1ZixcjAW2PUxruXrbm0f/file

Uncommitted - https://dl.dropboxusercontent.com/content_link/Z45n6W46gPOOiCCURKN4l14hLZWyYWoFBT17DLGFQyvlassLixysg27qdcX42btz/file

**Comment by faooful** [comment]
https://drive.google.com/open?id=0Bx4cmJeOod4iTUp4TU9qbDA0VUE

**Comment by huwshimi** [comment]
We now show the full status in the list.
