### ISSUE TITLE
Add the onboarding tooltip to the relations block on charm details 

### ISSUE THREAD

**Issue by Lucapaulina** [juju/juju-gui#1701]
See designs here: https://github.com/CanonicalLtd/juju-design/blob/master/Utilities/Onboarding/Onboarding_relations.png

Text should read: "Relations enable services to easily and securely share information with each other, without you having to worry about any manual configuration."

**Comment by elvirafigueras** [comment]
Updates on this? @huwshimi

**Comment by hatched** [comment]
@elvirafigueras we update the issues with the current milestone and assignee when we start working on them.

**Comment by huwshimi** [comment]
Is this still relevant? I see that the mockup has been removed.

**Comment by Lukewh** [comment]
It's been over a year since this issue was created and 4 months since any kind of activity - closing. If it's still relevant reopen and tag relevant parties.
