### ISSUE TITLE
Update the charm action links to the new world order

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#1704]
The contribute and bug links for charms and bundles are changing/have changed and we need to figure out how to handle them. See the discussion here: https://github.com/juju/juju-gui/pull/1688#discussion_r64605199

**Comment by hatched** [comment]
After a discussion we've decided to not show any links unless they are explicitly defined in the common-info endpoint. In the case where there isn't one defined a tooltip will be shown with instructions on how to add a bug-url and homepage to the entity.

You can add a 'homepage' and 'bug-url' to your charms by running:
charm set juju-gui --channel development homepage=https://github.com/juju/juju-gui/

The information is then available at:
https://api.jujucharms.com/charmstore/v4/juju-gui/meta/common-info

**Comment by anthonydillon** [comment]
I think it would be a better user experience to should the notice about no
bug or project URL exists and the tooltip with how to add it. If you are
the author of the current details page. If you are not then it probably
should show nothing as the tooltip will not be relevant.

**Comment by galgalesh** [comment]
Bumping this issue

- the "contribute" link in the Juju gui is completely wrong.
- the "home" and "gui" link isn't shown.

Jujucharms: https://jujucharms.com/kubernetes-core/
Juju GUI: https://demo.jujucharms.com/?store=cs:bundle/kubernetes-core-14
