### ISSUE TITLE
Add tooltips to the import and export buttons at the top of the canvas masthead

### ISSUE THREAD

**Issue by Lucapaulina** [juju/juju-gui#1707]
It would be good to add our tooltip when you hover over the import or export button. The tooltips in this case, since they are on an icon, should appear instantly on hover.

![image](https://cloud.githubusercontent.com/assets/5873394/15574293/6b86f4f6-2344-11e6-9d1f-4aa0d611a520.png)

Our tooltip styling can be found here:
https://github.com/CanonicalLtd/juju-design/tree/master/Utilities/Tooltip

**Comment by hatched** [comment]
Both the import and export buttons have a "title" field defined and because of that have a tooltip when being hovered. Just to clarify that you'd like us to implement a custom tooltip instead of relying on the native implementations?
