### ISSUE TITLE
Loading the gui with the profile open errors

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#1711]
If you load the gui with /profile/ in the URL you get the following error:

`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.`

**Comment by huwshimi** [comment]
It's possible this is only without jem.

**Comment by hatched** [comment]
This is no longer an issue, closing.
