### ISSUE TITLE
If connected to the destroyed model, switch to profile page.

### ISSUE THREAD

**Issue by urosj** [juju/juju-gui#1718]
If you're connected to a model (in GIJoe) and a user destroys a model through CLI, GUI should detect the change and end up in the profile page.

**Comment by huwshimi** [comment]
Waiting for JEM lifecycle flags.

**Comment by huwshimi** [comment]
It doesn't look like app.env gets any attr updates when the model is destroyed from the CLI, not sure how we should proceed with this.

**Comment by frankban** [comment]
Closing in favor of a more generic feature discussion at https://github.com/juju/juju-gui/issues/2950
