### ISSUE TITLE
realtime-syslog-analytics bundle fails to load details page

### ISSUE THREAD

**Issue by urosj** [juju/juju-gui#1719]

**Comment by anthonydillon** [comment]
Do you mean the link from the big-data page? Seem to open OK for me.

https://jujucharms.com/realtime-syslog-analytics/

**Comment by urosj** [comment]
@anthonydillon no, in GUI, search for realtime, try to load details page from search results.

**Comment by urosj** [comment]
This seems to be a problem from charm store:
https://api.jujucharms.com/charmstore/v5/bundle/realtime-syslog-analytics/meta/owner and https://api.jujucharms.com/charmstore/v5/bundle/realtime-syslog-analytics/meta/any state revision 15.

https://api.jujucharms.com/charmstore/v5/bundle/realtime-syslog-analytics-15/meta/published shows it's the default stable revision.

However:
https://api.jujucharms.com/charmstore/v4/~bigdata-charmers/bundle/realtime-syslog-analytics/meta/any
Points to revision 1.
https://api.jujucharms.com/charmstore/v5/~bigdata-charmers/bundle/realtime-syslog-analytics/meta/published
Also shows it's the default. 

Once charm store is fixed, this will be resolved.
