### ISSUE TITLE
comingsoon staging server down

### ISSUE THREAD

**Issue by wurde** [juju/juju-gui#1727]
This is either an old link or the server is down. As seen on juju-gui charm README.

> A [staging server](http://comingsoon.jujucharms.com/) is also available, running the latest and greatest version.

[https://jujucharms.com/juju-gui/](https://jujucharms.com/juju-gui/)

**Comment by hatched** [comment]
Hi Any, thanks for the report! 

That is an old link and the docs should be updated, we don't generate those releases any longer as we've been moving towards a much quicker release cycle.

**Comment by hatched** [comment]
This issue can be tracked on the charm repository: https://github.com/juju/juju-gui-charm/issues/68
