### ISSUE TITLE
Show message when need to authenticate

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#1730]
Sometimes you need to authenticate with identity (I think) and if the request times out it has an error. We should catch that error and show a message saying you need to log in (or refresh the GUI) or something, otherwise you just get the spinner forever.

**Comment by Lucapaulina** [comment]
You can see our notification styles here: https://github.com/CanonicalLtd/juju-design/tree/master/Notifications

For this we can use the Error toast design.

**Comment by huwshimi** [comment]
We shouldn't hit these errors in production as when the GUI is connected to JEM it'll be embedded in the storefront and the storefront will do the authentication checks.
