### ISSUE TITLE
Annotations expanded

### ISSUE THREAD

**Issue by wurde** [juju/juju-gui#1737]
I like moving away from traditional static architecture diagrams and using JuJu GUI & JuJu bundles to create a living model of our architectures. Maintainable and functional architectural diagrams are brilliant and much needed, however context is lacking in what we have now.

Currently models require a combination of understanding the individual services and their intended application within the model. Could we add facilities to help surface and detail this information so the models are self-explaining or at least a way to document the intent of the author.

One idea is to expand the annotations: attribute within bundles to have go beyond gui-x and gui-y information to contain a comment: attribute.

**Comment by hatched** [comment]
Thanks for bringing this up. Could you elaborate a little more on what you'd like to add to this `comment` attribute and how you'd like it presented in the GUI?

**Comment by wurde** [comment]
![juju-model](https://cloud.githubusercontent.com/assets/5455357/15793384/378b5a1e-29a9-11e6-83d3-963e1a374a90.png)

**Comment by wurde** [comment]
The above is a deployed bundle for **High Performance Batch Processing** as JuJu displays it now.
[https://jujucharms.com/high-performance-batch-processing/bundle/5](https://jujucharms.com/high-performance-batch-processing/bundle/5)

**Comment by wurde** [comment]
We could bury the annotation in the menu as that's where the service names have moved.
![services-menu](https://cloud.githubusercontent.com/assets/5455357/15793467/c48cc97a-29a9-11e6-840d-568fed2105a0.png)

**Comment by wurde** [comment]
The juju charm store bundle previews look like this.
![juju-charm-preview](https://cloud.githubusercontent.com/assets/5455357/15793517/09333de8-29aa-11e6-8b4e-bd8edf6879b2.png)

**Comment by wurde** [comment]
I'm agnostic to wither the labels should be over the graphical models or simply highlighted in the menu when hovered over (though I lean towards the menu that we have currently). What I care about is adding some metadata that goes beyond the service name.

**Comment by wurde** [comment]
If I share this architecture with another developer I'd want them to understand the intent behind the services in context of the model. The service names help with **compute-node** and **yarn-hdfs-master** differentiating the two hadoop services. Playing around with the relations navigations in the GUI I'm not sure an expanded annotations is necessary and may actually make the model brittle in the long term. Let's keep things functional and not add this.
