### ISSUE TITLE
GUI tests fail with the service -> application rename

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#1739]
As seen here:

http://reports.vapour.ws/releases/issue/5751c49e749a56711194b318

Copied from https://bugs.launchpad.net/juju-gui/+bug/1588922

**Comment by hatched** [comment]
Thanks for the report @mitechie this is a known issue and we're planning on performing the necessary renaming next week.

**Comment by hatched** [comment]
The GUI has had the proper updates made but can't yet get into simplestreams yet. So I'll close this as it should resolve once the simplestreams release is able to be updated.
