### ISSUE TITLE
Scrolling issue on charm/bundle details breaks w/ cursor high on page

### ISSUE THREAD

**Issue by makyo** [juju/juju-gui#1760]
Position cursor over the copy-paste CLI deploy command on a details page and scroll down using trackpad/scrollwheel.  When the sticky header drops down, it will capture scroll events and cause the page to stop scrolling

**Comment by huwshimi** [comment]
One way to fix this would be to set `pointer-events: none` on the header when it is sticky and then set `pointer-events: auto` on every element in the sticky header that needs interaction (links, buttons etc.)
