### ISSUE TITLE
Test failing after clean/build

### ISSUE THREAD

**Issue by makyo** [juju/juju-gui#1767]
```
$ make clean-all fast-babel test-js-old
...
SUMMARY:
✔ 1402 tests completed
ℹ 27 tests skipped
✖ 1 test failed

FAILED TESTS:
  application hotkeys
    ✖ "before all" hook
      PhantomJS 2.1.1 (Linux 0.0.0)
    timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
$ make test-js-old
...
SUMMARY:
✔ 1405 tests completed
ℹ 27 tests skipped
```

**Comment by huwshimi** [comment]
@makyo I just ran `make clean-all fast-babel test-js-old` with the latest develop and didn't get any failures. Are you still able to reproduce this?

**Comment by hatched** [comment]
This appears to have something to do with the removal of the nested YUI deps caused by the npm3 update that we remove as to avoid bloating the dist. I'm not entirely sure how we can get around this.

**Comment by hatched** [comment]
It's been a while for this one and there haven't been any more reports, please re-open if you're still seeing this.
