### ISSUE TITLE
Use https and not git

### ISSUE THREAD

**Issue by codeyash** [juju/juju-gui#1772]
################
    # Download cache
    ################
    $(CACHE):

Replace this

	git clone --depth=1 "git@github.com:juju/juju-gui-downloadcache.git" $(CACHE)

with

    git clone --depth=1 "https://github.com/juju/juju-gui-downloadcache.git" $(CACHE)

Please use https version. 

There is no requirement of key in second case.

**Comment by codeyash** [comment]
I  related pull request also.

https://github.com/juju/juju-gui/pull/1773

**Comment by hatched** [comment]
#1650
