### ISSUE TITLE
Feature Request: add-machine via the gui does not take series as an option

### ISSUE THREAD

**Issue by arosales** [juju/juju-gui#1788]
When I want to add a machine via the GUI I can set constraints but I cannot specify config such as series for the machine. This is troublesome in 2.0 as the default is Xenial, but I very well may want a Trusty machine.

At the command line I can issue:
`juju set-model-config -m mymodel default-series=trusty
`
but I cannot do this in the GUI via the Machine Tab -> Add Machine option.

**Comment by valeech** [comment]
+1

**Comment by hatched** [comment]
This is a great idea, thanks for the request, I'll add it to the roadmap
