### ISSUE TITLE
"Featured Search" on demo.jujucharms.com references very old Hadoop charm

### ISSUE THREAD

**Issue by anthonydillon** [juju/juju-gui#1796]
The "Featured Search" that comes up when adding a charm on demo.jujucharms.com (and presumably any instance of the GUI) recommends a very old Hadoop charm. (In fact, we plan to unpromulgate this charm soon, as it is not maintained.) Instead, the hadoop-processing bundle should be recommended.

**Comment by kadams54** [comment]
Pointing it to hadoop-processing is no problem, but it does raise a few questions:

1. hadoop-processing is only on production, not on staging or guimaas. Are we OK with the link breaking in those environments?
2. What icon do we want to use? We can point to the generic bundle icon, but that's pretty ugly for something featured. We can continue pointing to the same Hadoop icon, but not sure if we want to do that if the charm is going to be unpromulgated.
3. This will be the only bundle in the Featured Search; is that OK?

**Comment by anthonydillon** [comment]
1. This is a issue a raised a while ago. I believe @urosj is working on a way to sync them in the future.
2. I think we can use the nice icon as we are removing the bundle icons so it wont be confusing to users.
3. Yeah that is ok, We feature both charms and bundles in the new store page.
