### ISSUE TITLE
Could not add the requested machine. Server responded with: unknown object type "Client"

### ISSUE THREAD

**Issue by huegelc** [juju/juju-gui#1827]
Hi,

using juju 2.0-beta1 with the gui client 2.1.2 Every time i want to deply changes I get following error

`Could not add the requested machine. Server responded with: unknown object type "Client"`

How can I fix this? Thank you

**Comment by hatched** [comment]
Hi, sorry about that. I'm assuming that you meant to say you were using beta11. In which case the version of the GUI which is in simple streams (2.1.2) does not support beta 11. Until that can be updated you can download and upgrade to the latest GUI release:

```Bash
# Bootstrap your controller
juju bootstrap lxd lxd

# Download the latest release
wget https://github.com/juju/juju-gui/releases/download/2.1.8/jujugui-2.1.8.tar.bz2

# Upgrade the release in that controller
juju upgrade-gui /path/to/jujugui-2.1.8.tar.bz2

# Open the GUI
juju gui --show-credentials
```

**Comment by huegelc** [comment]
Thank you. That did the trick :)

**Comment by hatched** [comment]
Glad to help!

**Comment by PingLord** [comment]
Hello,

I have the same issues with juju gui 2.1.8. I can deploy without issues from the CLI but from the juju-gui i always get the same error : 

Could not add the requested unit. Server responded with: unknown object type "Client"
Could not deploy the requested service. Server responded with: unknown object type "Client"
Could not add the requested machine. Server responded with: unknown object type "Client"

Any idea?
