### ISSUE TITLE
test_upgrade_gui fails with juju-beta12

### ISSUE THREAD

**Issue by nskaggs** [juju/juju-gui#1851]
uitest/suite/juju.py:211: in controller_info
    0, retcode, 'cannot retrieve controller info: {}'.format(error))
E   AssertionError: 0 != 2 : cannot retrieve controller info: error: flag provided but not defined: --show-passwords

See http://reports.vapour.ws/releases/4141/job/function-uitest-gui/attempt/268#highlight

**Comment by sinzui** [comment]
As of commit
    https://github.com/juju/juju/commit/ef5ff9f3160a51e1964943532191df95644665d5

--show-passwords was renamed to --show-password. The uitests must be updated.

**Comment by jaycee** [comment]
I have a fix ready; I'll send it up for review tomorrow. 

Sent from a mobile device with a very small keyboard. Please forgive typos.




On Fri, Jul 15, 2016 at 7:10 PM -0400, "Curtis Hovey" <notifications@github.com> wrote:












As of commit

    juju/juju@ef5ff9f



--show-passwords was renamed to --show-password. The uitests must be updated.
