### ISSUE TITLE
Overlapping booleans configuration sidebar

### ISSUE THREAD

**Issue by ghost** [juju/juju-gui#1859]
The current fixed-width solution works 99% of the time. And to be fair I'm trying to charm GitLab, which is an amalgam of applications. A one-to-one naming of options provided in gitlab.rb produces the below results, so I can just abstract the names and lose some context. I'm not sure of an easy design solution either. Overall, very happy with the Juju GUI.

![overlapping_booleans](https://cloud.githubusercontent.com/assets/5455357/16962727/7a95ff34-4db8-11e6-82df-74c3109ac2a4.png)

**Comment by hatched** [comment]
Thanks for the bug @wurde we'll take a look at this.

On a somewhat unrelated note, while I'm not familiar with GitLab's architecture, typically you'd want a different charm for each of the different applications in your architecture. You'd then create a bundle which would handle deploying them all at once with your predefined relations and configuration values.

This allows you to simplify your charm logic, and scale/modify your various applications independently. It also has a side effect that you don't need to prefix the configuration options for each application ;)

**Comment by wurde** [comment]
Totally in agreement on how best to construct charms. It's GitLab isn't my solution and, for my use-case, it's much simpler to wrap the (ever changing) solution into one charm than it is to break it out into separate charms.
