### ISSUE TITLE
Unable to deploy bundles in sandbox mode

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#1860]
When trying to deploy a bundle in sandbox mode an error is presented to the user: 

`The following errors occurred while retrieving bundle changes: not implemented (sandbox mode)` 

It appears to be making a websocket connection, sending the bundle changes and then having it rejected as not supported.

**Comment by frankban** [comment]
This is expected, and @makyo is working on a micro-service that will provide the bundlechanges functionality for the GUI in the form of a restful endpoint for cases when Juju is not available (sandbox mode). The GUI used to connect to the GUI server at demo.jujucharms.com, which uses jujubundlelib, and we decided to drop support for that as it going to be more and more out of sync with the Go bundlechanges as included in Juju.

**Comment by hatched** [comment]
This was fixed by #2048
