### ISSUE TITLE
juju show-controller --show-passwords is now juju show-controller --show-password

### ISSUE THREAD

**Issue by nskaggs** [juju/juju-gui#1869]
The gui login screen still shows juju show-controller --show-passwords, rather than the proper command which drops the plural for singular.

**Comment by anthonydillon** [comment]
Thank you for the issue. This has just been proposed and should be available in the next release.

**Comment by hatched** [comment]
Fixed by #1866

**Comment by mitechie** [comment]
What's the timeline for an updated release to have the correct instructions
available to users getting Juju from xenial?
