### ISSUE TITLE
Update model methods facade 

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#1876]
In Juju master, 3 methods have been moved from the `Client` facade to the `ModelConfig` facade:

- ModelGet
- ModelSet
- ModelUnset

ex) 

```JavaScript
this._send_rpc({
  type: 'Client',
  request: 'ModelGet'
}, cb);
```

now becomes:

```JavaScript
this._send_rpc({
  type: 'ModelConfig',
  request: 'ModelGet'
}, cb);
```

**Comment by frankban** [comment]
The GUI currently only uses ModelGet, and only when using the MAAS provider.
I'll fix this asap.
