### ISSUE TITLE
Could not add the requested machine. Server responded with: unknown object type "Client"

### ISSUE THREAD

**Issue by PingLord** [juju/juju-gui#1889]
Hello,

I have the same problems reported in #1827  with juju gui 2.1.8. I can deploy without issues from the CLI but from the juju-gui i always get the same error :

Could not add the requested unit. Server responded with: unknown object type "Client"
Could not deploy the requested service. Server responded with: unknown object type "Client"
Could not add the requested machine. Server responded with: unknown object type "Client"

Any idea?

**Comment by urosj** [comment]
Hi, 

Which juju version was used to bootstrap the controller?

**Comment by PingLord** [comment]
$ juju status
MODEL    CONTROLLER  CLOUD/REGION         VERSION
default  lxd-test    localhost/localhost  2.0-beta13

APP        VERSION  STATUS   EXPOSED  ORIGIN      CHARM      REV  OS
juju-gui            unknown  true     jujucharms  juju-gui   130  ubuntu

**Comment by hatched** [comment]
Thanks for the report @PingLord I'll be investigating shortly.

**Comment by hatched** [comment]
I haven't been able to reproduce this issue using Juju 2 beta13/14 with the GUI release archive from github or the one which is delivered on a fresh Juju bootstrap using Ubuntu 14.04 or 16.04.

Could you open up your browser console and run the following commands and reply with the values.

`app.isLegacyJuju()`

`app.get('jujuCoreVersion')`

**Comment by PingLord** [comment]
app.isLegacyJuju()
VM355:1 Uncaught TypeError: app.isLegacyJuju is not a function(…)(anonymous function) @ VM355:1

app.get('jujuCoreVersion')
"2.0-beta13-trusty-amd64"

**Comment by hatched** [comment]
As I suspected you're not actually running GUI 2.1.8 as the isLegacyJuju method was added in 2.1.8. When bootstrapping a new model Juju should be pulling down the latest version of the GUI (2.1.8 in this case). For some reason it looks like that didn't happen and you'll need to follow the steps outlined in #1827 to update it.

**Comment by hatched** [comment]
You can confirm this by visiting the following url:

`https://<api-address>:17070/gui-archive`

You should then see output similar to:

```
{
  versions: [
    {
      version: "2.1.8",
      sha256: "57ceac72f84d820fd675bb1439cee013fb35df19a0f535e58b1f75acbf4bf2cb",
      current: true
    }
  ]
}
```

**Comment by PingLord** [comment]
I've tried the solution from the other ticket but the only message i get is the following : 

`$ juju-2.0 upgrade-gui jujugui-2.1.8.tar.bz2
Juju GUI at version 2.1.8
`

Restarted the server and the same. 
I have deployed and destroyed the app multiple times. Tested on 2 physical servers...

Any idea?

**Comment by hatched** [comment]
@PingLord We have just released a new version of the Juju GUI. Could you please check if the issue has been resolved with this latest version?

``` bash
# Bootstrap your controller
juju bootstrap lxd lxd

# Download the latest release
wget https://github.com/juju/juju-gui/releases/download/2.1.9/jujugui-2.1.9.tar.bz2

# Upgrade the release in that controller
juju upgrade-gui /path/to/jujugui-2.1.9.tar.bz2

# Open the GUI
juju gui --show-credentials
```

**Comment by PingLord** [comment]
Everything works perfect until now.

Thank you very much for this and great work.

**Comment by hatched** [comment]
Great, thanks!
