### ISSUE TITLE
Message incorrect when adding relation

### ISSUE THREAD

**Issue by bac** [juju/juju-gui#1912]
With 2.1.9 on AWS I found ` /?store=cs:bundle/rails-example-single-6` and added the bundle to the canvas. The following message appeared.  `[Object object] `needs to be fleshed out.

![screen shot 2016-08-10 at 13 26 43](https://cloud.githubusercontent.com/assets/617845/17563687/8045d6e6-5efe-11e6-813b-a1bc8d42f0a8.png)

**Comment by bac** [comment]
Probably related, there are JS errors when trying to deploy the bundle:

![screen shot 2016-08-10 at 13 37 53](https://cloud.githubusercontent.com/assets/617845/17563985/c5171bc6-5eff-11e6-8a93-af574e880b04.png)

**Comment by hatched** [comment]
This issue was with Juju 1, not 2 and a fix will be landing shortly.
