### ISSUE TITLE
Destroying models: use the new destroyModels API call

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#1926]
DestroyModels is implemented and will replace the deprecated DestroyModel (no trailing s) call. The new endpoint allow for destroying multiple models in the controller, without being directly connected to them.
See https://github.com/juju/juju-gui/pull/1924

We need to be able to use the new call for destroying models (except for the controller model) in the profile page. This is high priority as it needs to be included in next GUI release: the deprecated call will be removed in beta16.

**Comment by huwshimi** [comment]
We do not actually use the destroyModel method, so I've removed the old method in #1931.
