### ISSUE TITLE
The juju gui shows the wrong help text.

### ISSUE THREAD

**Issue by mbruzek** [juju/juju-gui#1929]
I was trying to use the juju gui with 2.0-beta15-xenial-amd64 and I encountered an issue where the GUI showed me incorrect help text. I tried to 
![screenshot from 2016-08-16 16-58-51](https://cloud.githubusercontent.com/assets/6385185/17717358/321933e4-63d3-11e6-9dae-9f3e73d565a5.png)

```
$ juju show-controller --show-passwords
error: flag provided but not defined: --show-passwords
$ juju show-controller --show-credentials
error: flag provided but not defined: --show-credentials
$ juju show-controller -h
Usage: juju show-controller [options] [<controller name> ...]

Summary:
Shows detailed information of a controller.

Options:
--format  (= yaml)
    Specify output format (json|yaml)
-o, --output (= "")
    Specify an output file
--show-password  (= false)
    Show password for logged in user
```

According to juju core the flag is singlular `--show-password` and the GUI shows an "s" on the end of the flag. We should fix this before users encounter this problem.

**Comment by hatched** [comment]
Thanks for this issue @mbruzek 

This has been fixed in the latest GUI release but that release cannot yet be put into simplestreams because we have to wait for the Xenial release to be updated.

If you grab the latest GUI release from https://github.com/juju/juju-gui/releases then run `juju upgrade-gui /path/to/release.tar.bz2` you should be off to the races.

**Comment by mbruzek** [comment]
I wanted to point out the `juju show-controllers` command and the `juju gui` command accept similar but different flags "--show-password" and "--show-credentials". I have opened a bug against juju-core here: https://bugs.launchpad.net/juju-core/+bug/1613892 

@hatched Which way was this fixed?

**Comment by hatched** [comment]
The GUI will show you the command to get your credentials below the login screen with `--show-password`
