### ISSUE TITLE
Importing a bundle does not show the correct name for services

### ISSUE THREAD

**Issue by rbclark** [juju/juju-gui#1938]
I am currently using the current juju beta: `2.0-beta15-xenial-amd64`. When attempting to import a bundle (I used openstack-base for my screenshot), the service names do not persist and I am instead left with a bunch of services called xenial, xenial-a, xenial-b, etc, which is not very useful for identifying which service is which. 

<img width="1123" alt="screen shot 2016-08-18 at 12 53 54 pm" src="https://cloud.githubusercontent.com/assets/2308869/17782746/062696ac-6543-11e6-8a59-0b7a6236dad5.png">

The steps to reproduce this are pretty simple, just install the latest juju beta, navigate to the gui and search the charm store for the openstack-base bundle (or any other bundle).

**Comment by hatched** [comment]
This issue is resolved using the latest GUI release which does not yet come bundled with beta15 on xenial. You can upgrade it by:

1. Download the latest release from: https://github.com/juju/juju-gui/releases
2. Run `juju upgrade-gui /path/to/gui.tar.bz2`
3. Run `juju gui --show-credentials`

**Comment by hatched** [comment]
If you're still experiencing this issue with the latest GUI please feel free to re-open this issue.
