### ISSUE TITLE
Constraints on uncommitted machines should be visible (and editable)

### ISSUE THREAD

**Issue by johnsca** [juju/juju-gui#1982]
When an uncommitted machine is pending, any constraints specified are not visible.  It would also be nice if the pending constraints could be modified in place without removing the pending machine entirely and re-assigning the unit to a new machine (having to specify all of the constraints from scratch, rather than making just the changes that are needed).

This is most useful when tweaking a bundle just prior to deployment.

**Comment by hatched** [comment]
Hi @johnsca thanks for bringing this up, this would be a great feature to add! I'll bring it up to the rest of the team and see what we can come up with.

Related #1379

**Comment by kasiag** [comment]
adding @cassiocassio
