### ISSUE TITLE
Show status should be available in Juju  GUI

### ISSUE THREAD

**Issue by buggtb** [juju/juju-gui#1994]
Juju gui should show a web version of the juju status from within the UI to stop people having to switch out to a console.

**Comment by hatched** [comment]
The GUI canvas is a representation of the current status of your model. Can you elaborate a bit on what information you're missing where Juju status is more appropriate? We'll then be able to take that information and work on the UI to surface it better.

**Comment by buggtb** [comment]
Thanks Jeff,

Again, the status shows a very useful instant snapshot to developers of the
state of every charm and machine. It would be great to have a mirror of
that in HTML world that just shows the status  of everything in a quick
scan. Whilst the GUI obviously returns charm state etc via the colouring of
the charms, it would be great to offer that same level of detail in a table
format that console users are used to.

--------------

Director Meteorite.bi - Saiku Analytics Founder
Tel: +44(0)5603641316

(Thanks to the Saiku community we reached our Kickstart
<http://kickstarter.com/projects/2117053714/saiku-reporting-interactive-report-designer/>
goal, but you can always help by sponsoring the project
<http://www.meteorite.bi/products/saiku/sponsorship>)

**Comment by hatched** [comment]
I'll bring this to the team and see what we can come up with. Thanks again

**Comment by frankban** [comment]
We already have some design ideas around the concept of representing the status more explicitly in the GUI

**Comment by kasiag** [comment]
adding @cassiocassio

**Comment by frankban** [comment]
The status pane has been implemented in GUI 2.9.0.

**Comment by buggtb** [comment]
winning!
