### ISSUE TITLE
juju gui should have a console mode to stop users having to shell out.

### ISSUE THREAD

**Issue by buggtb** [juju/juju-gui#1995]
The juju gui should have a small embedded console that provides users used to working with the juju commands on the shell the same subset of commands that they are used to using, thus stopping users having to run GUI & shell at the same time.

**Comment by hatched** [comment]
Thanks for bringing this up @buggtb it's actually been on our roadmap for quite some time and remains there :)

Can you provide a list of features that the GUI is missing that you'd be using this console for?

**Comment by buggtb** [comment]
Hey Jeff

It's not that the GUI is  missing stuff particularly, its the convenience
factor for those of us who use a console for like 95% of their working day
:)

I like the GUI but don't use it much because using the shell is cool, but
you could offer up a bunch of extra stuff to developers who want to
manipulate juju via shell/scripts but means that sysadmins wouldn't have to
give them accounts on a box or deal  with juju clients on developer
machines.

--------------

Director Meteorite.bi - Saiku Analytics Founder
Tel: +44(0)5603641316

(Thanks to the Saiku community we reached our Kickstart
<http://kickstarter.com/projects/2117053714/saiku-reporting-interactive-report-designer/>
goal, but you can always help by sponsoring the project
<http://www.meteorite.bi/products/saiku/sponsorship>)

**Comment by hatched** [comment]
Thanks @buggtb we'll see where we can take this.

**Comment by hatched** [comment]
This is coming in the next release.
