### ISSUE TITLE
Once a multi-series subordinate is deployed, no relations can be made with it

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2021]
Add "filebeat" to the canvas in any mode (sandbox, gijoe, etc) and then deploy it.
Add "elasticsearch" to the canvas and try and relate them. 
You won't be able to even though there is a possible relation.

If you add both to the canvas before deploying you will be able to create this relation

**Comment by huwshimi** [comment]
This may have been due to the subordinate defaulting to xenial when it was deployed, so when the relation to the trusty app was attempted the two apps had different series.

We stopped subordinates/apps being related when they had different series not long ago. We need to confirm that you can't do this from the command line.

**Comment by hatched** [comment]
When a subordinate is added to the canvas we deploy it as normal when the user commits the changes. This happens regardless of the subordinate having a relation to a real application or not. This has not been a problem up until subordinates were given the ability to support multiple series. Now we have to define the series on an application or subordinate before deploying it.

When deploying a subordinate via the CLI it doesn't appear to actually get "deployed" until it is related to another application, at which point the series is locked.

The GUI however will take the default series for the subordinate and deploy it using that series. This is incorrect because after committing it can no longer be related to another application of a differing series even if its in the supported series list.

The GUI needs to be conscious of the subordinates relationship status and if it's not currently related to anything it can add the charm to the model but it cannot deploy, as the Juju API requires that a series be defined.

**Comment by huwshimi** [comment]
It sounds like this needs to be updated to allow connections from any supported series to the deployed multi-series subordinate.

**Comment by huwshimi** [comment]
I guess we should also remove the config option for setting the series on a multi-series subordinate as it doesn't need to be selected.
