### ISSUE TITLE
Retry button does nothing

### ISSUE THREAD

**Issue by nskaggs** [juju/juju-gui#2025]
I am using the latest published gui in streams, 2.1.10, and clicking the retry button for a failed hook performs no action that I can see within the gui, nor on the cli. If I select resolve within the gui, it does retry the hook as expected.

Running juju resolved --retry on the cli does perform my expected action.

**Comment by hatched** [comment]
@nskaggs Thanks for the report.

The 2.1.10 release is quite old now. Does the same issue happen with the latest GUI release? 
```
$ wget https://github.com/juju/juju-gui/releases/download/2.1.12/jujugui-2.1.12.tar.bz2
$ juju upgrade-gui path/to/jujugui-2.1.12.tar.bz2
```

**Comment by nskaggs** [comment]
Yes, same issue occurs. Depending on what is happening when you select 'retry', perhaps the issue is within juju itself. Clicking resolve does perform the action I expect. I'm not sure what the difference is intended to be between the two options.

**Comment by hatched** [comment]
Thanks @nskaggs we've got a release coming up so we'll see about getting this resolved for 2.1.13

**Comment by anastasiamac** [comment]
"resolved" behavior changed on rc1. Please see Release Notes for new behavior \o/

**Comment by frankban** [comment]
AFAICT the change is only CLI wise, and the GUI seems to be sending the right calls to the Juju API.
So for instance, I deployed the failtester charm, forcing it to go on an error state when running the config-changed hook. I then opened the current GUI (develop version) and used the JavaScript console to check the WebSocket frames (network -> WS tab -> select the model api connection -> inspect the frames). Here are the results:
When I press the "Resolve" button:
```
{
  params: {unit-name: "failtester/0", retry: false},
  request: "Resolved",
  request-id: 14,
  type: "Client",
  version: 1,
}
```
When I press the "Retry" button:
```
{
  params: {unit-name: "failtester/0", retry: true},
  request: "Resolved",
  request-id: 20,
  type: "Client",
  version: 1,
}
```
In both cases the response from Juju does not include errors.
@nskaggs could you please double check the messages sent to Juju?

**Comment by nskaggs** [comment]
@frankban that looks correct. Resolve should send without retrying and I believe it should remove the error state. This doesn't seem to be happening. Do you agree @anastasiamac ?

For the 'retry' button, it should send a retry. Juju on the cli does respond accordingly, so I wonder why the button doesn't appear to do anything in the gui. The API calls look fine AFAIK.

Could the feedback on both of these buttons be a bit better? Clicking them merely unchecks the box. That's confusing either way.

**Comment by nskaggs** [comment]
I should add I will retry with rc1 as the behaviors have changed. Perhaps the buttons will work closer to as expected now.

**Comment by hatched** [comment]
As this isn't technically a bug but some UI changes, I've moved it off of our next release to be tackled once we have a chance to look at a better UX.
