### ISSUE TITLE
Logging into juju gui isn't clear

### ISSUE THREAD

**Issue by anastasiamac** [juju/juju-gui#2030]
Related to https://bugs.launchpad.net/juju/+bug/1625687, is it possible/desirable for GUI to accept arguments from 'juju gui' command to facilitate login? This may save user from typing 'juju show-controller --show-password' and digging up needed info from the bottom of the list.

I am not clear on security implication at this stage and will take your advice on the matter.

**Comment by hatched** [comment]
Just repeating what I had typed on the linked bug:

```
If you start the GUI using `juju gui --show-credentials`

It will show your credentials in the console which can be used to log into the GUI.

Other options can be found in the help output `juju help gui`

We have plans to include a token login system.
```
