### ISSUE TITLE
Revisions not working on charm details

### ISSUE THREAD

**Issue by anthonydillon** [juju/juju-gui#2033]
Visit: https://demo.jujucharms.com/?store=xenial/landscape-client

See that the revisions section is visible with 0 revisions. In the store there seems to be 10 revisions: https://jujucharms.com/landscape-client/#revisions.

**Comment by urosj** [comment]
This is really old GUI, needs to be updated. Plans to do that in the
following days.

**Comment by hatched** [comment]
I'm going to close this as we already have the plans in place for the upgrade.
