### ISSUE TITLE
When switching models sometimes username disappears from breadcrumb

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2047]
This only appears to happen on a slow connection. But when switching between models the username component of the breadcrumb `admin@local` will sometimes disappear which makes it impossible to get to the profile page. Usually it'll come back in a short moment but sometimes it doesn't appear to. There is likely some logic to only show this if we're connected to a model or something. This will need to be modified.

**Comment by huwshimi** [comment]
The username is also lost if you go to the uncommitted state

**Comment by huwshimi** [comment]
This has been fixed.
