### ISSUE TITLE
cursor jump to the beginning of the line on every type with Firefox

### ISSUE THREAD

**Issue by nobuto-m** [juju/juju-gui#2053]
Reproducible with:
Ubuntu 16.04 LTS + Firefox 49.0+build4-0ubuntu0.16.04.1 on https://demo.jujucharms.com/

The cursor will jump to the beginning of the line on every type when editing configuration options of charm. It's not reproducible with Chromium.

![jumpy-cursor](https://cloud.githubusercontent.com/assets/4356209/18960626/5792251e-86a5-11e6-9680-ffcf38e8a880.gif)

**Comment by hatched** [comment]
Thanks for the bug report @nobuto-m This has been fixed in the next GUI release (going out today) and we'll be updating demo.jujucharms.com early next week.
