### ISSUE TITLE
Deleting an application keeps adding to change log 

### ISSUE THREAD

**Issue by anthonydillon** [juju/juju-gui#2065]
To replicate: 

- Deploy a few applications in a real environment
- Click on a application in the inspector
- Click the Destroy button
- The application goes to uncommitted and adds two items to the change log
- Then do the same again to the same application and it adds another two items to the change log

Expected:
- Once an item is earmarked to be destroyed the destroy button should be disabled or hidden.

**Comment by kadams54** [comment]
Part of fixing #1503 will also fux this issue.

**Comment by hatched** [comment]
I"m closing this as resolved as with #1503 it's no longer possible to delete an application multiple times the user cannot get into this state.
