### ISSUE TITLE
Replace bundle icon for new bundle icon (group of icons)

### ISSUE THREAD

**Issue by faooful** [juju/juju-gui#2073]
replace this icon:
![image](https://cloud.githubusercontent.com/assets/9321516/19068842/28694c02-8a1c-11e6-8412-b951fcf21858.png)

with the new one that shows a representation of the charms included in the bundle

![curated-search-results-4cards](https://cloud.githubusercontent.com/assets/9105999/19069196/bfac603a-8a1d-11e6-9b2b-44284608caad.png)

**Comment by huwshimi** [comment]
We no longer display an icon on the bundle details page, so is this no longer relevant?

**Comment by huwshimi** [comment]
Thanks @spencerbygraves I'll close this issue then, and we can make sure to use that style in the future.
