### ISSUE TITLE
Discuss the model switcher empty state

### ISSUE THREAD

**Issue by faooful** [juju/juju-gui#2074]
@hatched @urosj Do you think that the current empty state is correct? It currently shows a button to the profile, or should this be a 'new' button which creates an empty canvas?

**Comment by anthonydillon** [comment]
You are already in an empty canvas. I don't think we need a like to the
same place.

**Comment by hatched** [comment]
I think that the actions are correct however maybe we could add something like a 'no models' text value.

**Comment by elvirafigueras** [comment]
+1 @hatched
