### ISSUE TITLE
Model is in it's open state by default when going to the profile

### ISSUE THREAD

**Issue by faooful** [juju/juju-gui#2076]
It should be closed by default.

![image](https://cloud.githubusercontent.com/assets/2169216/19070687/6d7d367a-8a24-11e6-9da3-2cbcfc1e3ded.png)

**Comment by hatched** [comment]
We have the 'first' model open by default on purpose so that it shows the Manage button as an indicator to the user on how to get back to the canvas. If you have an updated UI for the model listings which solves this problem a different way we can implement that instead.
