### ISSUE TITLE
Checkboxes missing from the bottom of of the deployment flow

### ISSUE THREAD

**Issue by faooful** [juju/juju-gui#2078]
![image](https://cloud.githubusercontent.com/assets/2169216/19070427/18235f0c-8a23-11e6-81ce-41b2921d77d7.png)

**Comment by hatched** [comment]
They are missing because we don't have anything to hook them up to.

**Comment by cassiocassio** [comment]
Terms and updates butons included in the newer DF designs built and user tested summer 2017
