### ISSUE TITLE
Number of machines is different from Charm details to the controller (canvas)

### ISSUE THREAD

**Issue by faooful** [juju/juju-gui#2079]
Charm details:

<img width="521" alt="screen shot 2016-10-04 at 11 06 46" src="https://cloud.githubusercontent.com/assets/22299251/19070362/c835f25c-8a22-11e6-9ebe-4245f79bb457.png">

Controller - canvas:

<img width="321" alt="screen shot 2016-10-04 at 11 06 54" src="https://cloud.githubusercontent.com/assets/22299251/19070396/f6071940-8a22-11e6-93ed-25b234be6654.png">

This happens with all bundles.

**Comment by hatched** [comment]
I believe this is because we treat containers as machines in the charm details but not in the machine header. 

I know that we don't include the containers in the machines header on purpose. @faooful do we also not want to show containers count in the charm details?

**Comment by anthonydillon** [comment]
We have removed the stats from the bundle details in the storefront sometime ago. Maybe we could do that?
![beats core juju](https://cloud.githubusercontent.com/assets/1413534/19106394/019cb4a6-8adf-11e6-88e4-446416149569.png)

**Comment by elvirafigueras** [comment]
If we treat them one way in one place we should do the same everywhere else. 

@anthonydillon That would help, but I wonder if someone's choice might be guided by that information. It might be best to do as @hatched suggested and not count containers in charm details?

**Comment by anthonydillon** [comment]
I dont mind but we should have the designs exactly the same or not at all.

**Comment by elvirafigueras** [comment]
Then let's keep the info and not count containers in charm details.

**Comment by frankban** [comment]
This seems already done to me.
