### ISSUE TITLE
Provide link to midpoint from empty machine view

### ISSUE THREAD

**Issue by aobregon** [juju/juju-gui#2080]
![image](https://cloud.githubusercontent.com/assets/9321516/19071107/586ecf62-8a26-11e6-8d31-4ec341791c83.png)

We need to enable users to jump to midpoint from an empty machine view (e.g. link the text 'Add an application to get started')

Spencer will provide visual styling and attached it below.

**Comment by hatched** [comment]
There is no midpoint any longer, clicking the search input the store page opens. We also have the 'Add applications to get started' in the left column. That could be turned into a link to open the store page.

**Comment by anthonydillon** [comment]
I like the idea of turning that into a link to the store. I think that
would solve this issue.

**Comment by spencerbygraves** [comment]
Update using the blue link style:

![image](https://cloud.githubusercontent.com/assets/9105999/21150843/5d08b0ce-c158-11e6-8e13-437b15306dfe.png)

**Comment by huwshimi** [comment]
This has been done.
