### ISSUE TITLE
The behaviour of the float label

### ISSUE THREAD

**Issue by faooful** [juju/juju-gui#2081]
If the field is empty, the label should be 16px and then shrink to 12px when clicking into the field and adding information. 

![float lable exploration](https://cloud.githubusercontent.com/assets/2169216/19070029/506603f8-8a21-11e6-8446-0cd0db37a1ad.gif)

**Comment by spencerbygraves** [comment]
The colour change for this should be #666666 to #333333 on focus. The label changes from 16px to 12px, the input is then 16px.
