### ISSUE TITLE
Warn the user when exporting an empty canvas

### ISSUE THREAD

**Issue by ClaraLavina** [juju/juju-gui#2082]
A notification comes up but the model is not being imported to the canvas.

<img width="433" alt="screen shot 2016-10-04 at 11 31 43" src="https://cloud.githubusercontent.com/assets/22299251/19071086/3ac4e53c-8a26-11e6-9952-64fc40e54e2b.png">

**Comment by anthonydillon** [comment]
Could you provide the model you are trying to import? Either the name it
the file itself.

**Comment by ClaraLavina** [comment]
The file has the default name Juju gives to the model when downloading it. In this case is 'untitled-model-16-10-04.yaml'.

**Comment by hatched** [comment]
Can you attach the bundle yaml file to this issue so that we can test it.
We'll also need to know the Juju and GUI version being used.

**Comment by ClaraLavina** [comment]
[untitled-model-2016-10-04.yaml.zip](https://github.com/juju/juju-gui/files/508900/untitled-model-2016-10-04.yaml.zip)

**Comment by anthonydillon** [comment]
That is an empty bundle. There has been nothing committed there for when
uploading it leaves the canvas empty.

**Comment by ClaraLavina** [comment]
Does this mean exporting is not working?

**Comment by anthonydillon** [comment]
No its working as expected. It only exports committed changes. Anything in
blue is uncommitted (unsaved). If you commit your changes then export, the
`.yaml` file should contain your changes to be imported.

**Comment by ClaraLavina** [comment]
Ok, thank you for the clarification. Maybe it could be good to warn the user when trying to export the model without committing changes for the first time, and cancel any download when the canvas is still empty/uncommitted. Does this make sense? :)

**Comment by anthonydillon** [comment]
Yes that would make sense. A notification when exporting with uncommitted
changes.

**Comment by elvirafigueras** [comment]
We'll make a visual of this and add it here

**Comment by anthonydillon** [comment]
Is it possible to export an empty canvas? I thought export was hidden if
there is was nothing added. We should hide the export until something is
committed.

**Comment by huwshimi** [comment]
@anthonydillon the export is hidden when there are no changes, but if you export you only get the committed changes.

**Comment by anthonydillon** [comment]
That's why I think it might be better to change the logic so the button is
only showed when there is committed changes.

**Comment by elvirafigueras** [comment]
I think the two options should always be there so long as they have something in the canvas. I see what you mean @anthonydillon  but don't think we should block the user from exporting what they have on the canvas only because they haven't committed it yet. imo a warning would be better.

**Comment by hatched** [comment]
There is a technical limitation blocking us from exporting uncommitted changes. This wouldn't likely be implemented for quite some time. I had actually thought that this button was removed as @huwshimi mentioned. 

This may have been possible because of the uncommitted state issue that's now been fixed in develop. @ClaraLavina @elvirafigueras can you try and replicate the original issue plz.

**Comment by ClaraLavina** [comment]
I replicated the original issue with Juju demo.

Empty canvas, no EXPORT button.
<img width="1271" alt="screen shot 2016-10-18 at 10 38 26" src="https://cloud.githubusercontent.com/assets/22299251/19472425/25f9bf66-951f-11e6-807b-edb2178277d4.png">


I add a charm from the store, EXPORT button appears. Changes have not been commited.
<img width="1261" alt="screen shot 2016-10-18 at 10 38 42" src="https://cloud.githubusercontent.com/assets/22299251/19472426/25fe40fe-951f-11e6-8c16-1ce74deafc81.png">


Export model. Changes have not been committed. Empty file is exported.
[sandbox-2016-10-18 (1).yaml.zip](https://github.com/juju/juju-gui/files/535849/sandbox-2016-10-18.1.yaml.zip)


Charm is destroyed from canvas. EXPORT button is still displayed.
<img width="1269" alt="screen shot 2016-10-18 at 10 39 06" src="https://cloud.githubusercontent.com/assets/22299251/19472427/25fffd5e-951f-11e6-8af8-f4cd94edc005.png">


Export empty model. Empty file is exported.
[sandbox-2016-10-18 (1).yaml 2.zip](https://github.com/juju/juju-gui/files/535857/sandbox-2016-10-18.1.yaml.2.zip)

**Comment by hatched** [comment]
Thanks @ClaraLavina I've marked this as a bug

**Comment by spencerbygraves** [comment]
When trying to export uncommitted changes:

![image](https://cloud.githubusercontent.com/assets/9105999/20754787/7c7cbfe4-b704-11e6-8ada-c454c854e4df.png)

**Comment by huwshimi** [comment]
We now include uncommitted changes in the export.
