### ISSUE TITLE
Update the error state to form fields

### ISSUE THREAD

**Issue by faooful** [juju/juju-gui#2084]
Red outline with red text below explaining error. Hex for the red: #DF382C

![error field](https://cloud.githubusercontent.com/assets/2169216/20483852/32d242c0-afec-11e6-8553-f06defac6eae.png)

**Comment by elvirafigueras** [comment]
This is what we get on the deployment flow at the moment

![screen shot 2016-11-22 at 10 51 46](https://cloud.githubusercontent.com/assets/12827541/20521143/b6971e54-b0a1-11e6-9581-efb6cb5f64ee.png)
