### ISSUE TITLE
It is not possible to enter a new name for the model on the canvas.

### ISSUE THREAD

**Issue by faooful** [juju/juju-gui#2085]
'untitled model' does not over-write when you enter a new model name.

![image](https://cloud.githubusercontent.com/assets/9321516/19069713/e94fa382-8a1f-11e6-8a4f-b715b43cb9d0.png)

**Comment by faooful** [comment]
We have designs for naming the model on the canvas pre deployment:

Editable field

![service view - pre deployment naming 01](https://cloud.githubusercontent.com/assets/9105999/19070230/26cfc24e-8a22-11e6-8f1a-f5cb2fe1ada0.png)

Focused

![service view - pre deployment naming 02](https://cloud.githubusercontent.com/assets/9105999/19070237/31e487d2-8a22-11e6-85b1-45b4b8bbbf7d.png)

Post deployment

![service view - post deployment 01](https://cloud.githubusercontent.com/assets/9105999/19070255/416bc904-8a22-11e6-842f-8f6785240a18.png)

Selected

![service view - post deployment 02](https://cloud.githubusercontent.com/assets/9105999/19070266/53619ca6-8a22-11e6-9892-9c0b16bd29a8.png)

**Comment by faooful** [comment]
Related: If i enter the model name in the deployment screen, but return to canvas before clicking deploy, it does not save my model name or update the field in the canvas.

**Comment by faooful** [comment]
After deployment, the model name does not match the switcher:

![image](https://cloud.githubusercontent.com/assets/9105999/19070736/aae0dd6e-8a24-11e6-8f35-7d8e23a48bce.png)

**Comment by spencerbygraves** [comment]
Can we also add the UI label for the design updates please.

**Comment by hatched** [comment]
@faooful That is because you're in an unconnected model not the 'helloworld' model.

**Comment by spencerbygraves** [comment]
@hatched so it's not possible to rename your model on the canvas, before hitting deploy?

Also, the last image above was grabbed after deployment when helloworld was selected.

**Comment by elvirafigueras** [comment]
So there's three different issues here
1. 'untitled model' does not over-write when you enter a new model name.
2. If i enter the model name in the deployment screen but return to canvas before clicking deploy, it does not save my model name or update the field in the canvas
3. After deployment, the model name does not match the switcher (which happens because you're in an unconnected model not 'helloworld, right?)

@hatched Do you know what the progress is on the other two?

**Comment by hatched** [comment]
None of these tasks have been started. We'll update the issue when we do. The third mentioned issue there we can't reproduce reliably so if you have steps to reproduce that it would be appreciated.
