### ISSUE TITLE
Canvas is displayed in the background of the user profile

### ISSUE THREAD

**Issue by faooful** [juju/juju-gui#2086]
This happens when accessing to the Charm Store from Users Profile, and adding a Charm/Bundle to the canvas.

<img width="1239" alt="screen shot 2016-10-04 at 10 39 46" src="https://cloud.githubusercontent.com/assets/22299251/19069514/34cd0e9a-8a1f-11e6-90e9-823f669107b6.png">

**Comment by ClaraLavina** [comment]
This creates another problem to the user: How to go to the canvas when adding a charm/bundle from the user's profile? (adding to canvas from the search bar)

**Comment by anthonydillon** [comment]
When deploying from the store the GUI should jump back to the canvas.

**Comment by hatched** [comment]
@faooful what do you think of blocking off that top section sot hat you cannot search the store unless you're on the canvas?

**Comment by anthonydillon** [comment]
I think we should just switch back to the canvas. The user would have already have got to there profile so will know how to get back.

**Comment by elvirafigueras** [comment]
+1 w/ @anthonydillon

**Comment by hatched** [comment]
We can't simply jump back to the canvas. The idea which the profile view is that when you're in the profile view you're not connected to anything, it's just a blank page. So does this mean interacting with the search would have to automatically drop the user into an unconnected state? This profile page logic needs some considerable thought before we go implementing any of these features.

**Comment by anthonydillon** [comment]
Got you. Yeah that makes sense. Yeah think we need some thinking about the
profile page.

**Comment by ClaraLavina** [comment]
Update from Uros: 
This will be as it is. We've got no time to reimplement that. Maybe a fix in 17.04 cycle, but certainly not before.

**Comment by hatched** [comment]
This is no longer an issue with the new redesign.
