### ISSUE TITLE
If I open my profile I cannot go back to the canvas to my model unless I create new model (in which case I loose everything I had on the canvas)

### ISSUE THREAD

**Issue by faooful** [juju/juju-gui#2087]

**Comment by anthonydillon** [comment]
When going to profile with uncommitted changes. You are warned you will
lose the changes. If you go to profile without changes then you can switch
to a new one without losing work.

**Comment by hatched** [comment]
As @anthonydillon said, this is intentional.

This does bring up an interesting point, if you want to view your charms without going through the search field then you have no way of doing that with uncommitted changes.

**Comment by ClaraLavina** [comment]
Can I see my charms from the Charm Store?

This issue links to the one that refers to adding charms from the user profile (https://github.com/juju/juju-gui/issues/2086)

**Comment by elvirafigueras** [comment]
We should allow the option to 
1. open the profile despite of having uncommitted changes
2. go back from the profile to the canvas easily
The two happening without losing anything on the canvas

**Comment by hatched** [comment]
Lets talk about the profile view and what it should be. We need a plan before we move forward on these changes.

**Comment by frankban** [comment]
We are currently intending the profile page as something disconnected from any model (even if technically it isn't). If we want to change this, or if it's demonstrated that the current behavior is confusing for users, let's open a discussion bug.
