### ISSUE TITLE
When you delete a single service, [deploy changes (1)] still shows but is inactive

### ISSUE THREAD

**Issue by faooful** [juju/juju-gui#2088]
When you delete a single service, the [deploy changes (1)] button still shows but does not progress to the deploy screen - I can't click it, but it looks active. It is confusing to show 1 change on the button when the canvas is empty.

![image](https://cloud.githubusercontent.com/assets/9321516/19069172/a9689078-8a1d-11e6-9ecd-ee55cbd51861.png)

If all services on a canvas are destroyed, we should return to the empty canvas state, with the faded button and 0 changes. @urosj would you agree?

**Comment by faooful** [comment]
Also the deploy changes button is reflecting a different amount of changes then what is happening. Adding one charm for example is showing 3 changes, and then clicking the button increases this to 4. 

![image](https://cloud.githubusercontent.com/assets/2169216/19069416/ce47a7b6-8a1e-11e6-97b3-e6f0f78c8cec.png)

**Comment by hatched** [comment]
There are definitely issues here with changes not being cleared and properly updated. However the counts are correct. When you add an application to the canvas the GUI must 1) Add the charm 2) Deploy the application 3) Add a unit.

**Comment by elvirafigueras** [comment]
@hatched Exactly. The counts are correct but this should not be shown to the user as it just leads to confusion. The number in that button should only reflect the actions that a user has actively taken.

**Comment by spencerbygraves** [comment]
@elvirafigueras I'm not sure I agree, previously when you clicked deploy you could see what those 3 changes were. Isn't it useful to know that? We discussed yesterday that perhaps the changelog is still visible somehow.

**Comment by ClaraLavina** [comment]
Could these 3 changes be nested in a single one action? 

User adds 1 charm to the canvas = 1 change (expand to see this involved A) Add the charm B) Deploy the application & C) Add a unit).

**Comment by hatched** [comment]
Sorry @elvirafigueras @ClaraLavina that isn't really possible. I'll have to stay the way it is (Of course with the bug fixed)

**Comment by hatched** [comment]
I believe this is the same issue as with #2045

**Comment by elvirafigueras** [comment]
@spencerbygraves it would work with a change log but we don't have that anymore... Looks like there is a case to bring it back.
