### ISSUE TITLE
Tool tip on the profile page hidden behind body of the page

### ISSUE THREAD

**Issue by faooful** [juju/juju-gui#2089]
![image](https://cloud.githubusercontent.com/assets/2169216/19069171/a6a96d30-8a1d-11e6-9072-f1dd15cdde2f.png)

**Comment by hatched** [comment]
I believe if we block that header then this will be a non-issue

**Comment by anthonydillon** [comment]
The header needs to jump above the mask in the z-index list.

**Comment by elvirafigueras** [comment]
Any progress on this? @hatched

**Comment by hatched** [comment]
We update the issues when we start working on them.
