### ISSUE TITLE
Profile empty state has wrong cta

### ISSUE THREAD

**Issue by faooful** [juju/juju-gui#2090]
![image](https://cloud.githubusercontent.com/assets/2169216/19069092/4a64e2de-8a1d-11e6-97fc-0b596ed92cdc.png)

Should be like this:
![image](https://cloud.githubusercontent.com/assets/2169216/19069100/4fb79cc2-8a1d-11e6-8165-5b4eda2cc9d7.png)

**Comment by anthonydillon** [comment]
Where would this link to?

**Comment by hatched** [comment]
And where are the assets? :)

**Comment by faooful** [comment]
@anthonydillon it would link to the canvas.
@hatched the image that is currently being used is fine, this was more in reference to the lock up.

**Comment by kadams54** [comment]
So it seems like the "Create new" button needs to come down below the image and be green. Is that accurate?

**Comment by elvirafigueras** [comment]
@kadams54 "Start building" needs to be placed under the onboarding text, which itself needs to be bigger too.

**Comment by spencerbygraves** [comment]
The text sizes should be 23/16px.
