### ISSUE TITLE
The current flow for destroying a service after having deployed it needs to be redesigned

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#2093]
This would not apply 

![screen shot 2016-10-04 at 12 05 32](https://cloud.githubusercontent.com/assets/12827541/19072118/6068c0e2-8a2b-11e6-8148-34baa789304c.png)

**Comment by hatched** [comment]
Can you elaborate on what should apply?

**Comment by elvirafigueras** [comment]
@hatched We've added this work to our roadmap and will provide designs as soon as we have them.

**Comment by hatched** [comment]
There are no actionable items here, closing.
