### ISSUE TITLE
 OpenStack base 45 not being deployed with Juju GUI 

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#2094]
Copied from https://bugs.launchpad.net/juju-gui/+bug/1630123

Juju beta 18
MAAS Version 2.0.0+bzr5189-0ubuntu1

After clicking on "Deploy", GUI locks in "Choose cloud to deploy to" screen (attached screenshot).

Deploys correctly using command line:

juju deploy cs:bundle/openstack-base-45

**Comment by urosj** [comment]
Looks like handling of maas provider is broken/missing in GUI.

**Comment by hatched** [comment]
I'll get in touch with the original reporter - It's very possible that the version of the GUI used does not support Beta 18 due to API changes.

**Comment by hatched** [comment]
Closing this as we haven't heard that this issue persists with the 2.0 GA. Feel free to reopen if you can still reproduce.
