### ISSUE TITLE
cannot access charms in juju gui from any namespace other then my user

### ISSUE THREAD

**Issue by jamesbeedy** [juju/juju-gui#2098]
I have created a team on launchpad for my company, when logged into the juju-gui using my ubuntu sso account, I can see charms in my personal namespace, but cannot see any charms listed for teams I am member of, outside of my personal namespace.

**Comment by frankban** [comment]
You can now go directly to the /u/{user-or-team} page in the GUI, and that profile page will show all charms and bundles for that user or team. We are designing a better search experience, hope this workaround is good enough for the time being.
