### ISSUE TITLE
Re-enable destroy-model in profile view

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2106]
Now that the destroy-model call has been moved to the controller we can re-add it to the profile view.

We still have the `destroyModels`[0] call implemented on the controller api so this should be a simple case of just hooking it up to a new UI element. This destroy UI element should only be shown if the ACL[1] permits it

[0] https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/store/env/controller-api.js#L668
[1] https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/store/env/acl.js#L91

**Comment by frankban** [comment]
Thanks Jeff, the ACL check should be done, but maybe later, as it's not straightforward: as the docstring says, it "Report[s] whether the user can destroy the current model.". So there is no way to knwo if the user can destroy an arbitrary model they are not currently connected to. So, as a first step, let's assume the user can always destroy models and be ready to gracefully handle "forbidden" permission errors.
