### ISSUE TITLE
Missing 'change cloud' button when deploying a second time

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#2111]
What it is now:
![screen shot 2016-10-07 at 13 10 43](https://cloud.githubusercontent.com/assets/12827541/19189374/9ce6cd0a-8c8f-11e6-8049-d51d2695d2c0.png)

We're missing the button on the top right
![screen shot 2016-10-07 at 13 13 12](https://cloud.githubusercontent.com/assets/12827541/19189427/e18d763e-8c8f-11e6-81e4-cf0f3723a6a2.png)

**Comment by urosj** [comment]
The model is already created in a cloud, you can't change it.
