### ISSUE TITLE
The gui is not proxy-ready if the websockets require proxying or floating IP.

### ISSUE THREAD

**Issue by jrwren** [juju/juju-gui#2116]
Scenario: HJC (likely gisf too)
 * juju gui on a private openstack with IP 10.10.0.124 
 * juju controller with IP 10.10.0.125
 * HJC will proxy connections to 10.10.0.125 via the /juju/controller-api rewrite rule

This works if the private openstack network is used, but as soon as a floating IP is used, nothing works.

e.g.:

 * floating IP 10.245.162.152 bound to ip 10.10.0.124

Now a browser request to https://10.245.162.152 returns a config.js with wss://10.10.0.124/... which is probably not accessible.

Similarly, if a proxy is used (instead of floating IP) to expose teh 10.10.0.124 gui, the proxy address may be 10.0.5.109 and gui may respond at https://10.0.5.109/horizon/juju/, but the config.js still has wss://10.10.0.124/... 

Expected:
The wss://$host/ The $host here should match the Host: header in the request, even if it is an IP.

https://10.0.5.109/horizon/juju/gui/config.js should return template socket addresses with wss://10.0.5.109/... not wss://10.10.0.124/...

**Comment by jrwren** [comment]
update:

If I cowboy hardcode the IP Address in production.ini to 10.0.5.109, I get the connection attempt being made, and a response:


    WebSocket connection to 'wss://10.0.5.109/juju/controller-api/10.0.5.109/undefined' failed: Error during WebSocket handshake: Unexpected response code: 404

**Comment by bac** [comment]
I think the address in production.ini is actually IP:PORT.  That's why you see undefined.

**Comment by jrwren** [comment]
thanks @bac, indeed, that is why I see undefined. (I always forget this.)

**Comment by bac** [comment]
@jrwren I'm making a change now to HJC to rename controller-ip-address to controller-location so the port requirement won't be as obscured.

**Comment by bac** [comment]
https://github.com/CanonicalLtd/horizon-juju-charm/pull/49

**Comment by hatched** [comment]
After a discussion offline this is indeed not a bug in the GUI but improper configuration values. We could probably update the docs around the configuration values to make it easier to understand what is necessary and why.
