### ISSUE TITLE
in GISF switching models does not show correct model name in Safari

### ISSUE THREAD

**Issue by bac** [juju/juju-gui#2146]
When switch from one model to the other, it is common to see 'untitled-model' temporarily before the selected model name shows up. That's what happens in Chrome. In Safari the canvas populates but 'untitled-model' remains.

![screen shot 2016-10-19 at 17 18 22](https://cloud.githubusercontent.com/assets/617845/19538008/2f05648c-9620-11e6-9928-fea9c14d9965.png)

**Comment by hatched** [comment]
Thanks for the report @bac This is a known issue and we're actively working on a resolution.
