### ISSUE TITLE
When selecting an application, don't move the canvas if the app circle is visible already

### ISSUE THREAD

**Issue by bac** [juju/juju-gui#2147]
It is nice to be able to click through the apps, but moving the canvas to center them makes it feel jumpy. Let's not move the canvas if the selected app is already fully visible, and if it's partially visible let's just move it enough to bring it onto the canvas. If it's way off, then let's pan the canvas just enough to bring it fully into view.  

Original: https://bugs.launchpad.net/juju-gui/+bug/1634007

**Comment by spencerbygraves** [comment]
Thanks @bac we were talking about this just last week. I think your solution sounds good.

**Comment by huwshimi** [comment]
The first part (not moving the canvas if the app is on screen) has been done in #2782.
