### ISSUE TITLE
Juju logo is cropped and missing a few pixels on the right hand edge

### ISSUE THREAD

**Issue by sparkiegeek** [juju/juju-gui#2163]
Juju GUI 2.2.1, Firefox 49.0, Juju core 2.0.0

The juju logo is cropped by a few pixels:

![screen shot 2016-10-27 at 12 43 14](https://cloud.githubusercontent.com/assets/246192/19765924/f70e5e8e-9c42-11e6-82cc-f576ee7f1a63.png)

If I hack the HTML to set `viewBox="0 0 90 30"` (from 75) then it looks correct.

**Comment by hatched** [comment]
Fixed by #2168
