### ISSUE TITLE
Not clear how to trigger juju actions in Juju GUI

### ISSUE THREAD

**Issue by nobuto-m** [juju/juju-gui#2185]
I wanted to use Juju actions[1] on Juju GUI, but at least I could not find where to see available Juju actions and how to trigger those. I'm not sure if Juju GUI already supports Juju actions or not though.

[1] https://jujucharms.com/docs/stable/actions

**Comment by hatched** [comment]
Hi @nobuto-m, the GUI doesn't yet support actions. It is on our roadmap however but we do not have a date as to when to expect it.

**Comment by nobuto-m** [comment]
Ok, fair enough. But the doc needs to be updated as it says "Actions are scripts that can be triggered on a unit via the command line or the Juju GUI.". I will open a bug on juju docs then.

**Comment by hatched** [comment]
Thanks! I'll leave this issue open and report back once we have implemented actions.
