### ISSUE TITLE
Error when deploying with removed applications

### ISSUE THREAD

**Issue by anthonydillon** [juju/juju-gui#2200]
To replicate:
- I added an application (easyrsa) to the canvas and opened the deployment flow.
- In the deployment flow I opened the summary
- Then went back to the canvas
- Deleted the application via the inspector
- The deploy count on the deploy button says (2)
- Clicked on the deploy button
- Nothing happens and I get the following errors in the console.

![console-errors](https://cloud.githubusercontent.com/assets/1413534/20355311/945090d6-ac29-11e6-91de-e70db2a1c383.png)

**Comment by huwshimi** [comment]
I couldn't reproduce this, I suspect because we now clean up removed charms. If you can reproduce this again please reopen this issue.
