### ISSUE TITLE
I can't edit model name on the dropdown on the canvas (can't type in the input field) and it shows the tool tip when I click on it even if I just want to edit the name

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#2207]

**Comment by elvirafigueras** [comment]
![screen shot 2016-11-21 at 11 41 09](https://cloud.githubusercontent.com/assets/12827541/20481513/6fe3fcd8-afdf-11e6-8819-7a44bd140e00.png)

**Comment by urosj** [comment]
Model name is defined in the deployment flow, not model switcher.

**Comment by spencerbygraves** [comment]
We worked on designs for naming a model on the canvas before deployment earlier in the year. Hopefully we can include this in the future.

https://github.com/CanonicalLtd/juju-design/issues/7

**Comment by hatched** [comment]
Duplicate: #2085
