### ISSUE TITLE
When clicking your name in the top left hand corner, the modal that pops up has red button

### ISSUE THREAD

**Issue by ClaraLavina** [juju/juju-gui#2208]
This button should be neutral

<img width="320" alt="screen shot 2016-11-21 at 11 57 00" src="https://cloud.githubusercontent.com/assets/22299251/20481932/a38c3332-afe1-11e6-807f-2f42db867f76.png">

**Comment by ClaraLavina** [comment]
UROS: that red button is signalling loss of data. should be red, not neutral. loss of data is *kinda* important

**Comment by hatched** [comment]
@ClaraLavina Your statements conflict. Hitting `Continue` here will cause the user to lose their uncommitted data. So why shouldn't it be red?

**Comment by faooful** [comment]
@hatched So to me this should be neutral as you losing data is a by product of you going to your profile. If this button is read it feels to me that going to the profile is the negative action.

**Comment by hatched** [comment]
If you don't have uncommitted changes then this alert doesn't show up so it is a warning that you're going to lose your data. Note that the profile button itself isn't red.

**Comment by faooful** [comment]
I was just speaking to Spencer and we are just thinking up some messaging that makes more sense, which might be the issue

However, Spencer made a good point that it is similar to this kind of error. 

![image](https://cloud.githubusercontent.com/assets/2169216/20488104/beca18c8-affd-11e6-93af-8f47cd51ea42.png)

Don't want to speak directly for him, but having said that, I think he prefers it being red.

**Comment by hatched** [comment]
Thanks @faooful we can open up a new issue with any messaging updates.

**Comment by spencerbygraves** [comment]
I think the language is a bit confusing, as continue doesn't fit with a destructive action. We could say "You will lose these changes if you leave". And have Leave in the red button.
