### ISSUE TITLE
All modal windows should have transparency behind them to hide the UI behind

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#2209]

**Comment by faooful** [comment]
The UI is old, but it shows what it should look like. It's #f7f7f7 with 70% opacity.

<img width="717" alt="screen shot 2016-11-21 at 11 46 12" src="https://cloud.githubusercontent.com/assets/2169216/20481654/1f97a328-afe0-11e6-9638-e58709edc929.png">
