### ISSUE TITLE
Profile page - Empty state for when you have some things but not others (eg. a team, but no models) is incorrect

### ISSUE THREAD

**Issue by faooful** [juju/juju-gui#2213]
![image](https://cloud.githubusercontent.com/assets/2169216/20489279/ec79b950-b001-11e6-8c77-c10b6cf8c1c9.png)

**Comment by ClaraLavina** [comment]
This is what I see the first time I access

![screen shot 2016-11-21 at 10 55 31](https://cloud.githubusercontent.com/assets/22299251/20518387/f285f490-b096-11e6-9914-bbd4a95fa606.png)

This is what I can see when I go to my profile later on
![screen shot 2016-11-21 at 11 44 23](https://cloud.githubusercontent.com/assets/22299251/20518424/167af51c-b097-11e6-8c33-c3f3ac043ec7.png)

Both designs are not matching the correct design.

**Comment by kadams54** [comment]
To clarify, the correct design should display "You currently have no models", correct? Is that true for the other sections as well, e.g., "You have no bundles", "You have no teams", etc.?

**Comment by frankban** [comment]
The profile page has been modified to more properly handle missing entities.
