### ISSUE TITLE
Hovering over charm icons, the tool tip is too close to the image (inside of it)

### ISSUE THREAD

**Issue by faooful** [juju/juju-gui#2215]
<img width="162" alt="screen shot 2016-11-21 at 10 49 23" src="https://cloud.githubusercontent.com/assets/2169216/20489359/3aa922be-b002-11e6-9e72-ddfcbc6b682d.png">

**Comment by kadams54** [comment]
Where is this at? Search results? The user profile page?

**Comment by kadams54** [comment]
The issue was in another codebase and resolved in a pull request there.
