### ISSUE TITLE
Authentication failed. Notification appears with no focus to the related section this error belongs to

### ISSUE THREAD

**Issue by faooful** [juju/juju-gui#2220]
Will attach a screenshot when I can access the staging demo again.

**Comment by ClaraLavina** [comment]
<img width="697" alt="screen shot 2016-11-21 at 11 27 29" src="https://cloud.githubusercontent.com/assets/22299251/20518163/073b7140-b096-11e6-94ba-7c448c25a49a.png">

**Comment by frankban** [comment]
It's not really doable to track this kind of errors from the server to any sections. And we don't want to guess. I believe our efforts should be put into not making this kind of errors happening at all.
