### ISSUE TITLE
Remove "Show changelog" in the Services to be deployed section

### ISSUE THREAD

**Issue by faooful** [juju/juju-gui#2221]

**Comment by hatched** [comment]
So the functionality is to be removed entirely or just the link?

**Comment by ClaraLavina** [comment]
Functionality goes away by removing the link. We do not need them as changelog is still available in the next section "Model changes".

<img width="1054" alt="screen shot 2016-11-22 at 17 18 06" src="https://cloud.githubusercontent.com/assets/22299251/20534070/af7a9322-b0d7-11e6-9338-e70a0b9c8ddd.png">

It should be like this:
![unadjustednonraw_thumb_5f7](https://cloud.githubusercontent.com/assets/22299251/20534280/925763fa-b0d8-11e6-9c3f-42fba215dd70.jpg)

**Comment by ClaraLavina** [comment]
Please notice SERVICES need to be replaced with APPLICATIONS
