### ISSUE TITLE
jujucharms.com doesn't render correctly in ubuntu touch browser

### ISSUE THREAD

**Issue by oSoMoN** [juju/juju-gui#2231]
(originally reported as https://launchpad.net/bugs/1643333)

The ubuntu touch browser app (https://launchpad.net/webbrowser-app) uses the chromium content API for rendering, and should be able to display pretty much any content that chrome on android handles.

Its default UA string is: "Mozilla/5.0 (Linux; Ubuntu 15.04 like Android 4.4) AppleWebKit/537.36 Chromium/53.0.2785.143 Mobile Safari/537.36" (the ubuntu and chromium version numbers are dynamic).

**Comment by hatched** [comment]
Thanks for the bug report. The Juju GUI doesn't officially support any mobile browsers. While its usually functional, it's not recommended. Our supported browser list is simply the greenfield desktop browsers and we do not do any UA sniffing. 

While the jujucharms.com website appears to work correctly for me, if you have a specific bug for the website and not the GUI it can be filed here: https://github.com/CanonicalLtd/jujucharms.com/issues
