### ISSUE TITLE
How to collapse the model changes expandable section is not obvious

### ISSUE THREAD

**Issue by ClaraLavina** [juju/juju-gui#2232]
![screen shot 2016-11-21 at 11 27 13](https://cloud.githubusercontent.com/assets/22299251/20518535/6cc1e8f4-b097-11e6-8755-43fac08b93be.png)

**Comment by anthonydillon** [comment]
If you click on the list again it closes the list.

**Comment by ClaraLavina** [comment]
This is not intuitive at all. 
Could we add a collapse/close button next to the section title and remove the closing functionality from the list items?

**Comment by ClaraLavina** [comment]
![unadjustednonraw_thumb_5f7](https://cloud.githubusercontent.com/assets/22299251/20534708/17c976d0-b0da-11e6-90c4-419cf436b44f.jpg)

**Comment by hatched** [comment]
This section is being removed, closing this
