### ISSUE TITLE
Repetition in the model changes list (see screenshot)

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#2233]
![screen shot 2016-11-21 at 11 03 36](https://cloud.githubusercontent.com/assets/12827541/20518767/39502bd8-b098-11e6-9b7d-67ae8c9b7a96.png)

Are we repeating ourselves by showing two additions even though the one charm has only been added once?

**Comment by hatched** [comment]
No the changelog reports the actions that the GUI is taking. One is adding the charm to the controller the other is adding the application to your model. The wording here could be improved though. Thanks

**Comment by hatched** [comment]
The wording has been updated to separate these two items more cleanly.
