### ISSUE TITLE
When scrolling the add to canvas on charm details button becomes smaller

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#2234]
Sizes should stay the same
![screen shot 2016-11-21 at 10 43 24](https://cloud.githubusercontent.com/assets/12827541/20520245/fc02da18-b09d-11e6-8786-c52ff62333f6.png)
![screen shot 2016-11-21 at 10 44 00](https://cloud.githubusercontent.com/assets/12827541/20520246/fc03434a-b09d-11e6-9ae2-eed43ff0e548.png)

**Comment by hatched** [comment]
Duplicate: #2216
