### ISSUE TITLE
Multi-user issue with deployment when model is destroyed

### ISSUE THREAD

**Issue by urosj** [juju/juju-gui#2239]
There is an interesting bug with the GUI. Say i create a model and share it with you. You want to deploy to it. I delete the model while you have deployment flow open. As gui connects to first available model once the current model is destroyed, deployment flow will actually deploy to completely different model then intended,

**Comment by hatched** [comment]
This has been resolved in a previous commit. It now deploys to a specific UUID so if that UUID no longer exists then it'll just fail.
