### ISSUE TITLE
Cloud logo does not update after destroying model

### ISSUE THREAD

**Issue by anthonydillon** [juju/juju-gui#2259]
To replicate:
- Deploy something to AWS
- Once deployed, go back to the profile and destroy the model
- Then click Create new model 
- See that the GUI is empty and unnamed but still has the AWS logo [1]
- Add an application
- Click deploy
- The cloud choose is then presented again (even though there is AWS on the canvas)

Expected:
- When a model is destroyed
- The user goes into unconnected state and the cloud logo is then removed 

[1] http://awesomescreenshot.com/03b66yyye3

**Comment by frankban** [comment]
It;s also still displayed when going to a profile view.

**Comment by kadams54** [comment]
I believe this was resolved by #2656.
