### ISSUE TITLE
Local charm upload needs pending indicator

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2277]
When uploading a local charm nothing appears to be happening while the charm is uploading. We should add some type of a spinner to the button or the like.

**Comment by frankban** [comment]
@spencerbygraves could you please take a look at this?

**Comment by kasiag** [comment]
@spencerbygraves we have a 'pending' icon in MAAS, it would be worth having a look at it

**Comment by cassiocassio** [comment]
We already check in the flow if the name is duplicate, but we do so at the point of clicking "Deploy"

<img width="1680" alt="screen shot 2017-08-31 at 14 28 53" src="https://user-images.githubusercontent.com/4593556/29925625-d18641e6-8e58-11e7-9b14-425b22b8009b.png">

We check validity, capitals and spaces etc when you tab out/onward from the field.

<img width="817" alt="screen shot 2017-08-31 at 14 30 35" src="https://user-images.githubusercontent.com/4593556/29925719-25619ebe-8e59-11e7-85d8-675630d7d196.png">

Could/should we also check for namespace-unique at that moment?

**Comment by anthonydillon** [comment]
This is not trivial. As the fields are set up to validate the value entered
in the field with a regex.

This field would be an extra blur listener with the function which checks
for uniqueness.

That unique checking function would then have to trigger a validation
failure on the input. Which the basic input components does not support
currently.

It's not impossible, just trying to help explain and outline the steps of
work.

**Comment by kasiag** [comment]
@spencerbygraves can you comment please

**Comment by spencerbygraves** [comment]
There is a button for adding repos in [Snapcraft](https://build.snapcraft.io/) which displays our spinner icon.  We could use this pattern on the import button.

![image](https://user-images.githubusercontent.com/9105999/31334880-0a1034b0-ace8-11e7-9010-f3eacc0dd68c.png)

@cassiocassio are you happy with this?

**Comment by cassiocassio** [comment]
@frankban can you clarify the isue a little?

is this true?

- I  can drag and drop a .zip of a charm from my desktop into the canvas, right?
- the UI is necessarily blocked whilst this is uploading / deploying, but there's nothing for the user to see?
- it's a progress we can't measure the progress of - we need a spinner and can't show a bar?

Q:
- Which the button you're referring to?
