### ISSUE TITLE
Cannot delete applications in error

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2278]
Because Juju won't destroy a unit that is in error we need the ability to 'resolve' an error in the inspector. These buttons appear to have disappeared.

To reproduce, deploy the ghost charm from the charmstore, it'll fail deploy. Then try and destroy it. You'll see that the unit list no longer has the ability to resolve errors.

**Comment by hatched** [comment]
It may be impossible to delete units in error right now but we should still have the 'resolve' buttons back in the event that the user has indeed resolved the issue.

see: https://bugs.launchpad.net/juju/+bug/1642868

**Comment by hatched** [comment]
also related #2025

**Comment by frankban** [comment]
@hatched don't we have the retry/resolve button on the inspector for the specific unit in error?
Anyway, we should really make the GUI more smart for the cases when it's clear that users just want to get rid of units in error. For instance, if the machine hosting the unit does not host other units we could force destroy the machine. In other cases, we could force a resolve until the unit is gone, but only after informing the user that that machine could have been left in a dirty state, as the unit was not able to tear down correctly.

**Comment by hatched** [comment]
@frankban I believe we still do have those buttons however they are effectively useless as Juju just forever retries.

**Comment by hatched** [comment]
I'm removing the milestone from this as this is effectively a Juju issue that we can't do much about at this moment.
