### ISSUE TITLE
hard links cannot span physical devices

### ISSUE THREAD

**Issue by jamesbeedy** [juju/juju-gui#2288]
Controller Series: Trusty
Juju Version: 2.0.0
Juju Provider: Manual

Trying to access the juju-gui I'm seeing: 
"Juju GUI is not available: cannot uncompress Juju GUI archive: cannot rename Juju GUI root directory: rename /tmp/gui951369099/jujugui-2.2.5/jujugui /var/lib/juju/gui/4d3482f8708f5a9c7c93ea55e9a338bebe857a2314a4beefb984840393e7e16b: invalid cross-device link"

I created a ticket with Rackspace seeing if it was possible to enable cross device links to no avail, as it seems to be a non-modifiable system level restriction. Here is the response I got from Rackspace, following my ticket with them:

"Hello James,

I see that the noexec option has been returned to /tmp [1]. From the error that you posted it looks like the Juju application is trying to hard link the /tmp/gui951369099/jujugui-2.2.5/jujugui directory to /var/lib/juju/gui/4d3482f8708f5a9c7c93ea55e9a338bebe857a2314a4beefb984840393e7e16. If the application attempts to create a hard link from the /tmp logical volume, /dev/mapper/vglocal20161111-tmp00, to the root filesystem on device /dev/dm-2, this will not work as hard links cannot span physical devices. If the application could be modified to instead move the directory, this would be possible across physical devices. I would recommend reaching out to the application developers for a workaround to get the GUI installed. If you have any questions or if there is any other way in which we can assist you, please let us know."

Is it possible for us to `mv`, instead of `ln`?

**Comment by hatched** [comment]
Thanks @jamesbeedy for this issue, this is definitely something that we can work towards a resolution on. 

This is handled by code in Juju itself and not the GUI dist specifically so we'll have to get it into a future Juju release. But we'll keep this issue updated with our progress.

Thanks again!

**Comment by frankban** [comment]
The error is specifically returned while renaming the directory: see https://github.com/juju/juju/blob/staging/apiserver/gui.go#L241
In Go and Unix, os.Rename ends up doing syscall.Rename, which fails in the case the src and target are on different file systems. I guess the mv command tries the cheap Rename syscall and if it fails, falls back to copying and then deleting the file. I think we should use the same strategy here.

**Comment by frankban** [comment]
Alternatively, we can uncompress the GUI near the destination, so that we can ensure src and target are in the same fs when calling rename. This solution would be cheaper.

**Comment by frankban** [comment]
The fix will be present in the next Juju release.

**Comment by jamesbeedy** [comment]
@frankban that was fast! awesome!
