### ISSUE TITLE
Inspector configuration changes aren't outlined in the UI

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2296]
Add a charm to the canvas, go to the Config pane and change the name. You'll see that there is no indication that the value has changed. You can also navigate away from the config pane without a warning to save changes. This causes the user to lose their changes unless they KNOW they have to click the somewhat hidden 'save' button

**Comment by anthonydillon** [comment]
Did we have a UI design for unsaved fields from the early days of the inspector. When we had designs for conflict resolution in the inspector?

**Comment by hatched** [comment]
We did, but those don't really apply any longer. I don't think we have to tackle conflict resolution now, just simply indicating that the value has changed, and then indicating this to the user if they try to leave the Configuration without saving.

**Comment by frankban** [comment]
@anthonydillon no rush but it would be nice to improve the user experience of the inspector in the way Jeff suggested.

**Comment by anthonydillon** [comment]
@spencerbygraves could you please attach designs to an inspector config input that has changed and a message to warn the user they are navigating away with unsaved config changes.

**Comment by spencerbygraves** [comment]
The designs are in this issue:

https://github.com/CanonicalLtd/juju-design/issues/176
