### ISSUE TITLE
Cannot commit k8s bundle in sandbox mode

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2297]
Add and deploy: https://demo.jujucharms.com/?store=cs:bundle/canonical-kubernetes-14
You'll see that most of the relations are never created

**Comment by frankban** [comment]
Unfortunately this also affects the deployment of kubernetes on real models. Same issue, some relations are properly established, most of them are not, and many units are still pending even after committing the changes. No apparent JavaScript errors in the console.

**Comment by frankban** [comment]
I was able to reproduce this issue also using the remove-yui-router branch on google cloud.
