### ISSUE TITLE
Number of machines incorrectly computed

### ISSUE THREAD

**Issue by bac** [juju/juju-gui#2306]
When viewing the canonical kubernetes bundle in the GUI it shows

<img width="1098" alt="screen shot 2016-12-16 at 11 18 24" src="https://cloud.githubusercontent.com/assets/617845/21267602/6cf1face-c381-11e6-912e-39df568422a4.png">

The bundle actually has some applications with multiple units so the actual machine count is nine.

**Comment by hatched** [comment]
Thanks for finding this @bac
