### ISSUE TITLE
IP Address shows as None 

### ISSUE THREAD

**Issue by jrwren** [juju/juju-gui#2307]
![screen shot 2016-12-19 at 9 32 34 am](https://cloud.githubusercontent.com/assets/106443/21316316/286bc3fe-c5ce-11e6-8c0e-e63dfc12b967.png)

$ juju status
MODEL       CONTROLLER  CLOUD/REGION   VERSION
parse-test  jem         aws/us-east-1  2.0.2.1

APP           VERSION  STATUS   SCALE  CHARM         STORE       REV  OS      NOTES
parse-server           unknown      1  parse-server  jujucharms    1  ubuntu

UNIT             WORKLOAD  AGENT  MACHINE  PUBLIC-ADDRESS  PORTS  MESSAGE
parse-server/0*  unknown   idle   0        54.82.203.49

MACHINE  STATE    DNS           INS-ID               SERIES  AZ
0        started  54.82.203.49  i-0e33d8b95d5e27d0f  xenial  us-east-1a

**Comment by frankban** [comment]
This affects other browsers as well.

**Comment by jrwren** [comment]
Confirmed in Chrome(57) and Safari(10)

**Comment by jrwren** [comment]
Retrieving environment info.
Connecting to wss://jimm.jujucharms.com:443/model/12bcaa00-accd-4029-81ae-51180d36dd91/api.

--> #1 Admin:Login
{'params': {'auth-tag': 'user-admin', 'credentials': 'aaa'},
 'request': 'Login',
 'request-id': 1,
 'type': 'Admin',
 'version': 3}
<-- #1 response
{'error': 'redirection required',
 'error-code': 'redirection required',
 'request-id': 1,
 'response': {}}

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "megawatcher.py", line 137, in <module>
    start(connect())
  File "megawatcher.py", line 41, in connect
    conn.login(password)
  File "megawatcher.py", line 99, in login
    facades = resp['response']['facades']
KeyError: 'facades'

**Comment by jrwren** [comment]
At some point, gui did display this in a red box in the lower left.

cannot update credentials: updating cloud credentials: read tcp 172.31.7.200:58318->172.31.36.230:37017: i/o timeout

Note the reserved ip addresses.

**Comment by richardsith** [comment]
same problem if I try to deploy Postgresql, here is the screen

![screen shot 2017-02-09 at 13 50 58](https://cloud.githubusercontent.com/assets/9977215/22784102/f39cffc4-eece-11e6-8bcc-4cf069a5467b.png)

**Comment by hatched** [comment]
Thanks for confirming this issue @richardsith 
It's on our roadmap to get resolved, we'll update this issue when we do.
