### ISSUE TITLE
api.jujugui.org has invalid name; uses self-signed certificate

### ISSUE THREAD

**Issue by nskaggs** [juju/juju-gui#2316]
This breaks logging into the charmstore via API:

macaroon: x509: certificate is valid for juju-b4d3a0-44.c.jaas-001.internal, not api.jujugui.org

Cert is pointing to juju-b4d3a0-44.c.jaas-001.internal

**Comment by jrwren** [comment]
use www.jujugui.org

**Comment by hatched** [comment]
If this is still an issue, please feel free to re-open
