### ISSUE TITLE
URL path is wrong when navigating to profile after logging in.

### ISSUE THREAD

**Issue by kadams54** [juju/juju-gui#2317]
Steps to reproduce on the `remove-yui-router` branch:

1. `make clean-all deps fast-babel gui run`
2. `go get github.com/frankban/guiproxy` (skip if you already have guiproxy)
3. `guiproxy -controller jimm.staging.jujucharms.com:443`
4. Go to `http://localhost:8042/` in an incognito window.
5. Login with USSO. Note the URL path is now `/login`.
6. In the model switcher, click on the "Profile" button. You'll see this error in the console: "invalid root path. unable to generate state: invalid root path." Note that the URL path is now `/login/u/USERNAME`.
7. Edit the path so that it's just `/u/USERNAME` and verify that you can now get to the profile.

**Comment by Lukewh** [comment]
FYI this is now on `develop` branch. `remove-yui-router` branch is no more 🍾

**Comment by Lukewh** [comment]
Fixed with all the recent changes and merging to develop.
