### ISSUE TITLE
Add to canvas fails when readme is not defined

### ISSUE THREAD

**Issue by Lukewh** [juju/juju-gui#2330]
Noticed when trying to add Sentry.

`TypeError: this.readmeXhr is null
juju.components.EntityContentReadme`

edit: The charm is added, but the UI hangs on the charm screen.

**Comment by hatched** [comment]
Thanks for the bug report @Lukewh

**Comment by Lukewh** [comment]
Fixed with: https://github.com/juju/juju-gui/pull/2357
