### ISSUE TITLE
Removing applications in the GUI is awkward

### ISSUE THREAD

**Issue by cmars** [juju/juju-gui#2331]
From a chat with Prob in #juju today, I noticed a few oddities about the GUI that do seem awkward for new users.

The button to remove an application is labeled "Destroy" but this doesn't match the terminology used in the CLI, which is "Remove".

When you have removed an application, a flash message appears, "This application has been marked to be destroyed on next deployment." which is confusing, because you wanted to remove something, not deploy anything. This should really say something to the effect of "removed when changes are committed".

Finally, when you commit the changes, you have to scroll way down to click.. a Deploy button. To remove things. That button should perhaps also be labeled "Commit changes"?

**Comment by hatched** [comment]
Good call on all points @cmars thanks!

**Comment by spencerbygraves** [comment]
Thanks @cmars I'll add this to juju-design too.

**Comment by spencerbygraves** [comment]
Could a copy review for this be looked at during the New Orleans sprint?

**Comment by cassiocassio** [comment]
so there's 
$ juju remove-appplication
we only use destroy for models and controllers?
$ juju destroy-model


how about this
"This application will be removed when changes are next committed"

?
