### ISSUE TITLE
Deploying hdp-storm-zookeeper bundle fails

### ISSUE THREAD

**Issue by anthonydillon** [juju/juju-gui#2332]
When clicking "Add to demo" on the bundle details: https://jujucharms.com/hdp-storm-zookeeper/.

I land on the GUI but with an unhelpful error as a user.

![untitled model juju gui](https://cloud.githubusercontent.com/assets/1413534/22061250/071427e0-dd6c-11e6-8b02-3ef899adbcef.png)

**Comment by frankban** [comment]
This has been already fixed at https://github.com/juju/juju-gui/pull/2319
The fix will be online with the release of 2.3.0.
