### ISSUE TITLE
Adding creds for Azure is not supported

### ISSUE THREAD

**Issue by urosj** [juju/juju-gui#2333]
cannot update credentials: updating cloud credentials: validating cloud credentials: credential "azure/uros-jovanovic@external/azure-maybe-test" with auth-type "userpass" is not supported (expected one of ["interactive" "service-principal-secret"])

auth-type: service-principal-secret
application-id: 
application-password: 
subscription-id: 

These are the fields needed. 

The instructions how to get these are wrong as well. Best way to do it is with CLI and copy/paste the values. We should redirect the user to get the creds using CLI. The link in the GUI is useless.

**Comment by frankban** [comment]
Manually setting azure credentials is now supported, for the interactive mode I created https://github.com/juju/juju-gui/issues/2369
