### ISSUE TITLE
When deploying the canonical Kubernetes bundle, the relationships line disappear

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#2334]
Ive tried this with a few more bundles and it seems to work fine. I think it only happens with canonical kubernetes. 

![screen shot 2017-01-18 at 11 59 19](https://cloud.githubusercontent.com/assets/12827541/22063257/c4f388b0-dd75-11e6-8248-75cc3103bd3d.png)

**Comment by frankban** [comment]
This seems to be the same issue fixed at https://github.com/juju/juju-gui/pull/2300
If this is not the case after 2.3.0 is released, please reopen this bug.
