### ISSUE TITLE
Profile link should be absolute

### ISSUE THREAD

**Issue by Lukewh** [juju/juju-gui#2336]
After creating a new model `/new` clicking the profile link doesn't work (`/new/u/admin`)
- Go to profile
- Click 'Create New' under Models
- After new canvas loads click profile link
- `app/state/state.js&app/store/env/bakery.js&app/jujulib/index.js&app/jujulib/charmstore.js&app…:428 invalid root path. unable to generate state: invalid root path.`

**Comment by kadams54** [comment]
Note that this is a dupe of #2317.
