### ISSUE TITLE
view credentials via juju-gui

### ISSUE THREAD

**Issue by jamesbeedy** [juju/juju-gui#2338]
It would be nice if the gui displayed what credentials were being used for the current model. 
![screen shot 2017-01-19 at 7 00 38 am](https://cloud.githubusercontent.com/assets/5590546/22111375/f9e80a5c-de13-11e6-92d3-1672174dd3b4.png)

**Comment by hatched** [comment]
Thanks for bringing this up @jamesbeedy. I'll get this on the roadmap.

**Comment by jamesbeedy** [comment]
@hatched great! thx!

**Comment by frankban** [comment]
I am being optimistic assigning this to fontaine, we'll see.

**Comment by kadams54** [comment]
Related: #2506.
