### ISSUE TITLE
Model action buttons are displayed in the header when in the profile.

### ISSUE THREAD

**Issue by kadams54** [juju/juju-gui#2350]
Import & export are one-off, model-specific actions. When in the user profile, the user isn't in any particular model, at least not from a UX perspective. Consequently it doesn't make sense to continue displaying these buttons for the profile. It's unclear which model will be exported or what exactly will happen on import (Add to the last model viewed? Create a new model?).

![selection_001](https://cloud.githubusercontent.com/assets/378036/22263284/ec962eec-e241-11e6-9bfd-db45eedb0a6d.png)

**Comment by mitechie** [comment]
In the last sprint we talked about moving these to being actions more associated with the model level and moved away from the header like this. The main purpose was to split the idea of model level activities used rarely and more frequent items like sharing/etc.

**Comment by hatched** [comment]
So, sounds like we're in agreement that they should be hidden when in the profile view :)

**Comment by anthonydillon** [comment]
I believe shortly, we will need a model settings panel for a number of
model level features. It seems sensible to move import/export to that
window. Cleaning up the header of the canvas.

On Tue, 24 Jan 2017, 19:34 Jeff Pihach, <notifications@github.com> wrote:

So, sounds like we're in agreement that they should be hidden when in the
profile view :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/juju/juju-gui/issues/2350#issuecomment-274912641>, or mute
the thread

**Comment by kadams54** [comment]
We've got logic now to hide the sharing button when viewing the profile; seems like it shouldn't be that hard to include the import/export buttons.

**Comment by frankban** [comment]
With one caveat: while the sharing button can always be hidden when we are not connected to a model (and it is), the import/export must be displayed also in the case the user is working on a new canvas/creating a new model, in which case we don't have a model connection yet, but importing/exporting must be provided nonetheless.

**Comment by ClaraLavina** [comment]
Import/export buttons are displayed also when the user has no models in the profile. 

<img width="1270" alt="screen shot 2017-02-21 at 16 55 10" src="https://cloud.githubusercontent.com/assets/22299251/23207439/34cfa644-f8e9-11e6-8deb-b74ba2e5bbdc.png">

In this scenario - empty profile:
- Export button triggers the download of an empty yaml file
- Import button adds yaml file but it remains in the background and there's no way to go back to this model (see image below)

![screen shot 2017-02-22 at 10 39 54](https://cloud.githubusercontent.com/assets/22299251/23208063/86a7783c-f8eb-11e6-8314-f196521c8b27.png)

These two buttons should be hidden when in the profile page, as they do not refer to any specific model.
