### ISSUE TITLE
profile errors in jujugui for api.jujucharms.com/api/v1/agreements

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#2362]
Juju GUI 2.2.7 and Juju 2.1beta4 on guimaas

When loading the gui profile page:

    GET https://api.jujucharms.com/terms/v1/agreements 401 (Unauthorized)
    api.jujucharms.com/identity/v1/discharger/discharge:1 POST        https://api.jujucharms.com/identity/v1/discharger/discharge 401 (Unauthorized)

I've logged into the charmstore via the login box in the upper right, but I'm still getting these 401 requests. This seems to imply that I would not be able to agree/deploy charms that I've agreed to via the cli.

**Comment by hatched** [comment]
These have been removed from the profile page temporarily so these errors have stopped.
