### ISSUE TITLE
maas ip address no longer passed in ModelGet api call

### ISSUE THREAD

**Issue by anastasiamac** [juju/juju-gui#2372]
According to https://bugs.launchpad.net/juju/+bug/1659612, ModelConfig.ModelGet no longer contains cloud related information.

Please update the calls per recommendation in comment 1.

**Comment by frankban** [comment]
Thanks for pointing us to this Anastasia, we'll make sure to update the calls when on Juju 2.

**Comment by frankban** [comment]
From LP: 
"The ModelManager.ModelInfo method can be used to identify the cloud/region related to the model; and the Cloud.Cloud method can be used to obtain the details of the cloud and its regions."

**Comment by frankban** [comment]
This has been fixed.
