### ISSUE TITLE
Unable to deploy to new model in gui in juju because deploy button is disabled

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2384]
The button is disabled in the deployment flow on a new model.

Build the latest GUI and switch to the profile view. Create New, add a charm, then go into the DF. You'll see the deploy button is disabled so you cannot deploy.

**Comment by hatched** [comment]
ALso see #2380

**Comment by frankban** [comment]
I was not able to dupe this using a local lxd provider with guiproxy and with gijoe. The deploy button is always enabled.
Could you please provide the steps to dupe?

**Comment by hatched** [comment]
It turns out this was a UX issue that we have to resolved. I hadn't provided a required field.
