### ISSUE TITLE
Browser back button doesn't work when in charmbrowser

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2391]
Focus the search box and then navigate to a charm in the store. Hit the browsers back button. It doesn't go back to the previous page.

**Comment by Lukewh** [comment]
According to `state.js` the following rules apply:
- `/store/u/admin/default` is a valid route when clicking on the search input.
- `/store/u/admin/default` is not a valid route when clicking the back button on charm details.

According to the code `/store` is reserved and nothing should be allowed after it - is this still the case? If so clicking the search input should change the url to `/store` but with @frankban 's change (https://github.com/juju/juju-gui/pull/2402) surely this would go to a disconnected mode?

**Comment by Lukewh** [comment]
https://github.com/juju/juju-gui/issues/2405 fixes this
