### ISSUE TITLE
A subordinate's HTTP exposed interface is not visible in juju gui

### ISSUE THREAD

**Issue by anastasiamac** [juju/juju-gui#2392]
From https://bugs.launchpad.net/juju/+bug/1662014:
HTTP interface exposed by subordinate charm is not visible in the principals "Expose application" information box.

**Comment by deanmaniatis** [comment]
@anastasiamac Thank you for posting it here for me.

Adding full bug description and Juju version:

Client: 2.1-beta5-xenial-amd64
Controller: 2.1-beta4

"When deploying a subordinate charm which exposes an HTTP interface
  (not tested with other interfaces, may have impact there as well), it
  is not visible in the principals "Expose application" information box
  on juju-gui's web UI. It is hinted on the CLI when using `juju status`
  as an exposed port but if using only web-gui you cannot really defer
  whether there is such an additional service offered and you can't also
  use the link on "Expose application" box UI to quickly navigate to
  this HTTP page."

**Comment by frankban** [comment]
Thanks for reporting!

**Comment by hatched** [comment]
@deanmaniatis Can you let us know which principal and subordinate charms you were using?

**Comment by deanmaniatis** [comment]
@hatched It was a subordinate charm i was working which exposes a web UI. I've uploaded it [here](https://github.com/deanmaniatis/netdata-reactive) so you can reproduce it.


1. juju deploy ubuntu
2. juju deploy netdata-reactive
3. juju add-relation ubuntu netdata-reactive

If you check juju gui there won't be any reference that the subordinate is exposing something as seen in from the CLI (http://paste.ubuntu.com/24027908/).
