### ISSUE TITLE
gisf: logging in from the deployment flow does not propagate auth to storefront

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#2417]
- go to /new
- add a charm;
- click to deploy;
- click to sign up or log in;
-click deploy to create the model;
- you should be properly redirected to /u/{user}/{model};
- but if you refresh, you'll find out that you are logged out from the store front.

To dupe this you must set up the current `gui-handles-auth` branch of the storefront with the most recent GUI from `develop` branch, then `make run`, then log in and activate the GUI switch for everyone at `/_switchboard`. Then, in another browser, use incognito mode to start from scratch.

**Comment by jaycee** [comment]
Fixed in https://github.com/juju/juju-gui/pull/2421
