### ISSUE TITLE
gisf: storefront login does not work

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#2418]
There is a javascript error about juju_config not being defined, and the page is totally broken.

To dupe this you must set up the current `gui-handles-auth` branch of the storefront with the most recent GUI from `develop` branch, then `make run`, then log in and activate the GUI switch for everyone at `/_switchboard`. Then, in another browser, use incognito mode to start from scratch.

**Comment by frankban** [comment]
This could be a storefront bug, but it's filed here as it can block the release.

**Comment by jaycee** [comment]
This is actually a flaw in storefront--it doesn't properly pass through all requests to gui on the login route.

**Comment by jaycee** [comment]
Fixed in a bb branch.
