### ISSUE TITLE
Sentry link in the store fails to show the charm

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#2429]
To reproduce:
- open the store
- scroll down to the Sentry charm and click on it
- the page will show "There was a problem while loading the entity details. You could try searching for another charm or bundle or go back."
- your console should show `cannot fetch the entity:Error: invalid charm/bundle name: "~ricardokirkner"`

**Comment by hatched** [comment]
Thanks @huwshimi This is confirmed with 2.3.0

**Comment by frankban** [comment]
The static (curated) content in `components/store/store.js` include hardcoded data-references to old style URLs, that's why we are seeing that error.
