### ISSUE TITLE
Deep linking to models doesn't work if you have to log in with GUI in Juju

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2430]
Juju 2.1 and GUI 2.3.0

If you try to visit `/u/admin/{modelName}` If you've already logged in in that same tab then it'll navigate you to that model. 
If the login takes a while there is no indication that it's doing that while showing you the login screen. 
If you however get stopped on the main page to enter your credentials you'll get navigated to the `default` model.

**Comment by wallyworld** [comment]
PR https://github.com/juju/juju/pull/6992

**Comment by frankban** [comment]
The branch you linked solves this issue, as it includes in the config the UUID corresponding with the given model owner/name as specified in the path.

**Comment by frankban** [comment]
I will close this once 2.1 is out and it's demonstrated it works.

**Comment by frankban** [comment]
This is now included in 2.1.
