### ISSUE TITLE
Search results not displaying all returned results from api

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2435]
On guimaas do a search for "term" You'll only see two charms when 5 are returned.

2 of the 5 are namespaced versions of a promulgated charm so thats expected that they aren't removed but one is a namespaced charm with no promulgated alternative and isn't shown

**Comment by urosj** [comment]
@hatched @Lukewh 
This is the correct behaviour. If promulgated exist, show only subset of promulgated. If they don't they show all community results.

**Comment by hatched** [comment]
@urosj So if any promulgated charms are returned we're only supposed to show those and disregard others that are returned without promulgated matches?

ex)

| id | returned |
|---|---|
| term-example | yes |
| ~foo/term-example | no |
| term-test | yes |
| ~foo/term-test | no |
| ~bar/term-awesome | ? |

**Comment by galgalesh** [comment]
This is a very annoying issue/feature. It is currently not possible to find all charms on a subject without resorting to Google. Moreover, **this behavior makes charms disappear from the store.** Charms that show up in search results one day might not show up at all the next day, [depending on what charms have been promulgated](https://lists.ubuntu.com/archives/juju/2017-February/008611.html).

I totally understand the rationale behind putting the recommended charms front and center. However, completely hiding the community charms isn't the way to go. At the very least, there should be an option to show all search results at the end of the recommended charms list so the community doesn't have to resort to [writing their own crawlers to get an idea of what is actually in the store..](https://lists.ubuntu.com/archives/juju/2017-February/008613.html)

**Comment by urosj** [comment]
I suggest we add a link to "community charms", which then additionally lists all results if user requests to do so.

**Comment by frankban** [comment]
In the search results page let's also remove the toggle between charms and bundles and just show them all together.

**Comment by Lukewh** [comment]
I started this before - some of it might be useful https://github.com/juju/juju-gui/pull/2449

**Comment by ClaraLavina** [comment]
suggestion: When searching for a specific charm, could it be possible to show (some of) the bundles that contain this charm?

**Comment by hatched** [comment]
@ClaraLavina we return charms and bundles that match the supplied string. We don't know what type of entity the user is searching for. But the side effect of this is that we typically do return bundles which contain matching charms.

**Comment by ClaraLavina** [comment]
It would be nice to see that some bundles, as an example and in this case Kubernetes, contain the Easyrsa charm.

<img width="1193" alt="screen shot 2017-03-31 at 12 16 23" src="https://cloud.githubusercontent.com/assets/22299251/24548218/020ac51e-160c-11e7-8737-bacf6a1d58f9.png">
