### ISSUE TITLE
If terms requests 404 when opening DF then notify and block deploy

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2436]
If you try to deploy a charm which requires terms but we aren't able to fetch those terms we need to throw an error notification and block deploy until that charm is removed.

To reproduce this you can add a charm with terms but never upload the terms, or never 'release' the terms. This can be done easily using the term test script

**Comment by frankban** [comment]
This has been fixed in the linked PR.

**Comment by huwshimi** [comment]
@frankban I think we still need to update some terms api code, or wait for the api to update as currently we don't get an error when the terms 404.

**Comment by frankban** [comment]
@huwshimi could you please open another bug that describes this? What request are we sending, which API, what do we get back, what should we get instead?

**Comment by huwshimi** [comment]
@frankban I've tried to outline the problem here: #2488.
