### ISSUE TITLE
Investigate not opening a popup for logging in

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#2438]
We should provide a better authentication experience, and this is high priority for dax.

**Comment by hatched** [comment]
When doing the initial login I see no reason why we can't redirect as there is no state to preserve. We can also do the same for the on-canvas login button if the ecs is empty. Then we're only left with the DF requiring a popup until we can come up with a quality solution for storing and then re-importing the user state.

WRT the DF login: Now that we can export bundles with uncommitted state we can potentially export the state as a bundle, store it in local storage, then re-import it. The downside to this is that depending on the complexity of what is on the canvas this re-import can take considerable time (see openstack) and we'd want to then load them back into the deployment flow. This process would likely require some UI work to show that it's "working".  In this case I don't feel like the popup is very inconvenient compared to the former.  

I propose that the first step forward here is to implement the redirect for the two known-ok spots and leave the DF login.

**Comment by frankban** [comment]
+1, we can gradually improve later, but starting with the easy cases sounds good.

**Comment by Lukewh** [comment]
Related https://github.com/juju/juju-gui/issues/2502

**Comment by hatched** [comment]
With the new UI enhancements this has been deferred.

**Comment by frankban** [comment]
I'll put this on the roadmap as candid is gonna support this soon.
