### ISSUE TITLE
Signing out of the GUI 404 error

### ISSUE THREAD

**Issue by ClaraLavina** [juju/juju-gui#2440]
When you sign out of the GUI, search bar is prepopulated with "new" and returns a 404 error.

From Chrome Version 56.0.2924.87

![screen shot 2017-02-14 at 16 49 20](https://cloud.githubusercontent.com/assets/22299251/22939475/b162efc2-f2d6-11e6-9e18-7744cabfdc1a.png)

**Comment by hatched** [comment]
Thanks for the bug report @ClaraLavina but this has been rewritten and resolved.
