### ISSUE TITLE
Inconsistency between Logout and Sign out

### ISSUE THREAD

**Issue by ClaraLavina** [juju/juju-gui#2441]
Once signed in, jujucharms.com pages show "SIGN OUT" buttons

![screen shot 2017-02-14 at 16 55 56](https://cloud.githubusercontent.com/assets/22299251/22939447/9b3ee25a-f2d6-11e6-8388-866d96d386ab.png)

When in the canvas, this button changes to "LOGOUT"
![screen shot 2017-02-14 at 16 49 43](https://cloud.githubusercontent.com/assets/22299251/22939446/9b3d27f8-f2d6-11e6-9dc7-37a63b8b3a78.png)

From Chrome Version 56.0.2924.87

**Comment by hatched** [comment]
Thanks for the bug report @ClaraLavina but this has been rewritten and resolved.
