### ISSUE TITLE
In Firefox, text box for entering SSH key is misaligned

### ISSUE THREAD

**Issue by bac** [juju/juju-gui#2443]
<img width="1668" alt="screen shot 2017-02-14 at 17 17 15" src="https://cloud.githubusercontent.com/assets/617845/22949777/bfbeb4d6-f2d9-11e6-9d51-113c414ad8bf.png">

Placing the cursor into the box causes the cursor to be half in and half out. When you start typing the box grows to accommodate the text.

**Comment by Lukewh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Firefox input bug](https://trello.com/c/VrtZr40y/736-firefox-input-bug)
