### ISSUE TITLE
Deploy button is active even if there are no credentials.

### ISSUE THREAD

**Issue by bac** [juju/juju-gui#2444]
When adding credentials, the deploy button is active.

<img width="1668" alt="screen shot 2017-02-14 at 17 17 15" src="https://cloud.githubusercontent.com/assets/617845/22949887/257ae830-f2da-11e6-951d-d4276ef2f223.png">

If you enter the credentials, but fail to press the `Add credential` button, then you get the warning shown below.

<img width="1668" alt="screen shot 2017-02-14 at 17 18 04" src="https://cloud.githubusercontent.com/assets/617845/22949894/27fdf674-f2da-11e6-9b94-7bf349b4e500.png">

That's not bad but it would be better for `Deploy` to be inactive.

**Comment by huwshimi** [comment]
This should have been resolved in #2428. If you are still seeing the issue on develop then please reopen this.

**Comment by bac** [comment]
Thanks @huwshimi -- I knew you'd worked on it but assumed your fix was in 2.3.0.
