### ISSUE TITLE
Add a link to Juju docs and "get started" page

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#2448]
Now that most of the times gisf redirects users to the GUI, it's not really easy to access Juju docs and the get started page.

**Comment by anthonydillon** [comment]
We are slowly rolling all docs into a central docs system [1]. These doc's naturally live at https://docs.ubuntu.com/juju but can be served at any URL.  

I would suggest, docs.jujucharms.com or just leave it on docs.ubuntu.com for now. This would resolve this issue and if everyone is happy then increase the priority of the move.

[1] https://docs.ubuntu.com

**Comment by urosj** [comment]
@anthonydillon but until we have the docs there, we'll just link to the docs at the URL they are now.

**Comment by anthonydillon** [comment]
@urosj good plan.

**Comment by Lukewh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add a link to Juju docs and "get started" page](https://trello.com/c/TgbSDdtC/732-add-a-link-to-juju-docs-and-get-started-page)
