### ISSUE TITLE
Update to a newer version of vanilla

### ISSUE THREAD

**Issue by Lukewh** [juju/juju-gui#2461]
The scss code smell is stacking up in juju-gui with layers of scss atop the old version of vanilla in order to implement styles that are in newer versions of vanilla.

**Comment by hatched** [comment]
After upgrading vanilla these `!important` should be able to be removed https://github.com/juju/juju-gui/pull/2456/files#diff-20e7f1172eec27f612f1c81fd57e065fR16

**Comment by frankban** [comment]
Did we make this upgrade?

**Comment by Lukewh** [comment]
@frankban: No, this probably won't be done for a while. The new vanilla colours are going to be moved across as a first sub-issue/ step. There's a bigger discussion/ plan needed for full vanilla upgrade that I need to have with @anthonydillon.

**Comment by frankban** [comment]
My undertsanding is that this will happen now \o/
