### ISSUE TITLE
Add a link to file issues in the help menu

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#2462]
The link should point to https://jujucharms.com/issues if the user is authenticated and we are in gisf.
Otherwise, let's point users to github: https://github.com/juju/juju-gui/issues
Target must be _blank.

**Comment by Lukewh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add a link to file issues in the help menu](https://trello.com/c/5dr699na/743-add-a-link-to-file-issues-in-the-help-menu)
