### ISSUE TITLE
"add to canvas" should be "add to model".

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#2466]
I think it'd be useful to s/canvas/model throughout the gui and site. Now that there's not really the idea of the demo GUI which is not a real model I think referring to a model is best. 

If there's a currently named or active model I think that the button can/should name that model. Add to model XXX or the like so that context is clear and meaningful to the end user.

**Comment by hatched** [comment]
Good idea!

-  [ ] Rename all instances of "Add to canvas" to "Add to model"
-  [ ] If we have an active model "Add to {modelName}"
