### ISSUE TITLE
Unclear heading on DF "Public Cloud" after I pick GCE/AWS/etc. 

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#2471]
As I pick a cloud I can change it and there's a big heading "Public Cloud", huh? The only options are public clouds. Is this telling me anything? Do we need that? Maybe that can just stick to something like "Choose your cloud" or the like.

**Comment by hatched** [comment]
This is updated based on the context but we can simplify it:

https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/components/deployment-flow/deployment-flow.js#L614
