### ISSUE TITLE
Add to model button disabled when in read-only mode

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2477]
This is to be expected but it should have some indication as to why. There doesn't appear to be a 'read-only' message anywhere in the GUI.

**Comment by spencerbygraves** [comment]
we did some design on read only label a while back, we can review those again.

**Comment by frankban** [comment]
@spencerbygraves yes please.

**Comment by spencerbygraves** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Review read only design](https://trello.com/c/jZFUnU4S/767-review-read-only-design)

**Comment by spencerbygraves** [comment]
The last work done on this was some time ago, so I'm not sure this is up to date. Any thoughts?

https://github.com/CanonicalLtd/juju-design/issues/110

**Comment by ClaraLavina** [comment]
I buy the latest design, the white non-clickable label replacing the Deploy button. 

Thanks @spencerbygraves!!

**Comment by frankban** [comment]
Cool thanks @ClaraLavina
