### ISSUE TITLE
Should clearing the search box and hitting return search for *all* charms/ bundles?

### ISSUE THREAD

**Issue by Lukewh** [juju/juju-gui#2483]
Or should it show the store?

**Comment by frankban** [comment]
I'd be +1 on showing the store, as the other query seems very expensive.

**Comment by anthonydillon** [comment]
Agree the site page would be best in that case. There is anything issue to
remove filters when performing a new text search. For example, do a search.
Filter by bundle. Then do a new search. Should result in search for all
entity's.
