### ISSUE TITLE
getAgreementsByTerms does not provide an error when the terms do not exist

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#2488]
When doing a getAgreementsByTerms request if the terms do not exist for the ids provided then the request does not return an error and also returns `null` for the list of terms, which is the same result as when all terms have been agreed to.

The solution is possibly a bit complex as some terms may exist and some not. In the case that the user needs to agree to those terms before deploy we would want to know if any terms do not exist and cancel the deploy.

See: https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/jujulib/terms.js#L192

**Comment by hatched** [comment]
cc @cmars @mattyw

**Comment by cmars** [comment]
@hatched It looks to me like `/v1/agreement` should respond with a 404 if any of the terms do not exist. Is this not the case?

**Comment by hatched** [comment]
@cmars it does return 404, however a 404 is a "successful" request. The rest of the apis we deal with typically return a json object which can contain an error field which we use to indicate if an error has occurred or not. Lets discuss if modifying the return values of this api is something we want to do.

**Comment by hatched** [comment]
@huwshimi after discussing with @cmars, the api on jujugui may return the necessary content, can you take a look when you have a chance, thanks!

**Comment by huwshimi** [comment]
This now works with jujugui.org so it should be resolved with the next release of the api.
