### ISSUE TITLE
non-public charm icons don't show in gui

### ISSUE THREAD

**Issue by jamesbeedy** [juju/juju-gui#2490]
what the title says

<img width="1436" alt="screen shot 2017-02-21 at 12 03 25 am" src="https://cloud.githubusercontent.com/assets/5590546/23155899/75936eca-f7c9-11e6-8360-815d4808485a.png">

**Comment by frankban** [comment]
Are those charms just unpromulgated or also local? I am not being able to dupe, could you please provide an example of a charm which exposes this problem?

**Comment by jamesbeedy** [comment]
@frankban any of these under my team namespace http://paste.ubuntu.com/24039222/. Now that I think about it, it might be a team namespace issue, and not promulgation.

**Comment by jamesbeedy** [comment]
@frankban I have granted everyone access on this charm for an example: cs:~creativedrive/fiche-1

**Comment by frankban** [comment]
I can see the icon of that one, and that's because you opened up access for that (I bet now you can see the icon of fiche as well). So this issue is related to non-public charms: I am working on restoring the ability to log into the charm store from the GUI as served by Juju. After logging in icons are visible.

**Comment by frankban** [comment]
It's ok that you cannot see the icons if you are not logged into teh charm store, as the icon is not public. We should fallback more gracefully, for instance by showing the default icon instead of a broken image.

**Comment by jamesbeedy** [comment]
@frankban totally - this is the case, with the exception that even when logged into the charmstore, I can't see the icons for charms in my team namespace that aren't released.
