### ISSUE TITLE
Add ability to link the heading of a charm's readme

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#2493]
From https://github.com/CanonicalLtd/jujucharms.com/issues/398:

The ability to link to a heading of the Charm readme. Github has this nice little "url" icon appearing next to each heading that can be used to link to that part of the readme. Very useful for sending users to the correct part of the documentation. Example: https://github.com/ibcnservices/layer-openvpn#administration

**Comment by kadams54** [comment]
@hatched Between this and #2650 we may need to revisit support for hashes in the state object.
