### ISSUE TITLE
Community bundles "files" links not working

### ISSUE THREAD

**Issue by galgalesh** [juju/juju-gui#2494]
Page: https://demo.jujucharms.com/?store=cs:~tengu-team/bundle/limeds-bigdata

click `bundle.yaml` in the "files" section.

links to: https://api.jujucharms.com/charmstore/v5/limeds-bigdata/archive/bundle.yaml
should link to: https://api.jujucharms.com/charmstore/v5/~tengu-team/limeds-bigdata/archive/bundle.yaml

**Comment by frankban** [comment]
New URL is https://jujucharms.com/u/tengu-team/limeds-bigdata/bundle
I duped the bug after logging in.
