### ISSUE TITLE
Homepage and signup flow changes for the public beta

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#2497]
Here are the homepage and signup flow changes we need to make:

1. The demo will no longer exist, so for now we'll remove the Demo button from the top navigation
![screen shot 2017-02-21 at 14 44 29](https://cloud.githubusercontent.com/assets/12827541/23169631/6859fbea-f844-11e6-88bf-3a44718c34fc.png)

2. At the moment, after the application is built and the user clicks deploy, we see this: 
![screen shot 2017-02-21 at 13 03 43](https://cloud.githubusercontent.com/assets/12827541/23169815/0ef46a6c-f845-11e6-891a-7b7eeb767fa1.png)

But it should be the following:

![screen shot 2017-02-21 at 14 49 00](https://cloud.githubusercontent.com/assets/12827541/23174256/b2ab7a5c-f853-11e6-93db-7b98087662af.png)

With a few small tweaks: 

- Where the red line is, say: 
- Next to Login, add the 'new tab' icon 

![screen shot 2017-02-21 at 14 48 35](https://cloud.githubusercontent.com/assets/12827541/23170010/b962746c-f845-11e6-80b2-21941d6b0959.png)

3. Once they have signed up, they will then be able to name their model, choose a cloud etc 
![screen shot 2017-02-21 at 15 08 36](https://cloud.githubusercontent.com/assets/12827541/23170595/a97b907c-f847-11e6-9e27-c6ec720b2475.png)

Any questions let us know
Thanks!

**Comment by frankban** [comment]
Thanks Elvi, the first part of the bug is already in progress.
Also note that, re the deployment flow change, when implementing the feature please don;t get confused: Login and Sign up actually point to the same URL.

**Comment by kadams54** [comment]
@elvirafigueras I'm not entirely sure what should go in place of the red line. Am I missing something?
