### ISSUE TITLE
Stange behaviour in the deployment flow

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#2499]
So, I'm on this screen 
![screen shot 2017-02-21 at 13 03 43](https://cloud.githubusercontent.com/assets/12827541/23174845/91db823e-f855-11e6-9f61-435c79ff39e1.png)

After about 30 seconds, I am either redirected to the Ubuntu One page or it tries to connect to the Juju model 
![screen shot 2017-02-21 at 16 47 15](https://cloud.githubusercontent.com/assets/12827541/23174908/c254f472-f855-11e6-885d-55bee6d47fe3.png)
<img width="1385" alt="screen shot 2017-02-21 at 16 48 53" src="https://cloud.githubusercontent.com/assets/12827541/23174981/f535de4c-f855-11e6-98b9-be701deac903.png">

This happens even if i don't click on anything.

**Comment by frankban** [comment]
This was due to periodic WebSocket disconnections and has been fixed.
