### ISSUE TITLE
After login in, profile page shows a "Log in to the charmstore" button

### ISSUE THREAD

**Issue by ClaraLavina** [juju/juju-gui#2501]
I log in via USSO and I'm taken to my profile page. "Log in to the charmstore" button appears but it seems to be not working. This shouldn't be here.

<img width="1270" alt="screen shot 2017-02-21 at 16 55 10" src="https://cloud.githubusercontent.com/assets/22299251/23175541/a2659476-f857-11e6-9f2b-33db9aaa2e42.png">

**Comment by hatched** [comment]
Thanks @ClaraLavina - in the soon-to-be-released code this is resolved.
