### ISSUE TITLE
Refactor the `window.open` functionality

### ISSUE THREAD

**Issue by Lukewh** [juju/juju-gui#2502]
There's currently a popup to say 'Please allow popups from :url'. This is because the `window.open` call is not directly from a user event (such as 'onClick'). Moving to 'onClick' will negate the need for a popup.

**Comment by spencerbygraves** [comment]
Until this fix is in place, can we make the two messages consistent in style please. Perhaps we can use the small white message on both the homepage and GUI, and remove the yellow message.

**Comment by frankban** [comment]
Closing this one in favour of https://github.com/juju/juju-gui/issues/2438
