### ISSUE TITLE
I cant access jujucharms.com if I am logged in

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#2503]
![screen shot 2017-02-21 at 17 52 27](https://cloud.githubusercontent.com/assets/12827541/23177402/90cdf710-f85e-11e6-8ed2-12572070b7dd.png)

The site doesn't seem to connect, just loads for a really long time

**Comment by hatched** [comment]
We have released an update since this. If you are still seeing this issue please re-open.
