### ISSUE TITLE
Automatic login attempts on anonymous deployment flow

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#2509]
From Uros email:
*Leave DF open in anon mode and it redirect to trying to log in and ends up in inf spinner by itself if left open for a while. Present in bashir and checkov. So, something for dax, but it is annoying.*

This might be related to WebSocket reconnections: we need a pinger to avoid those, even if it fails as the Juju pinger is only available to authenticated users.

**Comment by frankban** [comment]
Also note that, even if avoiding reconnections will make this better, disconnections are not the root cause if this: you could have a proper reconnection due to real network issues, in which case we'd encounter this problem again, even with a pinger. I think the problem is more related to how we handle anonymous mode. We basically allow connecting to a controller without authenticating if the root state is "new" (meaning /new is included in the URL). But, since the store is (wrongly) also a root state, /new is removed as soon as we open the store (for instance, because we want to deploy something). From that point on, a reconnection will fire a connectedChange event that will try to log the user in.

**Comment by urosj** [comment]
This happens even outside of DF. As long as you're anonymous user and put something on the canvas, sooner or later (30s inactive period) you end up with a request to login. I suspect there might be some authenticated call hidden somewhere.
