### ISSUE TITLE
No actions just keyboard shortcuts. 

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#2511]

**Comment by Lukewh** [comment]
Now that keyboard the keyboard shortcuts overlay is being surfaced, we should hide the settings on that overlay as they're not part of the same context.

**Comment by hatched** [comment]
@elvirafigueras we can't just remove functionality that people use without moving it somewhere else. I'm ok with having the options not under a "Keyboard Shortcuts" heading but not removed entirely.

**Comment by frankban** [comment]
This is now tracked at https://github.com/juju/juju-gui/issues/2526
