### ISSUE TITLE
Remove outline from help menu elements

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#2514]
How to recreate the bug:

1. Go to the canvas and click on the help icon (?)
2. Click on any of the first two links, which take you to a new tab
3. Go back to previous tab and now just hover over either of the links
4. Tada!

![screen shot 2017-02-22 at 12 24 48](https://cloud.githubusercontent.com/assets/12827541/23215674/295ca8d0-f90b-11e6-908c-3e7f7b13bf3b.png)

**Comment by huwshimi** [comment]
This menu no longer exists.
