### ISSUE TITLE
Loading bundle by URL has state error

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#2538]
When you visit a bundle URL directly (e.g. `/u/containers/elk-stack`) it has a state error: `Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Constructor component.`

**Comment by hatched** [comment]
There don't appear to be any negative side effects from this. Did you notice anything that would make this urgent?

**Comment by huwshimi** [comment]
@hatched I don't imagine it's urgent.
