### ISSUE TITLE
CA certificate in juju gui is invalid.

### ISSUE THREAD

**Issue by burton-swan** [juju/juju-gui#2553]
juju gui version: 2.4.2
juju version: 2.1.0-xenial-amd64
Cloud: AWS
Region: us-east-1
Browser: Google Chrome Version 56.0.2924.87 (64-bit) and Firefox 51.0.1 (64-bit)

Procedures:
1. bootstrap a controller on AWS cloud
2. run juju gui in Terminal
3. access the admin/default link from stdout in Google Chrome or Firefox, e.g.:

https://<IP_ADDRESS>:<PORT>/gui/u/admin/default

Expected:
juju gui admin/default login page shows up without any exception or error.

Actual:
a) CA certificate error page shows NET::ERR_CERT_AUTHORITY_INVALID (Google Chrome) or SEC_ERROR_UNKNOWN_ISSUER (Firefox).
b) Manually proceed (Google Chrome) or add exception (Firefox) to access the juju gui admin/default login page.

End users may feel confused when this error occurred.

Relevant links:
https://jujucharms.com/docs/stable/help-aws
https://jujucharms.com/docs/stable/controllers-gui

**Comment by frankban** [comment]
The exception appears when Juju is bootstrapped with a self-signed certificate, and since the GUI is served by the controller itself, the same certificate is used. But I agree that this can be confusing and feel unsafe for users, so I am opening a bug in the docs tracker so that we can at least mention this.

**Comment by frankban** [comment]
Opened https://github.com/juju/docs/issues/1697, closing this one.
Thanks for this suggestion!

**Comment by burton-swan** [comment]
Correct, it's because the certificate is generated and issued by juju itself instead of recognised Certificate Authorities officially accepted by Google Chrome and Firefox. Thank you for the update.
