### ISSUE TITLE
When store/ search is open, there is no margin to the help button

### ISSUE THREAD

**Issue by Lukewh** [juju/juju-gui#2554]
<img width="518" alt="screen shot 2017-03-03 at 09 12 23" src="https://cloud.githubusercontent.com/assets/479384/23545048/8d43f7a8-fff1-11e6-9aac-61b3d9530587.png">
I'm sorry I let this happen.

**Comment by Lukewh** [comment]
<img width="486" alt="screen shot 2017-03-03 at 09 26 34" src="https://cloud.githubusercontent.com/assets/479384/23545526/9d9eb7c6-fff3-11e6-8700-91a73f758214.png">
Not sure if something like this makes sense

**Comment by anthonydillon** [comment]
Seems like the best solution to me. Moving the help icon would be
confusing.

**Comment by Lukewh** [comment]
Also think the help icon should still be available in store/ search.

**Comment by spencerbygraves** [comment]
The position of the help icon and search box is changing as a result of #2572.

I'd rather find a solution for this as part of that work, rather than going with the fix above.

**Comment by spencerbygraves** [comment]
Or, until that work is done, just move the help icon along 10px?

![image](https://cloud.githubusercontent.com/assets/9105999/23748216/8fb2c5c8-04ba-11e7-88a3-9b0d3263984d.png)

And can we remove the horizontal line between the search box and the bigger box underneath?
