### ISSUE TITLE
I don't know my rights

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#2556]
From https://github.com/CanonicalLtd/jujucharms.com/issues/416

When I look at a model on a canvas, I can't tell what access rights I have. Am I admin? Am I read-only?

**Comment by frankban** [comment]
Hey @abentley thanks for reporting. Is the sharing icon (near import/export buttons) not good/apparent enough for knowing your rights?

**Comment by abentley** [comment]
It is not apparent enough.  I didn't want to share the model, I wanted to find out what my rights were.  I didn't think that sharing would show rights.  Usually a sharing icon just provides a list of social networks and messaging options.  I never even tried it.

**Comment by frankban** [comment]
Ok so we need to figure out a more apparent way to comunicate this.

**Comment by Lukewh** [comment]
Something next to the model in the breadcrumb as that's the exact point of access level imo. Will discuss with design too.

**Comment by frankban** [comment]
The design looks good thanks! So now we should be ready to implement that.
