### ISSUE TITLE
Investigate issues accessing shared models

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#2557]
It seems we might have some issues when accessing a shared model with not enough privileges.
See https://github.com/CanonicalLtd/jujucharms.com/issues/415
@bac How did you share your model with @abentley ? What permissions did you grant to him?

**Comment by hatched** [comment]
@frankban I also had the same issue with @bac's model. It appears to be an issue with the read permission and the modelinfo call

**Comment by frankban** [comment]
Fixed this on juju-core, which was wrongly requiring write access for users making the Client.ModelInfo API call.
See https://github.com/juju/juju/pull/7073
