### ISSUE TITLE
GUI shows false information while loading

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#2559]
Maybe we should use the spinner while switching.

From https://github.com/CanonicalLtd/jujucharms.com/issues/411

I click on a model. It takes a few seconds to load. While it's loading, it calls it "untitled-model", and says it has 0 applications, 0 machines.

It should not show incorrect information while it is loading. Instead, it could show that it is loading.

**Comment by hatched** [comment]
Thanks to the UI changes @kadams54 made, this issue is resolved.
