### ISSUE TITLE
No confirmation when uploading GCE credentials json file

### ISSUE THREAD

**Issue by bac** [juju/juju-gui#2561]
This is the presentation *after* selecting a credentials file to upload.

<img width="993" alt="screen shot 2017-03-03 at 8 45 41" src="https://cloud.githubusercontent.com/assets/617845/23551662/2c83d3b4-ffee-11e6-84f2-6803a240ecd3.png">

It is unchanged from the initial view. There should be some indication that the file has been selected, displaying the filename would be good.

**Comment by hatched** [comment]
This is resolved in GUI 2.4.3 which hasn't quite made it to jujucharms.com yet. Thanks for the issue though.
