### ISSUE TITLE
Automatic login to charmstore is intermittently failing

### ISSUE THREAD

**Issue by jaycee** [juju/juju-gui#2564]
Periodically on login to jujucharms.com or staging.jujucharms.com, after gui login completes, I have seen that I am not logged into the charmstore.

**Comment by elvirafigueras** [comment]
Any updates on this?
![screen shot 2017-03-28 at 11 52 01](https://cloud.githubusercontent.com/assets/12827541/24402312/df59b06a-13af-11e7-8668-e77d5aec68a0.png)
It shows up in @Lukewh's profile too but not in @spencerbygraves

**Comment by hatched** [comment]
@elvirafigueras it's in progress.
