### ISSUE TITLE
Showing credentials picker when making post-deploy changes.

### ISSUE THREAD

**Issue by bac** [juju/juju-gui#2565]
Say I've deployed a model...

and then I make some config changes and hit the 'Commit changes (n)' button.  The next page has a cloud credentials picker.

<img width="1156" alt="screen shot 2017-03-03 at 11 36 38" src="https://cloud.githubusercontent.com/assets/617845/23557412/5e048754-0006-11e7-9052-408689d49cc8.png">

Two things:
- The picker really shouldn't be there.  You can't change credentials after the initial deploy.
- The picker isn't even showing the credentials that are currently in use.

**Comment by huwshimi** [comment]
At some point in the past you were able to change the credentials you used to deploy the changes, has this changed? Maybe @urosj remembers the details, I think he requested it to work like that.

**Comment by frankban** [comment]
My understanding is that the deploy call is done by the currently logged in user, and it's not possible to provide additional credentials when deploying application.
