### ISSUE TITLE
Destroying a model in profile view doesn't update model status until you click "Destroy model" a second time

### ISSUE THREAD

**Issue by jaycee** [juju/juju-gui#2566]
From https://github.com/CanonicalLtd/blues_browser/issues/1442:

Upon clicking destroy model, the model remains in the model view until you click destroy model again. Then the status message of it being destroyed is displayed rather than an option to manage the model.

![](https://cloud.githubusercontent.com/assets/4275819/20502664/13f326a0-b00d-11e6-9040-b878dd49eb21.gif)

**Comment by kadams54** [comment]
@hatched's theory is correct; it takes a moment or two for the delta to come back and trigger a re-render, resulting in the "[model] is being destroyed" message being shown. This issue is really about providing better feedback to the user in the interim.
