### ISSUE TITLE
Failed deployments leave gui in bad state

### ISSUE THREAD

**Issue by jaycee** [juju/juju-gui#2568]
From https://github.com/CanonicalLtd/blues_browser/issues/1451:

A failed deployment can leave the gui in a bad state, showing models created w/o deployed services &c.

![](https://cloud.githubusercontent.com/assets/4275819/20540810/9f2cbb76-b0c8-11e6-9b43-993d93b13683.png)

![](https://cloud.githubusercontent.com/assets/4275819/20540741/5a592ef8-b0c8-11e6-9963-842e749ee410.png)

**Comment by hatched** [comment]
Because the GUI completes a number of actions in order it's possible that some of these tasks in the flow fail. At which point it does not go back and undo items it's already completed. This is expected.
