### ISSUE TITLE
Cannot remove failed application deployment

### ISSUE THREAD

**Issue by jaycee** [juju/juju-gui#2569]
From https://github.com/CanonicalLtd/blues_browser/issues/1454:

Once an application has failed to deploy, trying to remove it results in errors; this may be a result of the gui and the controller getting out of sync.

**Comment by frankban** [comment]
@nskaggs do we have a way to reliably reproduce this?

**Comment by hatched** [comment]
Closing this as we are no longer able to reproduce. If it still can be, feel free to re-open with reproduction steps.
