### ISSUE TITLE
storefront authentication failure

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#2571]
Being on my profile page, after a while being logged in, when refreshing the page I find myself logged out from the storefront. So I go ahead and log in, and I it succeeds, as I see my profile in the GUI, even if most of the times I am not logged into the charm store (bug https://github.com/juju/juju-gui/issues/2564). The problem is, if at this point I refresh I am still anonymous on the storefront side (even if I am logged into the GUI).

**Comment by jaycee** [comment]
I think this should be resolved by https://github.com/juju/juju-gui/pull/2728

**Comment by jaycee** [comment]
It looks like this has been resolved; if we see this problem again we can reopen.
