### ISSUE TITLE
Access to profile and account from from canvas

### ISSUE THREAD

**Issue by cassiocassio** [juju/juju-gui#2572]
1. The logged-in user needs to access their own [profile page](https://github.com/CanonicalLtd/juju-design/issues/184) whilst looking a one of their own models.
(currently by clicking on their username, top-left)

2. The logged-in user needs to access their  profile whilst looking at a model shared by another user.

In both cases:

3. the logged in user needs to be able to access their [account page](https://github.com/CanonicalLtd/juju-design/issues/185) 

4. They need to able to log out.

Solution sketch:

- Pull down menu. Profile and Account options. 
- separator line
- Logout choice

in (1) the menu pulls down from a person icon in box, sized to match the help and other icon boxes.
- We DON'T SHOW the user name to avoid repeating the name already  

in (2) the menu pulls down from a (person icon + user name)
- We DO SHOW the user name and  icon to _distinguish_ from the model-sharing user

![clara profile and account menu - two versions](https://cloud.githubusercontent.com/assets/4593556/23630312/47df7a52-0280-11e7-9f70-14013f57a19b.JPG)

**Comment by ClaraLavina** [comment]
# SCENARIO 1: Same user & model owner

## Breadcrumb
**O Juju / clara.lavina / model_name1 ⌄** 

- O Juju - Takes user to his profile. Aim to take user to homepage in the future.
- clara.lavina - Takes user to his profile.
- model_name1 ⌄ - Dropdown with models the user has access to.
Your models 
Shared with you 
[Button] Create new  

## Menu button
Icon only (user can easily understand is about him)

- Profile
- Account
- Logout


# SCENARIO 2: Different user & model owner

## Breadcrumb
**O Juju / cassiocassio / model_name1 ⌄** 

- O Juju - Takes user to his profile. Aim to take user to homepage in the future.
- cassiocassio - Takes user to model owner profile.
- model_name1 ⌄ - Dropdown with models the user has access to.
Your models 
Shared with you 
[Button] Create new  

## Menu button
Icon + user name (so user can easily understand is different to owner in the breadcrumb)

- Profile
- Account
- Logout

**Comment by cassiocassio** [comment]
Martin waves at @spencerbygraves 
@ClaraLavina found https://www.dropbox.com/work/00_web_team/jaas.io/new-jaas-icons?preview=user_24.svg

Which is enough to hack this together. But an actual visualisation from your good self would be excellent.

What's your opinion about the re-ordering of the search and help fields?

I'm guessing that grouping the person and help icons together will neater.

**Comment by spencerbygraves** [comment]
**1. Same user and model owner**
![image](https://cloud.githubusercontent.com/assets/9105999/23712761/c060f9f0-041b-11e7-8c18-9076a80551d3.png)

**2. Different user and model owner**
![image](https://cloud.githubusercontent.com/assets/9105999/23712824/f08cce7e-041b-11e7-9703-b4c6bd1f2bbb.png)

**Comment by mitechie** [comment]
This will address issues #2606 and #2603 

Some feedback:

- I'd change "Create a new model" to "Start a new model" as it doesn't create it and just starts at an empty unnamed canvas correct?

- Do we have a clear distinction between Profile and Account? Those words tend to be interchangeable and I'm concerned they're not distinct enough to end users. 

- I'm very concerned that with the drop down based off the model name field that the listing should actually be different when clicked. That looks like "list the files in this folder" which for /clara folder would be a diferent list than the /cassiocassio folder.

**Comment by spencerbygraves** [comment]
@mitechie Yes you're right about the dropdown, I'll update it for cassiocassio. Thanks.

**Comment by ClaraLavina** [comment]
Great @spencerbygraves thank you! Just a couple of things, the model owner name in the breadcrumb must be underlined, and the models I own should not have _clara/_ in the model dropdown, just the ones shared with me and I'm not owner.

Answering to @mitechie:
1. Agree on "Start a new model" button

2. Profile covers the models you have access to, charms and bundles, budgets and current/past spends. Account has your payment and contact details, T&C you accepted and credentials mgmt.
I totally agree those two terms need a bit of rewording as it could be very confusing.

3. Models dropdown shows always the models you have access to and is always the same, regardless of the user name [/clara or /cassiocassio]. We definitely can explore how to show this is more obvious to the user.

**Comment by mitechie** [comment]
Note that we have to be careful. When you click search the box around the input for search expands and touches/overlaps with the help button in an odd way. We should make sure the new designs don't replicate this behavior to the right-hand side as it does today on the left hand side. 

![selection_002](https://cloud.githubusercontent.com/assets/75915/23714657/0f0ab646-03f8-11e7-974c-42857e873b7d.png)

**Comment by ClaraLavina** [comment]
@mitechie  this has been filed as a bug in another issue

**Comment by ClaraLavina** [comment]
@mitechie https://github.com/juju/juju-gui/issues/2554

**Comment by spencerbygraves** [comment]
**1. User**
![image](https://cloud.githubusercontent.com/assets/9105999/23716836/8a585606-0429-11e7-98c7-f4c45df3fa2a.png)

**2. Different user**
![image](https://cloud.githubusercontent.com/assets/9105999/23716868/9c49e6c2-0429-11e7-8b28-fab315ca2f12.png)

**Comment by frankban** [comment]
This has been implemented.

**Comment by spencerbygraves** [comment]
Hi @frankban I'm going to reopen this issue as it's the model switcher that has been done (#2573), but not the profile part shown here. Is that right?

**Comment by elvirafigueras** [comment]
+ remove choose a model title too :)

**Comment by hatched** [comment]
@spencerbygraves @elvirafigueras can you elaborate on what work is still necessary and was not completed in the GUI 2.4.4 release?

**Comment by frankban** [comment]
I think it's the menu on top right with the profile and account links?

**Comment by elvirafigueras** [comment]
@hatched @frankban Has the menu on the top right been done? If so, we can close this issue.

**Comment by frankban** [comment]
No, we don't have that yet, you are right. Good catch Elvi.

**Comment by elvirafigueras** [comment]
it was @spencerbygraves's hawk eyes :)

**Comment by hatched** [comment]
Haha, thanks for clearing that up :)

**Comment by spencerbygraves** [comment]
Designs added to code - https://github.com/CanonicalLtd/juju-design/tree/master/Canvas

**Comment by frankban** [comment]
The menu on the top right is now done.
