### ISSUE TITLE
Model-switching menu in canvas

### ISSUE THREAD

**Issue by cassiocassio** [juju/juju-gui#2573]
allied to #2572 

Allow the logged-in user to switch the canvas view to another model

Three cases:

1. User has exactly one model. Menu only shows New Model button.
2. User has at least two models, only created by themselves. 
- list models
- show New model button
3. User has access to their own models, and at least one model created and shared by another user.
- show "Your models" and a list of their stuff
- show "Shared with you" and a list of namespaced models

see sketch

![img_5892](https://cloud.githubusercontent.com/assets/4593556/23630833/0f97d4bc-0282-11e7-84db-54d972c99114.JPG)

**Comment by spencerbygraves** [comment]
I'm not sure of the need to have the titles for your and shared models. In these examples I have also removed 'choose a model' which is present in #2572. What do we think?

![image](https://cloud.githubusercontent.com/assets/9105999/23747269/f39a10ea-04b6-11e7-8c8c-9c43734395cb.png)

**Comment by elvirafigueras** [comment]
I think it's best to provide easy & quick access to the models you visit most often, hence not organising them in the two groups and just having them listed in the order of most recently viewed works better. 

Having the owner's name should be enough for a user to differentiate between the ones you own and the ones you don't.

Also agree with removing choose a model title.
