### ISSUE TITLE
Wrong breadcrumb when sharing a model with Read-only permission

### ISSUE THREAD

**Issue by ClaraLavina** [juju/juju-gui#2576]
To replicate:
- Ask someone to share a model with you with read-only access
- Access to model
- Breadcrumb shows your name, not owners name. Also the correct name of the model does not appear.

<img width="1266" alt="screen shot 2017-03-07 at 09 31 16" src="https://cloud.githubusercontent.com/assets/22299251/23665435/06aa8632-031e-11e7-9fc6-028b8527a8fe.png">

**Comment by ClaraLavina** [comment]
Tested with Chrome Version 56.0.2924.87 (64-bit)

**Comment by frankban** [comment]
This bug is related to https://github.com/juju/juju-gui/issues/2557 but it actually provides a way to dupe, so thanks for reporting Clara! Closing this one here.
