### ISSUE TITLE
username in breadcrumb is not clickable when new account

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#2582]
Moved from https://github.com/CanonicalLtd/jujucharms.com/issues/424

My username in this screenshot is not clickable in my /login page. Using another account with a model listed it is so something is not consistent. 

![selection_001](https://cloud.githubusercontent.com/assets/75915/23678176/039fb2c2-0351-11e7-9d14-f94f15336a4b.png)

**Comment by kadams54** [comment]
@mitechie This problem seems to be resolved; can you confirm?
