### ISSUE TITLE
openstack should not be one of the big defaults for the search drop down

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#2587]
It's going to be rare for folks to be interested in deploying openstack on GCE/AWS/Azure and having it take up that valuable real-estate seems like a waste. 

Potential proposals would be:

CI/CD 
Prometheus/telgrad/grafana for monitoring

Since it goes to "view bundles" maybe there's a workflow tools that include both of the above? ^

**Comment by huwshimi** [comment]
This one needs some design work before implementation.

**Comment by frankban** [comment]
Do we have a resolution for this? Should openstack stay? Should it go?

**Comment by spencerbygraves** [comment]
@frankban there's a discussion over here - https://github.com/CanonicalLtd/juju-design/issues/196

**Comment by frankban** [comment]
Any resolutions on this yet?

**Comment by frankban** [comment]
Deferring this again...

**Comment by mitechie** [comment]
I'd like that in JAAS we just remove the OS one and focus on the two that are there. They're the big dogs in our portfolio. 

Down the road I think something like the ES stack might be worth highlighting but there's work to be done there to make sure it works everywhere, has a solid readme, etc.

**Comment by cassiocassio** [comment]
@mitechie Q to clarify: you think that logged-in JAAS users should not see OS, but that non-JAAS other users should see the three?
