### ISSUE TITLE
"model name" is duplicated in the deployment flow. 

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#2589]
See both the heading and the field have the same strings there. 
![selection_003](https://cloud.githubusercontent.com/assets/75915/23680312/c7d3affc-0358-11e7-83e9-12fd3c73f169.png)

**Comment by cassiocassio** [comment]
Noted. Not like that in the next wireframe.

**Comment by frankban** [comment]
Assigning to Luke, maybe for a quick fix before new design and release?
