### ISSUE TITLE
title'ing of input fields are inconsistent

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#2592]
In the credential name there's a upper title that says "Credential Name" but in the actual keys, there's no title but instead the name is in the body of the input. 
![selection_006](https://cloud.githubusercontent.com/assets/75915/23680734/4d00ced4-035a-11e7-88a2-bcadbab23bcb.png)

**Comment by mitechie** [comment]
I see that this is actually some sort of magic animated thing that depends on if the field has a value in it or not. Since some fields have a default value it's not obvious at all.

**Comment by kasiag** [comment]
adding @cassiocassio

**Comment by spencerbygraves** [comment]
We currently use float label, but the new DF designs will look at this.
