### ISSUE TITLE
cannot click on add credential, console error

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#2594]
In the console I see:

Unable to add credential bad request: "cloudcred-aws_rick-harding+guibot@external_myaws" is not a valid cloudcred tag

I got no notification to the UI that there was an issue and that this failed at all.

**Comment by bac** [comment]
The GUI has a bug that needs to be fixed in that it is eating the error.

The credential name should be valid, so the underlying error is in juju/names. It has been reported at https://bugs.launchpad.net/juju/+bug/1671915
