### ISSUE TITLE
Read only access - Replace "Commit changes" button

### ISSUE THREAD

**Issue by ClaraLavina** [juju/juju-gui#2595]
For models where I only have Read only access, the "Commit changes" button should say "Read only" and keep being disabled.

@spencerbygraves we could maybe change button style here. Any ideas?

The aim of this button in the future is to have the option to request access for the user to the model.

![read only model](https://cloud.githubusercontent.com/assets/22299251/23682219/542b5b4a-0358-11e7-9c49-9095e5448fa5.jpg)

**Comment by spencerbygraves** [comment]
The last design work done on this can be seen here - https://github.com/CanonicalLtd/juju-design/issues/110

There is another issue for this here - https://github.com/juju/juju-gui/issues/2477

**Comment by frankban** [comment]
@spencerbygraves good catch, closing this in favor of the other bug.
