### ISSUE TITLE
Open port ranges aren't shown correctly, makes GUI hang.

### ISSUE THREAD

**Issue by galgalesh** [juju/juju-gui#2596]
The[ Eclipse Che charm](https://jujucharms.com/login/eclipse-che) exposes the port range `32768-65535/tcp`. This range is shown correctly in the cli, but the GUI shows each port individually. Clicking on the eclipse-che/0 unit hangs the GUI for ~10 seconds while the GUI generates >30.000 open port links.

The Charm needs that many exposed ports, otherwise the Charm won't be accessible in a public cloud.

Juju CLI:

```
Model      Controller  Cloud/Region   Version
dev-model  jujucharms  aws/us-east-1  2.0.3

App          Version  Status  Scale  Charm        Store       Rev  OS      Notes
eclipse-che           active      1  eclipse-che  jujucharms    0  ubuntu  

Unit            Workload  Agent  Machine  Public address  Ports                     Message
eclipse-che/0*  active    idle   0        54.84.173.104   8080/tcp,32768-65535/tcp  Ready (eclipse/che)

Machine  State    DNS            Inst id              Series  AZ
0        started  54.84.173.104  i-00c7c62a2b8e3499e  xenial  us-east-1b

```

Juju GUI: 

![image](https://cloud.githubusercontent.com/assets/1492981/23700077/0505ca06-03f2-11e7-90d0-d906fbce64cc.png)

**Comment by frankban** [comment]
I believe we have the port range information on the mega-watcher, and there is surely area for improvement here. Thanks for reporting!
