### ISSUE TITLE
How do I switch user?

### ISSUE THREAD

**Issue by galgalesh** [juju/juju-gui#2597]
I haven't found a way to switch user in the Juju GUI at jujucharms.com.

If I logout and log back in, I'm logged in as the same user, I have no way to switch user.

**Comment by frankban** [comment]
Yes we are thinking about adding the ability to switch between users. In the meanwhile, the work around is either manually logging out from usso or authenticate as a different user in another browser/incognito mode. We are currently focusing on polishing the single user experience.
