### ISSUE TITLE
Show workload version in the GUI

### ISSUE THREAD

**Issue by galgalesh** [juju/juju-gui#2600]
Workload version states what version of the application is installed. (different from charm revision).

This info is shown in the CLI but not in the GUI

**Comment by kasiag** [comment]
adding @cassiocassio

**Comment by cassiocassio** [comment]
Can you get a good CLI example of a workload version?

<img width="1383" alt="revisions but not versions" src="https://cloud.githubusercontent.com/assets/4593556/25856166/1a9066c2-34cd-11e7-9c1c-5070856bd2f4.png">

**Comment by galgalesh** [comment]
The empty "Version" collumn in your screenshot shows the workload version (if the Charm sets it). The [postgresql charm](https://jujucharms.com/postgresql/148) sets workload version. 

It gets set with `hookenv.application_version_set(...)`

**Comment by frankban** [comment]
This needs a change in juju-core, as the workload version is not currently included in the mega-watcher to be consumed by the GUI. We'll make that change, but the feature will not be available until subsequent core release.

**Comment by frankban** [comment]
I proposed the Juju change at https://github.com/juju/juju/pull/7563

**Comment by frankban** [comment]
The workload version will be included in the new status pane. A preview version of the status pane will be included in the next 2.9.0 release.

**Comment by frankban** [comment]
This is now deployed to production.
Future work could also provide this information in a more integrated way in the inspector, but for now the status pane should be good enough.
