### ISSUE TITLE
Too-long line in search box

### ISSUE THREAD

**Issue by makyo** [juju/juju-gui#2601]
So trivial I had to make a 'trivial' label just to file it. The line between the search box and the magnifying glass icon is too tall.

<img width="304" alt="untitled-model_-_juju_gui" src="https://cloud.githubusercontent.com/assets/303761/23710188/719b3900-03e1-11e7-858f-e5369faf86f4.png">

**Comment by Lukewh** [comment]
Fixed with https://github.com/juju/juju-gui/pull/2613
