### ISSUE TITLE
credential name shown to me in the DF makes no sense to me

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#2604]
I created a model from the cli and it grabbed my credential. Now in the UX I see the name in the DF is "aws_rharding@external_personal"

I don't know what credential that is and it doesn't mean anything to me. It's very confusing verifying what's being used on my new model.

**Comment by frankban** [comment]
Yes, that's how the credential is called in Juju, and we should provide a more human friendly name (in the example case I guess `personal` would be good enough).

**Comment by mitechie** [comment]
Yes, when I added the model from the CLI the output was that it was "using your cached credential 'personal'...
