### ISSUE TITLE
profile in my model list doesn't make sense

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#2606]
If the link with the username in the breadcrumbs isn't an obvious enough link there maybe we should update that vs putting the profile link in a drop down of model names.

**Comment by spencerbygraves** [comment]
@mitechie If you just had a look at the designs here - https://github.com/juju/juju-gui/issues/2572, that profile button was a mistake, I've updated it to 'create new model'

**Comment by mitechie** [comment]
Thanks @spencerbygraves, I'll hush and look forward to #2572
