### ISSUE TITLE
gisf login postback code has no error handling

### ISSUE THREAD

**Issue by jaycee** [juju/juju-gui#2608]
When the gisf login postback fails, we blithely continue executing other gisf related login code.

We should abort login entirely, and redirect to root with an error message.

**Comment by frankban** [comment]
How to dupe this?

**Comment by jaycee** [comment]
I think there's a good chance that with the changes in https://github.com/juju/juju-gui/pull/2728 this is resolved. The only way for it to occur would be for the gisf callback to execute after a failed login, so no discharge token. But now we execute this as *part* of login, so if login didn't properly complete we're never going to get to the postback code.

**Comment by jaycee** [comment]
This has been resolved.
