### ISSUE TITLE
Store front search results display when logged in

### ISSUE THREAD

**Issue by spencerbygraves** [juju/juju-gui#2615]
Log in and view all charms via search, the results are shown in the GUI. If you refresh this page the results are then shown in the storefront.

**Comment by frankban** [comment]
Thanks for reporting! This is another effect of the login issues we are fixing. Therefore I am closing this here.

**Comment by jaycee** [comment]
Thanks @spencerbygraves; while this looks a lot like a login/logout issue, it's actually from improper route handling. We're now tracking this at https://github.com/CanonicalLtd/jujucharms.com/issues/428
