### ISSUE TITLE
cannot navigate when uncommitted changes exist 

### ISSUE THREAD

**Issue by jamesbeedy** [juju/juju-gui#2624]
Clicking "cancel" or "continue" both lead to the same result here. I can't seem to navigate away from the model.

![screen shot 2017-03-09 at 10 41 14 am](https://cloud.githubusercontent.com/assets/5590546/23765101/e85c2940-04b4-11e7-814b-5f7fa3eef5a2.png)

**Comment by Lukewh** [comment]
@jamesbeedy what steps did you take before trying to navigate away?

**Comment by hatched** [comment]
There have been a number of releases since this issue was reported and I'm not able to reproduce. If you're able to provide reproduction steps feel free to re-open this issue.
