### ISSUE TITLE
charm URL above the "Add to Model" button needs to change

### ISSUE THREAD

**Issue by anastasiamac** [juju/juju-gui#2625]
Related to https://bugs.launchpad.net/juju/+bug/1584193

As per comment 14 in the bug, old style "cs:" format needs to be updated once Juju change took place.

**Comment by frankban** [comment]
Thanks Anastasia, good catch!

**Comment by frankban** [comment]
Postponing to Garak as this functionality is not ready in Juju yet.

**Comment by frankban** [comment]
@huwshimi Why is this blocked?

**Comment by huwshimi** [comment]
@frankban from your comment above "Postponing to Garak as this functionality is not ready in Juju yet."

**Comment by frankban** [comment]
Right ;-)
