### ISSUE TITLE
'juju logout' via the CLI confuses an extant GUI session

### ISSUE THREAD

**Issue by bac** [juju/juju-gui#2627]
While logged into the GUI I used `juju logout` on the CLI.  Subsequently using the GUI worked up to the point I tried to deploy a new model. The console showed errors about an expired macaroon and then the GUI retried indefinitely.

Showed the issue in real time to @hatched 

Logging out via the GUI and starting my model from scratch then succeeded.

**Comment by frankban** [comment]
Possibly related to all other logout issues we are having.

**Comment by bac** [comment]
I tried to reproduce this issue and was unsuccessful. Steps

* Logged out via cli.  
* Created a new model in gui and deployed a charm.  
* `juju login` in the CLI and was presented with the new model.

Seems to be working as expected now.
