### ISSUE TITLE
Link to GCE credentials broken, JSON import throws error

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2631]
Moved from: https://github.com/CanonicalLtd/jujucharms.com/issues/434

https://jujucharms.com/i/deploy mentions

The key information can be downloaded as a JSON file, or copied from https://console.developers.google.com/project/apiui/credential.

This link seems to be outdated:
"URL not found
We couldn't find what you were looking for. Try one of the links below."

What I find is

https://console.developers.google.com/apis/credentials

I tried downloading a JSON file manually for deployment, and get:

"cannot create model: cannot create model: failed to open environ: json: cannot unmarshal object into Go value of type string"

**Comment by frankban** [comment]
Could you please describe the steps leading to the "cannot create model: cannot create model: failed to open environ: json: cannot unmarshal object into Go value of type string" error?
This seems to come from juju itself, not beeing able to decode the JSON content you provided.

**Comment by frankban** [comment]
So, assuming the JSON error, as returned by Juju, is due to a badly formatted json file, I am going to close this. Feel free to reopen if the error is returned by a correct JSON.
