### ISSUE TITLE
Login bug in GIJoe

### ISSUE THREAD

**Issue by bac** [juju/juju-gui#2637]
Did the following in both PR 2635 and develop:
```
juju bootstrap aws qa-2635 --config identity-url=https://api.jujucharms.com/identity
juju upgrade-gui dist/jujugui-2.4.3.tar.bz2
```

```
$ juju gui --no-browser
GUI 2.4.3 for model "admin/default" is enabled at:
  https://54.144.146.35:17070/gui/u/admin/default
Your login credential is:
  username: admin
  password: ca13ebab0f98923f4b9cf3dd0301aa36
```

When I go to `https://54.144.146.35:17070/gui/u/admin/default` the GUI loads and I get the login box but it has redirected to `https://54.144.146.35:17070/gui/login/u/admin/default`.  After logging in via SSO it returns to `https://54.144.146.35:17070/gui/login/u/admin/default` and a blank page. Reloading returns this in the page: 
```
{"error":{"message":"cannot open state: unknown model: \"login\"","code":"model not found"}}
```

According to @hatched the correct URL should be `/gui/u/admin/default/login`

**Comment by bac** [comment]
OK, all was well when tested with GISF...so not a big deal after all?

**Comment by frankban** [comment]
Redirecting to https://54.144.146.35:17070/gui/login/u/admin/default and displaying a blank page after logging in via USSO seems like a bug to me, but I cannot reproduce. Do you have permissions on at least one model for the external user?

**Comment by bac** [comment]
I re-ran the test and could not replicate the problem using

```
juju bootstrap aws issue-2637 --config identity-url=https://api.jujucharms.com/identity
juju grant bac@external login && juju grant bac@external read default
```

Note this is different from yesterday when I simply granted
```
juju grant bac@external admin default
```
