### ISSUE TITLE
add credentials text is big and not that helpful

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#2648]
During the deployment flow when you select a cloud and go to enter credentials we should leverage existing documentation for that material especially since we know what cloud they're adding for. 

https://jujucharms.com/docs/stable/credentials
https://jujucharms.com/docs/stable/help-aws
https://jujucharms.com/docs/stable/help-azure
https://jujucharms.com/docs/stable/help-google

vs the current material (GCE for example)

    The GCE provider uses OAauth to Authenticate. This requires that you set it up and get the relevant 
    credentials. For more information see  https://cloud.google.com/compute/docs/api/how-tos/ 
    authorization. The key information can be downloaded as a JSON file, or copied from  
    https://console.developers.google.com/project/apiui/credential

**Comment by frankban** [comment]
Do you mean that we should link those pages or provide more information based on the contents of those pages?

**Comment by evilnick** [comment]
I would suggest linking to the pages, as that way it gets maintained.

**Comment by mitechie** [comment]
Yes, the idea is to link to the pages as they can provide additional context, screenshots, etc and be much more helpful while not bogging down the page with a bunch of text for folks that know what they need/etc. I think we can do a better job of pulling that together here and clean up the UX a bit.

**Comment by frankban** [comment]
Sounds good to me.
