### ISSUE TITLE
Metadata field formatted in jujucharms.com but not in GUI

### ISSUE THREAD

**Issue by galgalesh** [juju/juju-gui#2651]
The metadata field is formatted in the non-JaaS `jujucharms.com` store, but not in the Juju GUI.

# non-JaaS:

![image](https://cloud.githubusercontent.com/assets/1492981/24000666/2de06e3e-0a5c-11e7-912d-a5ef749f7b03.png)

# Juju GUI

![image](https://cloud.githubusercontent.com/assets/1492981/24000688/44d233fc-0a5c-11e7-876e-8876fa42c752.png)

Link: https://jujucharms.com/u/cmars/mattermost/16

**Comment by frankban** [comment]
Good catch, thanks for reporting!
