### ISSUE TITLE
Import/export button initially present in the profile page

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#2684]
I login and get to my profile 
![screen shot 2017-03-28 at 12 02 11](https://cloud.githubusercontent.com/assets/12827541/24402009/a5cadc30-13ae-11e7-9280-b5d78beaed86.png)

All good so far (apart from the "Login to the charm store" button). 
However, if I click on either my username or the Juju logo, the import export icons disappear and the hover state of my username gets no underline.

![screen shot 2017-03-28 at 12 02 38](https://cloud.githubusercontent.com/assets/12827541/24402010/a5e0a5a6-13ae-11e7-89d2-2df2bf0a9e9a.png)

Hmmmm...?

**Comment by hatched** [comment]
@elvirafigueras was this on jujucharms.com?

**Comment by frankban** [comment]
Ok I confirmed the issue on jujucharms.com. As Elvira mentioned, we have two problems here:
- the import/export button are present when you originally land to your profile, and they shouldn't;
- a style problem when hovering the user name in the breadcrumb (no underline displayed).

**Comment by kadams54** [comment]
@frankban and I were unable to replicate on jujucharms.com; I suspect this issue was resolved by #2656, which recently went into production.
