### ISSUE TITLE
You can share with users that don't exist

### ISSUE THREAD

**Issue by Lukewh** [juju/juju-gui#2686]
Sharing with `0-luke@external123456677` works, so does `0-luke@externalarandomstringofcharacters`. We should probably do strict matching.

<img width="392" alt="screen shot 2017-03-28 at 11 40 56" src="https://cloud.githubusercontent.com/assets/479384/24406028/c60eba1a-13be-11e7-9969-2b8a659162b3.png">

**Comment by hatched** [comment]
We can only rely on the response from the backend to provide that sort of feedback. It currently doesn't provide this information and won't for the foreseeable future.

**Comment by jrwren** [comment]
This is a security issue. A user could share with an incorrect, nonexisting user name and in the future a different user could create an account with that name, gaining the privilege intended for the original user.

**Comment by frankban** [comment]
@jrwren my impression is that this security check must be done server side. The GUI does not know anything about available domains or whether a user already exists or not. We have a plan of getting the available domains from the idm, but this information is not available yer server side. Security wise, this is not different from any command line "juju grant" invocation, or even "charm grant". Maybe we can warn the user about that possibility? I'd be inclined to close this, what do you think?

**Comment by jrwren** [comment]
Yes, I agree on all points. `juju grant` and `charm grant` should either fix it by checking the controller and/or identity server, or the user should get a warning.

**Comment by frankban** [comment]
Ok, closing this here as we agreed that the check must be done by servers.
