### ISSUE TITLE
State system should accept validators

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2691]
There are a number of places in the GUI where we check that the `state.current` value matches some expected value. Because these state objects are freeform any change to the structure could indirectly break separate parts of the application. 

In an attempt to remedy this the State system should be expanded to accept validators to be registered. This will allow developers to define logic based on the state values and provide and a single place to modify that logic and provide a simple way to rename across the codebase if necessary.

A validator would be a method which would:
- Be available on the state instance.
- Return a boolean value.
- Can be registered with the state system at any time.

Example api:
```JavaScript
// Registering a new validator
state.registerValidator('isNew', state => state.current.root === 'new')

// Using a validator
if (state.validator.isNew()) {
  // The GUI is in a 'new' model 
}
```

**Comment by frankban** [comment]
Why not just adding those validators as functions in centralised place? Where do you see the need for adding a framework for registering validators and then reusing them with an indirect reference, rather than just calling a function? I am not sure that `state.validator.isNew()` is better than `validators.isNew(state.current)`.

**Comment by hatched** [comment]
I don't find the latter API as user friendly. If you already have the state instance you have access to the validators, and because those validators are on the state instance there is no need to pass additional data in as it already has all the necessary data.

**Comment by clagom** [comment]
Is this still relevant?

**Comment by hatched** [comment]
It is, but won't be for the new GUI. Closing.
