### ISSUE TITLE
Sandbox mode is gone. Fix 'make run' output.

### ISSUE THREAD

**Issue by bac** [juju/juju-gui#2710]
In the GUI if you run `make run` you get

```
Starting subprocess with file monitor
Starting server in PID 20877.
serving on http://0.0.0.0:6543
```

Since sandbox mode is gone, hitting that URL will not work. It would be helpful if the output message were changed to give guidance to use guiproxy.

**Comment by hatched** [comment]
This is a good idea @bac 

You are supposed to get an alert when you visit that page https://github.com/juju/juju-gui/blob/e5c0c7987b6484311028fa13843061a2c62a99d4/jujugui/static/gui/src/app/app.js#L2648 but it looks like due to recent changes, there is a typeerror instead.

**Comment by huwshimi** [comment]
In #2749 I've fixed the errors when you visit that URL so you now get the warning. Due to the running process there is no way to output a comment after that URL is printed, but just before that there is:
```
==============================================================
To run the GUI you must point it at a running Juju controller.
The accepted way of doing this is via the GUIProxy project: https://github.com/frankban/guiproxy
==============================================================
```
Hopefully that's enough.
