### ISSUE TITLE
add auto `next` support to login system

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2717]
Now that `next` has been added to state and to the setup. The rest of the login system should populate the `next` state if the user attempts to visit a path but requires authentication.

**Comment by frankban** [comment]
I think we decided that login should not be a state, but a mask that is displayed on top of other states when required, with the exception of a direct navigation to /login itself. This way we don't clutter the state history with login redirections and we can easily handle next. Thoughts?

**Comment by hatched** [comment]
Yeah I believe that is going to be the best case forward. A while back I added the ability to re-dispatch the application without changing state so implementation shouldn't be too difficult.
