### ISSUE TITLE
No way to close account

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#2724]
When you are viewing your account page there is no obvious way to get back to the canvas, the only thing you can do is click on your username to view your profile.

**Comment by frankban** [comment]
Note that the account URL is /account, not /u/{user}/{model}/account. This means that we are actually treating the account page as not something on top of the model canvas. I guess we could have both, but for the time being maybe it is better to just keep it simple (like the profile page)?

**Comment by huwshimi** [comment]
@frankban I discussed this briefly with @urosj yesterday and I think we'll just add a close x for now. This won't match the profile, but the account page is accessed from the user menu which you should be able to do while in a model and then be able to get back to the model.

**Comment by huwshimi** [comment]
@frankban I've seen you've landed some changes to the account page which make it behave more like the profile and less like an overlay, I'm going to put my branch on hold until we figure out what to do.

**Comment by kasiag** [comment]
@spencerbygraves let's keep this in mind when re-doing the account page

**Comment by huwshimi** [comment]
Closing as I don't think this will change.
