### ISSUE TITLE
Logged in users sees different view (no "Latest version", no "Embed this charm", no "Submit bug")

### ISSUE THREAD

**Issue by hloeung** [juju/juju-gui#2726]
When logged into jujucharms.com, there's no options to see latest version nor to embed this charm or submit a bug.

**Comment by hloeung** [comment]
Not logged in - [http://people.canonical.com/~hloeung/G8WwZu1Z.png](url)
Logged in - [http://people.canonical.com/~hloeung/rKgI0nTP.png](url)

**Comment by frankban** [comment]
The "latest revision" bit has been implemented at https://github.com/juju/juju-gui/pull/2736

**Comment by frankban** [comment]
The juju card has been implemented. The submit bug link is present on the right panel.
