### ISSUE TITLE
Wrong name on Kubernetes bundle details page

### ISSUE THREAD

**Issue by spencerbygraves** [juju/juju-gui#2751]
The name should be "The Canonical Distribution Of Kubernetes", as in the store.

https://jujucharms.com/canonical-kubernetes/bundle/21

**Comment by spencerbygraves** [comment]
Also, if you view this bundle in the GUI, copy and paste the URL in a new tab, it shows the store version. But with a different URL if you'd view the bundle in the store.

Hope that makes sense.

**Comment by frankban** [comment]
So you are being logged out when you copy/paste the URL? That could be related to an auth issue that should go away on next release. But what about the "different URL" that you mentioned? What's the difference between the two URLs?

**Comment by spencerbygraves** [comment]
This is all when logged out, but it seemed strange.

The different URL's are:

Store
https://jujucharms.com/canonical-kubernetes/

GUI
https://jujucharms.com/canonical-kubernetes/bundle/21

**Comment by frankban** [comment]
Ok, the two URLs are both valid, and they also show the same entity assuming the most recent stable kubernetes is revision 21. I am still not getting how you ended up with one URL starting from the other. Could you please describe how to dupe that? Thanks!

**Comment by frankban** [comment]
Ah, maybe clicking the search results with and without being authenticated?

**Comment by spencerbygraves** [comment]
When you're not logged in, click Store > View bundles (scroll down) > The Canonical Distribution of Kubernetes. You get this URL - https://jujucharms.com/canonical-kubernetes/ (1)

Still not logged in, click Try the beta > View bundles (in the search overlay) > Canonical kubernetes (search result). You get this URL - https://jujucharms.com/canonical-kubernetes/bundle/21 (2)

Take (2) and paste it into a new tab and you get the page of (1), but with the URL of (2)
