### ISSUE TITLE
Clicking author link doesn't send you to author page.

### ISSUE THREAD

**Issue by galgalesh** [juju/juju-gui#2760]
# What I get

- Clicking the author name in search, searches for that author's name.
- Clicking the author name in charm details page sends you to the launchpad page of the author.

# What should happen

Both links should point to the Charm author page (`/u/<author>`).

Example:

https://jujucharms.com/u/tengu-team/ssl-termination-proxy/0

The `tengu-team` link on this page should link to https://jujucharms.com/u/tengu-team

**Comment by frankban** [comment]
The detail page link has been fixed already at https://github.com/juju/juju-gui/pull/2736 (included in garak, so it will go online probably tomorrow). The link in the search results is a good suggestion, thanks!

**Comment by frankban** [comment]
The link in the search results fix has been proposed at https://github.com/juju/juju-gui/pull/2761 and will be parto of subsequent release.
