### ISSUE TITLE
Inline code in charm description looks very small

### ISSUE THREAD

**Issue by galgalesh** [juju/juju-gui#2765]
The inline code (the word `http`) in the header looks very small.

https://jujucharms.com/u/tengu-team/ssl-termination-proxy/1

![image](https://cloud.githubusercontent.com/assets/1492981/24965160/900dc1d6-1fa3-11e7-950a-8ac2420984b4.png)

**Comment by galgalesh** [comment]
It seems that this issue was mistakenly marked as fixed. PR https://github.com/juju/juju-gui/pull/2779 doesn't address this issue.

@frankban Can you confirm and reopen?

**Comment by frankban** [comment]
@galgalesh I confirm this is fixed but not yet released.
The homn release should be cut today, and, if we don't find any release blockers during our final QA, JAAS will be updated this week.

**Comment by galgalesh** [comment]
Thanks! And is there no way to see what release JAAS is running?

**Comment by frankban** [comment]
There is no easy way to check that currently, but we are working on it as part of https://github.com/juju/juju-gui/issues/2738

**Comment by hatched** [comment]
@galgalesh in the upcoming release you'll be able to view the GUI version by visiting the 'help' from the user dropdown or by hitting `shift+?`

**Comment by galgalesh** [comment]
Sounds great, thanks!

**Comment by frankban** [comment]
This is now live!
