### ISSUE TITLE
juju-gui broken on arm64?

### ISSUE THREAD

**Issue by Cerebus** [juju/juju-gui#2776]
I have a RPi3B cluster and my own custom-built xenial arm64 boot/root disk.  PI 64-bit kernel support isn't complete--some HW accelerations and wifi still don't work--but for my purposes it's functional enough.  

I've installed juju 2.1.2, added a manual cloud, and boostrapped a controller onto the head of the cluster without any problems.  I can deploy charms through the juju client and that appears to work.

The GUI breaks.  I can log in and it displays the application canvas and decorations, but none of the UI elements work--I can't change models, can't inspect the machines or applications list, can't add charms, and can't search the store.  Nothing shows up in the controller logs; breakage is in the browser.  I reproduced this with current Chrome, Safari, and Firefox.  

Attached is a browser log from Chrome 57.0.2987.146.  The GUI logs into the controller fine.  There's an early 404 error for a charm API fetch for a bundle named after my model, but if that's normal behavior then 404 would be expected since the model is empty.  After that the GUI logs into the model fine, but then it throws a TypeError trying to read svgHeight off an undefined object.

I know I'm out on the ragged edge with my system, and I don't expect every charm to work, but I would have expected the GUI to work--or at least, for errors to be server-side, not browser side.

-- T

[192.168.86.50-1492262739764.txt](https://github.com/juju/juju-gui/files/923628/192.168.86.50-1492262739764.txt)

**Comment by hatched** [comment]
Thanks for reporting this issue.

It is possible that the cloud logo renderer falls over when the cloud is not found in the logo list.

**Comment by hatched** [comment]
Hi @Cerebus the latest GUI has been released with this fix.

When bootstrapping you should see that it's downloading the latest GUI (2.5.2). Or if you already have a controller bootstrapped you can run `juju upgrade-gui` then `juju gui` to open it.

**Comment by Cerebus** [comment]
Verified working after upgrade-gui.  Thanks for the quick turn.
