### ISSUE TITLE
Import/Export icons are confusing which to which

### ISSUE THREAD

**Issue by nobuto-m** [juju/juju-gui#2780]
It may be a kind of bikeshed discussions, but at least I mis-recognized "up-pointing arrow"(Export) as "uploading my bundle", and "down-pointing allow"(Import) as "downloading the bundle".
![import_export](https://cloud.githubusercontent.com/assets/4356209/25124733/936f06f0-2467-11e7-94f4-cad81b2a3bab.png)

It's not elegant, but how about rotating icons like below? (Import/Export)
![rotate](https://cloud.githubusercontent.com/assets/4356209/25126374/0c341fc6-246d-11e7-85e0-e1409d5935a4.png)

**Comment by spencerbygraves** [comment]
This has been discussed recently, we added the labels on hover to make it clear which is which.

I think we can close this.
