### ISSUE TITLE
Banner with the login link is too persistent

### ISSUE THREAD

**Issue by urosj** [juju/juju-gui#2781]
In deployment flow, there is no way to close the "popup window" solver, one is not able to finish deployment anymore and return to canvas. 

If back button is used, the overlay says and one can't access profile or model switcher without reloading the page. 

We need an ability to close it so that all the functionality of the GUI stays available.

To reproduce:
- go to /new as anon user
- add something to the canvas
- click deploy
- click login (best in safari or any other browser with popups blocked)
- don't follow the link, try to go back to canvas
- click back in the browser to land somwhere in canvas

**Comment by elvirafigueras** [comment]
@spencerbygraves could you look into this?

**Comment by elvirafigueras** [comment]
@spencerbygraves could you look into this too?

**Comment by elvirafigueras** [comment]
![screen shot 2017-04-24 at 10 40 32](https://cloud.githubusercontent.com/assets/12827541/25331357/a0278eae-28da-11e7-9026-e32f82ae2451.png)

**Comment by spencerbygraves** [comment]
We should use our notification style, as below:

![image](https://cloud.githubusercontent.com/assets/9105999/25332147/60d69b3e-28dd-11e7-921d-99761130fed9.png)

**Comment by Lukewh** [comment]
@spencerbygraves this needs to work on all pages, not just DF so would need to be absolutely positioned (wouldn't push content down) for things like the canvas

**Comment by hatched** [comment]
We also want it to be blatantly obvious. So I don't think that this new style is 'in-your-face' enough.

**Comment by spencerbygraves** [comment]
We have other notification levels if we want to make it bolder, with different colours with icons. In this case you'll also see it appear after you click the button, so I don't think it will be missed. We could possibly fade the page content to give it more prominence too.

We should also make the designs of these two pages consistent.

![image](https://cloud.githubusercontent.com/assets/9105999/25384007/73d69566-29b6-11e7-9666-b2fcb0918d06.png)

**Comment by spencerbygraves** [comment]
I've updated the two pages above to use our notification style. I haven't included the user icon on the logged in page, as the GUI will be shown in the other tab and the instruction is to close this window.

![image](https://cloud.githubusercontent.com/assets/9105999/25530524/78bfd262-2c1e-11e7-9920-91cfcbe18ea0.png)

![image](https://cloud.githubusercontent.com/assets/9105999/25530565/9b256a9c-2c1e-11e7-8d4d-37597fb235c9.png)
