### ISSUE TITLE
 Landscape Dense MAAS: hook failed: "reverseproxy-relation-changed" for landscape-server:website

### ISSUE THREAD

**Issue by richardsith** [juju/juju-gui#2786]
Lab:

All environment has been realised using only Ubuntu 16.04 LTS:

 - 1 VM for MAAS (memory: 8GB, CPU: 1, HDD: 500GB);
 - 1 VM for JUJU GUI (memory: 8GB, CPU: 1, HDD: 500GB);
 - 1 VM for LANDSCAPE (memory: 8GB, CPU: 1, HDD: 500GB);

![screen shot 2017-04-19 at 17 43 49](https://cloud.githubusercontent.com/assets/9977215/25218647/e242fb48-25ab-11e7-9d80-4fc46db200a3.png)

during the deploy of Landscape Dense-MAAS via JUJU GUI I've received this error on juju status :

    hook failed: "reverseproxy-relation-changed" for landscape-server:website

the complete juju status is [here](https://paste.ubuntu.com/24414426/), below the screen on JUJU GUI

![screen shot 2017-04-19 at 17 43 53](https://cloud.githubusercontent.com/assets/9977215/25218648/e245a140-25ab-11e7-8e7a-00778e7002f3.png)
![screen shot 2017-04-20 at 09 29 13](https://cloud.githubusercontent.com/assets/9977215/25218649/e255b5da-25ab-11e7-8bca-b0ac507df968.png)

**Comment by frankban** [comment]
Hey Riccardo,
do you encounter the same failure when deploying from the CLI?
Could you paste the corresponding error as reported by debug-log?
Thanks!

**Comment by richardsith** [comment]
Lets me try that, I need to re-commission the machine and re-deploy that.  The command to use for having the debug-log is maybe that?

`$: juju deploy cs:bundle/landscape-dense-maas-7 --debug`

**Comment by richardsith** [comment]
Done it, but now the error is on postgresql as reported on the picture
![screen shot 2017-04-20 at 11 12 03](https://cloud.githubusercontent.com/assets/9977215/25222986/5a584ddc-25ba-11e7-944a-38acc15900df.png)

anyway the debug-log is too long to paste here or on Ubuntu Pastebin, how can I show you that?

**Comment by hatched** [comment]
@richardsith because you're getting the same issue on the CLI it looks like this is not an issue with the GUI but with the charms themselves. Your best bet there would be to contact the charm authors using the bug links on the charm details pages. 

https://jujucharms.com/landscape-dense-maas/
https://bugs.launchpad.net/landscape-bundles/+filebug
