### ISSUE TITLE
Canvas - Loading

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#2793]
The messages under the progress bar go on in a loop, and it's quite obvious that they don't refer to what is actually happening behind the curtains. Could we show each message for a few more seconds to make sure the user doesn't see it going back to the start of the loop?

![screen shot 2017-04-21 at 14 55 02](https://cloud.githubusercontent.com/assets/12827541/25280691/c40f49c2-26a2-11e7-980b-9de12d9b3742.png)

**Comment by jaycee** [comment]
Or alternatively add more messages.

**Comment by cassiocassio** [comment]
Genuine feedback or more convincing lies ?
