### ISSUE TITLE
Header icons are broken

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2807]
<img width="439" alt="screen shot 2017-04-26 at 3 36 26 pm" src="https://cloud.githubusercontent.com/assets/532033/25458180/2fc5d73e-2a96-11e7-9f13-220c84dc6467.png">

OSX Chrome 58.0

**Comment by Lukewh** [comment]
Where are you seeing this @hatched? This happened for me locally, the make clean-all run dance fixed it for me.
