### ISSUE TITLE
Clicking on the juju card on another site causes /login url to be left

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#2817]
From https://github.com/CanonicalLtd/jujucharms.com/issues/456

I clicked on the card in this blog post: http://spicule.co.uk/devops/git/juju/2017/04/26/gitlab-charm.html

and it caused me to end up with a URL:

https://jujucharms.com/login/u/spiculecharms/gitlab-ssl

The /login should go away and not be part of the url I might mistakenly put into a blog post or share and such.

**Comment by frankban** [comment]
I duped the bug, we should remove the login fragment.

**Comment by huwshimi** [comment]
I wonder if we fixed this with our last release? I just tried it and when I was logged out of jujucharms.com it was fine (to be expected) and when I was logged in I briefly saw the /login url but then it was removed.

**Comment by frankban** [comment]
Cool, then I'll close this!
