### ISSUE TITLE
going to a url keeps routing me back to my profile page

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#2825]
I'm trying to hard enter this url to see if the bundle exists:

https://jujucharms.com/u/paulgear/bundle/ntp-server

Each time I enter that url I seem to go through a login process and land back on my own personal profile page. I'd like to either get a 404 or see the bundle.

**Comment by frankban** [comment]
True, for non-existing entities, it seems that the GUI sometimes redirects to the profile page, and some other times it displays an error. We should make this consistent.

**Comment by huwshimi** [comment]
I was not able to reproduce this bug on develop, is it possible we fixed this? I visited "/u/spiculecharms/gitlab-ssl" and it didn't add /login/.
