### ISSUE TITLE
Profile view model list no longer displays machine count properly

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2831]
The machine count in the model list in the profile view is always 0.

**Comment by Lukewh** [comment]
@hatched can you provide more info - it works for me on `develop`.

**Comment by hatched** [comment]
I was just able to reproduce this using `develop`:
- Using GUIProxy to prod
- Add a single charm to the canvas
- Deploy to GCE us-central
- Wait a while for it to deploy
- Open your profile.

**Comment by huwshimi** [comment]
I can reproduce this on us-central, but not us-east. On us-central the `ModelInfo` call returns an empty array of machines.

**Comment by frankban** [comment]
Yes, this is a problem on the gce us-central1 region. I confirm the controller is not communicating with Jimm properly: try `juju add-model gce-central google/us-central1 && juju deploy wordpress && juju show-model --debug --logging-config trace`. This is not a GUI bug.
