### ISSUE TITLE
Sort and series menus in search are missing arrows

### ISSUE THREAD

**Issue by spencerbygraves** [juju/juju-gui#2860]
**GUI**
![image](https://cloud.githubusercontent.com/assets/9105999/25748803/559af9e8-31a4-11e7-9231-550bc8ef7437.png)

**Store**
![image](https://cloud.githubusercontent.com/assets/9105999/25748816/61edd18e-31a4-11e7-8db7-d652fa00af2f.png)

**Comment by huwshimi** [comment]
I can reproduce this on jujucharms.com, but it looks like we've already fixed this in develop. Please reopen this if it's still an issue after our next release.
