### ISSUE TITLE
z-indexes need revising

### ISSUE THREAD

**Issue by Lukewh** [juju/juju-gui#2866]
There are some odd situations where z-indexes are out of order. The biggest example is when you destroy a model from the profile page and the header appears above the blocker. Moving any of the indexes to fix this problem causes the top right menu's to open behind the profile page.

**Comment by frankban** [comment]
Postponed too many times, this is now the future.

**Comment by clagom** [comment]
Is this still relevant?

**Comment by hatched** [comment]
Nope
