### ISSUE TITLE
Cannot navigate back to search results from deployed model

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2873]
While connected to a model perform a search and then view one of the search results. Now hit the back button. You'll instead get an error about the search results not existing because it's trying to perform a search on the full url.

**Comment by hatched** [comment]
This comment may also be related to this issue: https://github.com/juju/juju-gui/pull/2915#issuecomment-303245889

**Comment by huwshimi** [comment]
This could be a general problem with the search state, if you do a search from your profile e.g. for openstack you'll end with the url. /q/openstack/u/huwshimi but then if you refresh the page you'll end up with the url /q/openstack/u/huwshimi/u/huwshimi and in the search box will be "openstack/u/huwshimi" and there will be a message: "Your search for openstack/u/huwshimi returned 0 results".

I thought we had this issue previously and that we had fixed it...

**Comment by frankban** [comment]
Also, refreshing a search page never works. This is a quite important usability problem.
