### ISSUE TITLE
HTML garbage inserted into inspector when updating values

### ISSUE THREAD

**Issue by jaycee** [juju/juju-gui#2885]
When you enter new config values in the inspector, garbage HTML is showing up in the component:
![2017-05-05-115117_389x570_scrot](https://cloud.githubusercontent.com/assets/26728/25870137/06c9ede4-34d1-11e7-91ff-3cea73e32bfa.png)

**Comment by hatched** [comment]
Related: https://github.com/juju/juju-gui/pull/2863

**Comment by huwshimi** [comment]
Thanks @jaycee this was fixed in #2863.
