### ISSUE TITLE
adding credentials from the account page should start with the cloud picker

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#2888]
Instead it defaults to AWS and I need to change cloud to see other options.

**Comment by mitechie** [comment]
Also the add button isn't styled like other buttons with the black border outline in chrome on macOS?

**Comment by frankban** [comment]
It only defaults to a cloud when it's the only one, like on current staging. Otherwise it starts with the cloud picker. Filed https://github.com/juju/juju-gui/issues/2889 for the add button style issue.
