### ISSUE TITLE
Username is not clickable in banner charm detail page

### ISSUE THREAD

**Issue by galgalesh** [juju/juju-gui#2890]
The username at the top of a charm details page is clickable. (**tengu-team** in the example.)

![image](https://cloud.githubusercontent.com/assets/1492981/25918036/46246bc8-35ca-11e7-9a99-f427d8505fbf.png)

Scroll down and it isn't clickable anymore:

![image](https://cloud.githubusercontent.com/assets/1492981/25918016/350f472c-35ca-11e7-80c2-01a04d52ef83.png)

Test with this url: https://jujucharms.com/u/tengu-team/jupyter-notebook/0

**Comment by frankban** [comment]
Good catch!

**Comment by frankban** [comment]
Is this some kind of z-index problem?

**Comment by Lukewh** [comment]
Good catch @galgalesh. Looks to be because of `pointer-events: none;` for the sticky header @frankban not sure why that was added.

**Comment by frankban** [comment]
@Lukewh thanks for the hint, I'll make that quick change.
