### ISSUE TITLE
Guidance for manually adding AWS credentials out of date

### ISSUE THREAD

**Issue by cassiocassio** [juju/juju-gui#2904]
The link here:

![add aws creds](https://cloud.githubusercontent.com/assets/4593556/26058558/3fb08f60-3976-11e7-9e70-e19edb64e4c6.png)

Takes users to the docs here:

![manual_creds](https://cloud.githubusercontent.com/assets/4593556/26058568/51afe0f8-3976-11e7-84a6-9b3a583a6b1b.png)

But the documentation at AWS console has changed substantially. The guidance is to no longer export root keys.:

<img width="1085" alt="new-creds" src="https://cloud.githubusercontent.com/assets/4593556/26058597/6bb28a1e-3976-11e7-9c6c-7dd331f46299.png">

**Comment by frankban** [comment]
Moved to https://github.com/juju/docs/issues/1852
