### ISSUE TITLE
Add some life to the pending status on the canvas

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2906]
https://codepen.io/anthonydillon/pen/oBBgBa

**Comment by spencerbygraves** [comment]
This hasn't been through a design review. It should be kept in juju-design until it's signed off.

**Comment by hatched** [comment]
It's ok @spencerbygraves it's easy to implement and provides a lot of life to the canvas. If we decide it's terrible later we an just as easily remove it.

**Comment by frankban** [comment]
I guess we need design for this.

**Comment by kasiag** [comment]
designs in progress (parked) can be seen here https://github.com/juju/juju-gui/issues/2906

**Comment by cassiocassio** [comment]
@hatched let's see how the unit mesages in the inspector cover this need - moved to triaged for the moment
