### ISSUE TITLE
store page missing assets

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2907]
Visiting /store you'll see two missing assets:

kubernetes-promo.png
write-your-own.png

**Comment by hatched** [comment]
This does not appear to be reproducible by anyone but me, and only if I use Chrome.

**Comment by huwshimi** [comment]
Could it be some kind of caching issue? I tried this on develop after a clean-all and using a private Chrome browser and could not reproduce.

**Comment by hatched** [comment]
@huwshimi it's very possible, I've got to fetch the logs to investigate. I'll assign to myself

**Comment by huwshimi** [comment]
I get 404s for those images when visit jujucharms.com in a private Chrome window.

**Comment by hatched** [comment]
This has been resolved in the latest GUI release, and the remaining assets not mentioned here are currently being fixed for the next release as a separate issue.
