### ISSUE TITLE
Add 'About this charm' link to the inspector

### ISSUE THREAD

**Issue by spencerbygraves** [juju/juju-gui#2910]
**Original issue**
https://github.com/CanonicalLtd/juju-design/issues/205

**Design**
![image](https://cloud.githubusercontent.com/assets/9105999/26115799/fe8c81cc-3a58-11e7-9220-ae6ad91a8603.png)

**Comment by frankban** [comment]
What happens when you click on it?

**Comment by spencerbygraves** [comment]
@frankban it should open the details page in the overlay.

**Comment by huwshimi** [comment]
@spencerbygraves we have another issue (#1136) about the link under 'Change version' being the only place to see what version the charm is. With this change the version won't be visible at all. Any suggestions on showing that somewhere (feel free to comment over at #1136).

**Comment by spencerbygraves** [comment]
@huwshimi sorry, I didn't deliberately remove that link, I'll update the visual.

I've also commented over on #1136

**Comment by spencerbygraves** [comment]
Here is an updated design. I'm going to open a separate issue on link styles in the inspector as they need updating.

I've included the 'Change version' link. The 'About this charm' link doesn't need the grey background hover as it's taking you to the details page, and not navigating within the inspector.

![image](https://cloud.githubusercontent.com/assets/9105999/26397302/c2079122-406d-11e7-8c75-ccf5ee05ea8e.png)

**Comment by huwshimi** [comment]
@spencerbygraves thanks for the update, do we now have two links next to each other that take you to the same place?

**Comment by spencerbygraves** [comment]
@huwshimi I see what you mean. Perhaps the 'About' link can be removed after deployment. I think we need a UX decision from @elvirafigueras and @ClaraLavina.

**Comment by frankban** [comment]
@elvirafigueras do we have a UX resolution for this?

**Comment by hatched** [comment]
This has been completed.
