### ISSUE TITLE
Regression when clicking search results from profile page

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#2917]
Introduced by https://github.com/juju/juju-gui/pull/2879
Start from your profile, click to open the store, click to view a charm (either from the store initial page or search results), you'll end up in a URL like /u/{user}/{charm} which is not ok, as it overlaps with the user owned charm. We need to close the profile when opening a charm detail.

**Comment by huwshimi** [comment]
This appears to work fine for namespaced charms e.g. /u/canonical-bootstack/prometheus becomes  /u/huwshimi/u/canonical-bootstack/prometheus when the profile is open, but not when there is no namespace e.g. /nagios becomes /u/huwshimi/nagios.
