### ISSUE TITLE
Box sizing issue in /store in develop

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2921]
<img width="1051" alt="screen shot 2017-05-18 at 3 35 21 pm" src="https://cloud.githubusercontent.com/assets/532033/26224455/a97bd10a-3bdf-11e7-9c58-55790d7924e9.png">

**Comment by huwshimi** [comment]
Hi @hatched which browser are you using? It appears fine in Chrome and Firefox for me.

**Comment by hatched** [comment]
This appears to have been resolved or a bad build, I also cannot repro. Thx
