### ISSUE TITLE
Visiting a charmstore entity directly causes multiple UI re-renders

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2929]
If you visit a path like: `<host>/u/hatch/mymodel/elasticsearch/#scale-out-usage` You'll notice that the UI re-renders multiple times as model connects. The app state `app.state._appStateHistory` is filled with multiple state entries with the same values.

The GUI shouldn't need to continue to re-dispatch the same state so we should track down why this is happening and also possibly implement a check in state to not dispatch state if it's identical to a new state.

**Comment by frankban** [comment]
@hatched should we move it to future?

**Comment by hatched** [comment]
Moved, thx
