### ISSUE TITLE
bundle description field is not used in the bundle charm details UX

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#2931]
I've added a description to my bundle:

    description: "My VPN bundle which has the clients I expect out of the box ready to go."
    services:
      myvpn:
        charm: openvpn
        options:
            clients: "rick guest"
        expose: true
        num_units: 1
        to: [0]
    machines:
        0:
            constraints: "mem=1G cpu-power=10"

It's part of the bundle spec

https://github.com/juju/charm/blob/v5/bundledata.go#L50

However I don't get it anywhere in my details UX.

![bundle-description](https://cloud.githubusercontent.com/assets/75915/26350217/6ba01af4-3f80-11e7-932c-1b587fccde32.jpg)

**Comment by hatched** [comment]
@cassiocassio plz advise
