### ISSUE TITLE
Update link styles

### ISSUE THREAD

**Issue by spencerbygraves** [juju/juju-gui#2937]
Links in the inspector should be blue (#007AA6), underlined on hover.

![image](https://cloud.githubusercontent.com/assets/9105999/26397441/41a942e0-406e-11e7-9c6a-e1c96f25c88c.png)

And also in details pages. This is the current style in the GUI:
![image](https://cloud.githubusercontent.com/assets/9105999/26397733/35750b70-406f-11e7-82f6-e25cabee76d0.png)

Versus the store:
![image](https://cloud.githubusercontent.com/assets/9105999/26397747/40e0d9f8-406f-11e7-8567-562a8bff862c.png)

**Comment by frankban** [comment]
So this seems to be fixed, could you confirm @makyo ?
