### ISSUE TITLE
Search field removes the space from search term

### ISSUE THREAD

**Issue by spencerbygraves** [juju/juju-gui#2943]
When I type 'Landscape client' and hit enter, the search field removes the space and returns no results:

**Typing the search term**
![image](https://cloud.githubusercontent.com/assets/9105999/26442683/76aea862-412d-11e7-8661-ea51122249af.png)

**After hitting enter**
![image](https://cloud.githubusercontent.com/assets/9105999/26442798/deaccf98-412d-11e7-99a6-36868a21b28f.png)

**Comment by frankban** [comment]
Good catch Spencer, thanks for reporting!
