### ISSUE TITLE
When viewing kubernetes bundles, some icons are 401ing

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2948]
Visit: `<host>/gui/q/kubernetes` with the browser console open. 

https://api.jujucharms.com/charmstore/v5/~kubernetes/trusty/kubernetes-master-11/icon.svg
https://api.jujucharms.com/charmstore/v5/~kubernetes/trusty/kubernetes-11/icon.svg

Icons are still shown so I'm not sure where these are being requested from.

**Comment by huwshimi** [comment]
You can see the missing icons if you do a search like: http://localhost:8042/q/kubernetes%20cluster. The icons seem to be under the ~kubernetes namespace and I can't see a user with that name, is there some kind of permissions thing going on here? When I click on the icon I get:
```
{
    Message: "unauthorized: access denied for user "huwshimi"",
    Code: "unauthorized"
}
```

**Comment by urosj** [comment]
The team owning those charms are "containers" not kubernetes.

https://jujucharms.com/u/containers/kubernetes-master/19

**Comment by hatched** [comment]
These errors are caused by bundles which have charms that no longer exist.  There isn't much we can do about this besides removing the bundles.

ex) u/mbruzek/kubernetes-cluster/bundle/22
