### ISSUE TITLE
'Back to model' button when on account/ profile page

### ISSUE THREAD

**Issue by Lukewh** [juju/juju-gui#2954]
I occasionally check the account/ profile page but want to return to the last model I was on (especially on the account page). It would be good to have something like:
<img width="1440" alt="screen shot 2017-05-26 at 17 16 22" src="https://cloud.githubusercontent.com/assets/479384/26503040/1923bd12-4237-11e7-8fec-ae083defb5d9.png">

**Comment by hatched** [comment]
Closing this as we no longer dc from the model and so the profile can just be closed.
