### ISSUE TITLE
When not logged in on /new gui has bottom scrollbar and breadcrumb divider

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#2958]
![new-model](https://cloud.githubusercontent.com/assets/361637/26570673/2650bc3a-4555-11e7-9f9e-4d8afdb440cc.png)

**Comment by hatched** [comment]
The breadcrumb missing is expected as when you're not logged in we have no username or model list.

However there shouldn't be a horizontal scrollbar

**Comment by hatched** [comment]
Sorry I now see that the breadcrumb / is being shown, that definitely shouldn't be there.
