### ISSUE TITLE
GUI gets into infinite loop after deploying to a new model

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2968]
GUI gets into infinite loop after deploying to a new model.

To reproduce:
- Use prod/staging jimm
- open the devtools 
- connect to a model
- click to create new
- add a charm to the model and deploy
- once deployed, switch models via the model switcher
it'll now loop

**Comment by jaycee** [comment]
Confirmed, I'm seeing the same behavior with these steps.

**Comment by jaycee** [comment]
QA OK.

On both gisf and gijoe, logging in works (auto login via usso on gisf, user:pass on gijoe). Creating new models with deployment flow works. Model switching between several models works. Loading other people's profiles directly (i.e. by entering the url /u/$username) works w/o me seeing /login/. Logging out works.
