### ISSUE TITLE
Code snippet field not displaying correctly

### ISSUE THREAD

**Issue by spencerbygraves** [juju/juju-gui#2976]
Missing the icon and button:

![image](https://cloud.githubusercontent.com/assets/9105999/26784208/50ff9c1e-49f4-11e7-883d-39405140a772.png)

**Comment by hatched** [comment]
@spencerbygraves was this the GUI tip? What browser? Any errors in the browser console? I'm not able to reproduce.

**Comment by spencerbygraves** [comment]
@hatched strange, seems to be ok now. Nevermind, I'll close this issue!

Thanks
