### ISSUE TITLE
readme headings are not anchorable

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#2978]
As we provide full solutions the need for the readme to be able to reference other sections (e.g. a FAQ or Troubleshooting section at the bottom) becomes a bigger and bigger missing feature. 

All headings should be anchorable so that users can link to those headings within the document.

**Comment by huwshimi** [comment]
Thanks @mitechie I think this functionality should be covered by #2915 and will be available with the next release. If there's something missing feel free to reopen.

**Comment by spencerbygraves** [comment]
@huwshimi have you used the anchor icon as in the docs pages, or the link icon for inserting links?

![image](https://cloud.githubusercontent.com/assets/9105999/26822999/e51ac66c-4aa3-11e7-9d0c-e4ca117f2681.png)

**Comment by huwshimi** [comment]
Oops, thanks @spencerbygraves, I used the wrong image.
