### ISSUE TITLE
How to specify a default VPC

### ISSUE THREAD

**Issue by bitdivine** [juju/juju-gui#2985]
Hello,

I am trying to set up juju so that by default it places all instances in a specified region and within that region, in a specified VPC.  Browsing the source code it looks as if I should be able to do something like this in the `credentials.yaml` in my home directory:

    credentials:
      aws:
        default-region: eu-west-1
        default-vpc:
          eu-west-1: vpc-xxxxxxxx
        conjure-up-aws-cba:
          auth-type: access-key
          access-key: redacted
          secret-key: redacted

However that isn't quite right.  Do you have an example configuration that works?

Many thanks!

**Comment by bitdivine** [comment]
Update:  I have been looking through the commands.  There is this:

    juju model-defaults aws/eu-west-1 vpc-id=vpc-xxxx  # doesn't work

So I nuked all my instances, ran the above, then `conjure-up` and made a new juju controller.  That came up in the default VPC, not in the one I had specified.  But ever hopeful I then made one server from a Kubernetes cluster.  That too came up in the default VPC, not the one I had specified.  So this is a dead end.  I'm still looking for something that works.

**Comment by hatched** [comment]
Hi @bitdivine this is the issue tracker for the Juju GUI, you'll have better luck with the juju mailing list for this question: https://lists.ubuntu.com/mailman/listinfo/juju

However the GUI includes a position to input your VPC ID when deploying to AWS either on a self bootstrapped controller or via JAAS: https://jujucharms.com/new/
