### ISSUE TITLE
New init issues & tasks

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#3009]
- [x] the cookie notice can't be dismissed - I can't seem to get it to show either...
- [x] log into charmstore in profile doesn't work
- [x] loading the gui without a model url or /new url loads a blank canvas instead of showing your profile - state should probably redirect.
- [x] update relationsUtils to be a module
- [x] update changesUtils to be a module
- [x] cookie notice missing
- [x] blank canvas onboarding missing
- [x] clicking the username doesn't take you to the profile
- [x] visiting a charm gives an error: Failed prop type: The prop `changeState` is marked as required in `HashLink`, but its value is `undefined`
- [x] clicking "Add to model" gives an error "this.get is not a function" (however the charm is added to the canvas)
- [x] after adding the app the deploy button does not become enabled
- [x] destroying an uncommitted app doesn't remove it, but adds a message: "This application has been marked to be destroyed on next deployment."
- [x] loading /new directly doesn't set the model name to 'uncommitted' (it's just blank)
- [x] in the machine view opening the add machine for and clicking Create has an error: `Cannot read property 'machines' of null`
- [x] switching from a model with uncommitted changes has an error when trying to show the lose changes confirmation

**Comment by huwshimi** [comment]
Close this as these tasks have been completed and further tasks are being tracked as single issues.
