### ISSUE TITLE
Trigger a notification when deploying a bundle

### ISSUE THREAD

**Issue by anthonydillon** [juju/juju-gui#3015]
When you deploy a single application you get a notification stating: `Successfully deployed the requested application.`

But when you deploy a bundle there is no notification.

**Comment by hatched** [comment]
So that notification is actually incorrect. You're not deploying the application at that point, simply adding them to the pre-committed model so it should be updated.

When adding a bundle to the canvas you get a notification that says "ChangeSet import complete.".

**Comment by frankban** [comment]
So I guess we can add notifications for when all the API calls used to deploy the thing are been sent and acked. So "Charm deployment started" and "Bundle deployment started" could be an option, the former after the usual addCharm/deploy calls are executed, the latter when all calls for all bundle changes are properly sent. As discussed, adding a ntification for when a deployment is actually done, especially in the bundle case, is tricky.
