### ISSUE TITLE
Emphasize security of stored creds

### ISSUE THREAD

**Issue by makyo** [juju/juju-gui#3029]
This will need design input, but user testing revealed that we should emphasize the security of stored credentials (cloud and SSH) for users. One user voiced that they had leaked some of their AWS keys at one point and experienced some fallout.

**Comment by cassiocassio** [comment]
current wording in DF
"Credentials are stored securely on our servers and we will notify you by email whenever they are changed or deleted. You can see where they are used and manage or remove them via the _account page._"

See also https://github.com/CanonicalLtd/juju-design/issues/213#issue-229373610
For sketch of proposal using new AWS best-practice, etc

**Comment by mitechie** [comment]
This story was specifically about why they now use GH enterprise internally
as the creds got into source code and leaked via GH. I also think that this
took some prodding from @cassiocassio. I think the feedback we received was
that folks would test with their own creds but that large organizations
definitely want to go the way of rolling creds which juju needs to build in
support for.

**Comment by hatched** [comment]
Closing this as there will be new designs implemented.
