### ISSUE TITLE
Remove duplicate changelogs in deployment flow

### ISSUE THREAD

**Issue by jaycee** [juju/juju-gui#3031]
There are two logs in the deployment flow that show the same data. We should remove one.

**Comment by cassiocassio** [comment]
![two logs what s the difference](https://user-images.githubusercontent.com/4593556/27534902-6cf33206-5a60-11e7-8509-3219a48474a5.png)




Commets and questions:

(1) with config changes etc we don't provide any detail

(2) with application additions we describe
	(i) machines to be deployed
	(ii) applictions to be deployed
	
	In that case, almost all the information is duplicated
	
But if we removed the detail in "model changes" updates not inlving the addition or removal of chamrms would not have any detail?

**Comment by huwshimi** [comment]
In case it helps, the different types of changes we have are:
- add an app
- destroy an app
- add an app resource
- add a unit
- remove a unit
- expose an app
- unexpose an app
- add a relation
- remove a relation
- add a machine
- destroy a machine
- set config for an app
- add a charm to the controller (a technical detail I think, I can't imagine the user would care about this).

**Comment by Lukewh** [comment]
Fixed by https://github.com/juju/juju-gui/pull/3089. Reopen if untrue.
