### ISSUE TITLE
Fix tense of items in deployment flow changelog

### ISSUE THREAD

**Issue by jaycee** [juju/juju-gui#3032]
The items in the ECS that are shown in the deployment flow changelog are all in past tense, e.g. "2 units added".

It should read e.g. "2 units to be added" or "2 units will be added".

**Comment by cassiocassio** [comment]
+1  to the the second form of words

**Comment by mitechie** [comment]
I'd also like to clarify the difference between the changelog and the
"changes" and why we need both?
