### ISSUE TITLE
embeded K8s juju card (ubuntu.com/ points to old demo

### ISSUE THREAD

**Issue by cassiocassio** [juju/juju-gui#3048]
(I'm not sure if this is a ubuntu.com problem or a jujucharms.com problem)

# An embeded card points to the old demo 

at [https://www.ubuntu.com/containers/kubernetes](https://www.ubuntu.com/containers/kubernetes)

(scroll right down...)

![card points to demo](https://user-images.githubusercontent.com/4593556/27831193-7e19e522-60c1-11e7-8229-f8a8579bfbce.png)

by comparison, cards made at https://jujucharms.com/community/cards point to the correct URL

![correct url for card](https://user-images.githubusercontent.com/4593556/27831313-0847938e-60c2-11e7-85fb-a46aaa633a94.png)

**Comment by anthonydillon** [comment]
This fix has gone live.
