### ISSUE TITLE
Local charms icons not properly shown in the GUI canvas

### ISSUE THREAD

**Issue by ionutbalutoiu** [juju/juju-gui#3067]
I have a local Juju controller on MAAS with GUI enabled and I deployed a couple of local charms.
The charms icons are broken in the GUI canvas and this is what I see: http://balutoiu.com/ionut/icons.png

If I do an inspect element on the charm box from the canvas and open the icon url into another tab, I see that icon is properly fetched from the Juju controller.

Moreover, when using Firefox, there is no issue and icons are properly shown in the GUI canvas.

Versions of the tools used:

- Juju 2.2.1
- Google Chrome 59.0.3071.115
- Firefox 54.0.1

**Comment by hatched** [comment]
Thanks for the report! We'll look into this shortly.

**Comment by frankban** [comment]
Related, from https://bugs.launchpad.net/juju/+bug/1712269

Due this Chrome https://www.chromestatus.com/feature/5669008342777856 feature. Juju icons are not loaded at all.

Chrome tries load images:

https://user-admin%40local:foobarpasswords@10.10.10.1:17070/model/e61120bf-9b6d-43e1-8ae4-f4bf5b31ffd1/charms?url=local:xenial/any-charm&icon=1

This reults (blocked:origin) error on Chrome.

**Comment by ionutbalutoiu** [comment]
Any update on this bug ? I'm using `2.2.4-xenial-amd64` right now and it icons are still not visible in Google Chrome.

**Comment by deephack1982** [comment]
I just commented on this related issue. [https://github.com/juju/juju-gui/issues/1262#issuecomment-332166336](url)

**Comment by hatched** [comment]
As this requires extensive changes in Juju to provide us with a different way to securely fetch the local charm assets, any updates to this may be a long time coming. I consider this to be a regression in Chrome and hopefully they will fully revert the change in time.

**Comment by frankban** [comment]
Yes I agree. We need to implement a macaroon based auth for getting charm files from the controller. This means adding macaraq logic for local users as well. While this is something that we'd like to implement for other auth-related reasons as well, we'll have to find a slot for this.

**Comment by rmescandon** [comment]
Any news on this thing?

**Comment by hatched** [comment]
I see that the old issue was closed. I've created a new one that can be used to track this issue in Juju https://bugs.launchpad.net/juju/+bug/1824887
