### ISSUE TITLE
Add more tests around deployment flow changes

### ISSUE THREAD

**Issue by Lukewh** [juju/juju-gui#3069]

**Comment by frankban** [comment]
Is this done?

**Comment by kasiag** [comment]
@Lukewh can you give an update please?

**Comment by hatched** [comment]
Because the UI is changing shortly I'm not sure this is worthwhile for now. @Lukewh please close if you agree.

**Comment by Lukewh** [comment]
Probably worth adding some for the SSH stuff. Will move it to next iteration (next two weeks for those not in the office) as it shouldn't take long and that stuff won't change that much @hatched @kasiag

**Comment by hatched** [comment]
@Lukewh I believe you've finished this?
