### ISSUE TITLE
Visiting read-only model shows model name as 'untitled-model'

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#3071]
To reproduce have someone share a read-only model with you.

When you switch to that model the model switcher will show 'untitled-model'

**Comment by huwshimi** [comment]
I think this is because you get an error: "error retrieving current model information: permission denied" from `_handleCurrentModelInfo`.

**Comment by hatched** [comment]
Thanks for the investigation @huwshimi

**Comment by frankban** [comment]
This problem has been fixed at https://github.com/juju/juju/commit/5bc7728955073ded61418a78f9acc06df3be9a58
