### ISSUE TITLE
Move components using expanding-rows to use accordion-section

### ISSUE THREAD

**Issue by Lukewh** [juju/juju-gui#3082]

**Comment by huwshimi** [comment]
Hi Luke, if you get a moment could you let us know a few more details about this change? I wasn't really sure what the difference between the components was.

**Comment by Lukewh** [comment]
@huwshimi the `accordion-section` is closer to the vanilla standard for openable (not a word) sections of content, allows for a clickable title and is less specific in it's classes. 
The original `expanding-row` uses classes quite heavily and is also a list item - sometimes it's used when not in a list.

Generally `accordion-section` should be a cleaner way of doing 'expandy-things'. If the consensus is that the above statements aren't true, close this issue!
