### ISSUE TITLE
DD offers to deploy when it can't find a charm

### ISSUE THREAD

**Issue by cassiocassio** [juju/juju-gui#3093]
![not-a-bundle](https://user-images.githubusercontent.com/4593556/28535614-edfcbb86-709c-11e7-9e19-9bfed5a6c19a.png)

- URL with an error in it
- should probably not offer to deploy this...

clicking the green button leads to a doomed flow..

![still-not-worth-deploying](https://user-images.githubusercontent.com/4593556/28535686-2b40c6cc-709d-11e7-9048-0906b5231edd.png)

suggestions: 

- don't show the line with the green button in?
- bounce the user to a store-page: bundle not found - search again?
- some kind of lazy-matching of the attempted deployment? - perhaps the bundle you were looking for was... ?

**Comment by hatched** [comment]
@cassiocassio fixed in #3096 feel free to give it a try!
