### ISSUE TITLE
canvas/machine switcher icons missing in chrome

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#3112]
<img width="310" alt="screen shot 2017-07-28 at 10 39 56 am" src="https://user-images.githubusercontent.com/532033/28727186-2c1799ae-7381-11e7-8b64-1a2c0748dab1.png">

**Comment by hatched** [comment]
It looks like these were removed intentionally: https://github.com/juju/juju-gui/pull/3104/files#diff-ae6134eaa439fc90782ada0b3383eb1bL71

@huwshimi

**Comment by huwshimi** [comment]
@hatched yeah, unfortunately with the new status item there is no longer any room for the icons.

**Comment by hatched** [comment]
Thanks @huwshimi
