### ISSUE TITLE
When removing only a machine the deployment flow doesn't say so

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#3113]
If you have a deployed machine then remove it. The deployment flow doesn't render the machine component and outline that a machine is being removed.

<img width="1071" alt="screen shot 2017-07-28 at 10 51 56 am" src="https://user-images.githubusercontent.com/532033/28727636-cd77c9b2-7382-11e7-868e-b2f891ce4dee.png">

**Comment by makyo** [comment]
This refers not to the model changes, but to the machine changes component (rather than a machine component in the model changes)
