### ISSUE TITLE
HELP! Can I run Juju on localhost?

### ISSUE THREAD

**Issue by leer168** [juju/juju-gui#3117]
Hi, guys,

I had downloaded Juju、Juju-gui、GuiProxy, and read the docs. But I can run them on localhost looks like jujucharms.com. 

I want to figure out how it work, then debug it and study the code.

What can I  do  to achieve it?

Thank you very much!

**Comment by frankban** [comment]
Hey,
not sure I fully understand what you are trying to do.
If you want to build the GUI so that you can hack/develop on it locally, do the following:
- clone this repo on ubuntu;
- run `make sysdeps`;
- run `make run`;
- in another tab, install golang on the ubuntu machine;
- run `go get github.com/juju/guiproxy`;
- install lxd and juju;
- bootstrap a local controller on LXD (`juju bootstrap lxd`);
- run `guiproxy`;
- visit the GUI at localhost:8042;

Please report any problems you encounter in the process, so that we can keep providing help and fix possible issues.

**Comment by leer168** [comment]
Thank you for reply!

But I can not run it.

![image](https://user-images.githubusercontent.com/934063/28777843-594e971e-762f-11e7-89d1-18d94e41cfa3.png)

Could you teach me in detail, include the params for the cmd. Thank you very much!

I lost in juju, juju-gui,guiproxy. In one word can I deloy one just looks like jujucharms.com, and other user can build model on my server?

**Comment by frankban** [comment]
Is the local controller running? Output of juju status? If you are switched into the controller you should not need any guiproxy parameters (-gui also is not required in most cases).

**Comment by hatched** [comment]
@leer168 the guiproxy is a development tool, so unless your plan is to modify the GUI you can just access the GUI by running `juju gui` from your CLI after bootstrapping your controller by running `juju bootstrap`. 

If you want people to create their own models on your controller you can do this by granting them access with `juju grant` https://jujucharms.com/docs/2.2/users-models

**Comment by leer168** [comment]
@frankban 
![image](https://user-images.githubusercontent.com/934063/28808377-184603fe-76ae-11e7-9ad1-25a02d59095c.png)

**Comment by leer168** [comment]
@hatched Thank you first! Yes I want do develop the gui, and delpoy my own server looks like jujucharms.com, I hope it runs completely independent. When I run some commands, they get data from jujucharms's server. I doubt it runs some rely on jujucharm.com or something like api-server.

![image](https://user-images.githubusercontent.com/934063/28808421-7213fa9e-76ae-11e7-8ac9-a26c7b5136c0.png)
![image](https://user-images.githubusercontent.com/934063/28808426-7cedc4d6-76ae-11e7-9f44-cdbc9d21d44a.png)

**Comment by frankban** [comment]
guiproxy needs juju to be on your path. Alternatively you can provide the controller API address via the -controller parameter (something like `-controller '10.56.39.86:17070'`). To retrieve the API address you can run `juju show-controller`. If you instead want to connect the local GUI to JAAS, you can run `guiproxy -env production`.

**Comment by leer168** [comment]
@frankban Thank you! I don't connect anything to JAAS. I want to clone JAAS. Can I reach it?

**Comment by urosj** [comment]
Hi, @leer168 

JAAS includes many services, GUI is just part of the frontend. I am however interested what user experience you're trying to solve by cloning. Maybe we can add something that would suit you or your (potential) users.

**Comment by leer168** [comment]
Thanks @urosj 

I like the UI and Model  building's interactive design. I wish to develop some feature base on it, which might not be appropriate merge to the upstream,  so I do it myself.

Can I use all of open-source code about juju, to build a server just like simplified version JAAS,
