### ISSUE TITLE
YAML warnings using kubernetes

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#3119]
- bootstrap on aws
- load the direct deploy with kubernetes e.g. /gui/u/admin/default/?dd=bundle/canonical-kubernetes-76 (or add kubernetes to the canvas)
- you'll have warnings in your console:
```
JS-YAML: deficient indentation at line 4, column 1
JS-YAML: deficient indentation at line 6, column 1
```

**Comment by hatched** [comment]
Thanks @huwshimi but this issue is with the bundle itself.

https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/371

**Comment by huwshimi** [comment]
Thanks @hatched do we need to display anything to the user or will it all work fine?

**Comment by hatched** [comment]
It all works as expected, thankfully the YAML parser carries on after that.
