### ISSUE TITLE
Uncommitted relations show as blank lines in the status view

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#3138]
If you add a new relation in a committed model there will be a new entry in the status view, but there is no text.

![relation](https://user-images.githubusercontent.com/361637/29397489-d7440e26-8361-11e7-9021-d7e4f6cef48a.png)

**Comment by frankban** [comment]
This is a duplicate of https://github.com/juju/juju-gui/issues/3158 (well, it's the other way around, but I am closing this as that one is already referenced by a PR).
