### ISSUE TITLE
Place beta message on all pages

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#3149]
The "Beta" message is missing on the Machine View and Status panes.

When the status is being viewed this message should change to something along the lines of "Status Preview" to indicate that it's still under development.

**Comment by spencerbygraves** [comment]
@hatched @huwshimi @frankban If we're happy to change the Beta label on the status view then I suggest something like "Status beta" for the text. The image below also has the newer notification style for errors etc, perhaps that can be part of the next update.

![image](https://user-images.githubusercontent.com/9105999/29558856-4d98075a-8725-11e7-9d13-0647a6ee0fad.png)
