### ISSUE TITLE
Log-in button form styling issue

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#3157]
<img width="404" alt="screen shot 2017-08-23 at 1 34 50 pm" src="https://user-images.githubusercontent.com/532033/29634697-e7648aec-8807-11e7-99ad-5fc2af5f976b.png">

**Comment by makyo** [comment]
Not sure why this change was made in https://github.com/juju/juju-gui/pull/3136/commits/11850596322dc1326945c2e0d197f6d2c22be069

@hatched do you remember why the padding/colors were changed? Can revert changes to that file safely? If I don't fix colors, I wind up with ugly text:
![image](https://user-images.githubusercontent.com/303761/29636236-1bc0ace4-880d-11e7-9515-4ffd5b955237.png)
