### ISSUE TITLE
Auto place in Machine View no longer works

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#3163]
Add an application and scale it up from the inspector. Switch to the machine view then click auto place. Nothing will happen but there will be a react error:

`Warning: Failed child context type: React.PropTypes type checking code is stripped in production.
    in DragDropContext(MachineView)`

**Comment by hatched** [comment]
It actually appears that maybe the units are auto-placed but the UI doesn't update...Switching away from the machine view and back again shows the placed units.

**Comment by frankban** [comment]
The warning does not seem to be related to the bug. ReactDnD is doing something weird, but it doesn't break anything.

**Comment by frankban** [comment]
Hum, maybe the warning is actually related to the bug.

**Comment by frankban** [comment]
No, it's not ;-)
