### ISSUE TITLE
Different charm revisions provided by charm store

### ISSUE THREAD

**Issue by hloeung** [juju/juju-gui#3165]
Hi,

I first thought this issue was to do with the "charm" tool so reported it here - https://github.com/juju/charm-tools/issues/337

It seems that when retrieving charms without specifying revisions (e.g. cs:~user/charm or cs:charm), users could end up with different versions of a charm. I dug into this and it seems to be caching done by the charm store.

> [hloeung@dharkan graylog]$ date -u; charm push . cs:~hloeung/testing-cache
> Fri  4 Aug 10:57:39 UTC 2017
> url: cs:~hloeung/testing-cache-7
> channel: unpublished
> [hloeung@dharkan graylog]$ date -u; charm release cs:~hloeung/testing-cache-7
> Fri  4 Aug 10:58:32 UTC 2017
> url: cs:~hloeung/testing-cache-7
> channel: stable
> warning: bugs-url and homepage are not set.  See set command.
> [hloeung@dharkan graylog]$ date -u; charm grant cs:~hloeung/testing-cache-7 everyone
> Fri  4 Aug 10:58:46 UTC 2017

Now the FE logs:

> 10.172.254.12 - - [04/Aug/2017:10:57:41 +0000] "POST /charmstore/v5/~hloeung/testing-cache/archive?hash=0c99628996508b5b35dd4effc52af7e40e5b85aeff866ff41b5b29a2994f814b2def3fcd1ef58889d6caa41d65c22370 HTTP/1.1" 200 721 "-" "Go-http-client/1.1" (17530708) "-"
> 10.172.254.12 - - [04/Aug/2017:10:57:59 +0000] "PUT /charmstore/v5/~hloeung/testing-cache-7/meta/extra-info HTTP/1.1" 200 664 "-" "Go-http-client/1.1" (7939) "-"
> 10.172.254.12 - - [04/Aug/2017:10:58:33 +0000] "PUT /charmstore/v5/~hloeung/testing-cache-7/publish HTTP/1.1" 200 4466 "-" "Go-http-client/1.1" (13943) "-"
> 10.172.254.12 - - [04/Aug/2017:10:58:33 +0000] "GET /charmstore/v5/~hloeung/testing-cache-7/meta/any?include=common-info HTTP/1.1" 200 747 "-" "Go-http-client/1.1" (4541) "-"
> 10.172.254.12 - - [04/Aug/2017:10:58:47 +0000] "GET /charmstore/v5/~hloeung/testing-cache-7/meta/any?include=perm HTTP/1.1" 200 4668 "-" "Go-http-client/1.1" (16626) "-"
> 10.172.254.12 - - [04/Aug/2017:10:58:47 +0000] "PUT /charmstore/v5/~hloeung/testing-cache-7/meta/perm HTTP/1.1" 200 664 "-" "Go-http-client/1.1" (11364) "-"

Now for "charm pull":

> [hloeung@dharkan t]$ date -u; charm pull --channel stable cs:~hloeung/testing-cache destdir10
> Fri  4 Aug 10:59:05 UTC 2017
> cs:~hloeung/testing-cache-4

FE logs:

> 10.172.254.12 - - [04/Aug/2017:10:59:06 +0000] "GET /charmstore/v5/~hloeung/testing-cache/archive?channel=stable HTTP/1.1" 200 3766990 "-" "Go-http-client/1.1" (12423282) "-"

Per the issue reported against charm tools, it was actually flipping between revisions depending on which FE my request was sent to.

**Comment by frankban** [comment]
Hey Haw, thanks for reporting this bug!
I moved it to the charm store project at https://github.com/juju/charmstore/issues/766
Therefore closing it here.
