### ISSUE TITLE
Switching models with the inspector open throws error

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#3170]
To reproduce, connect to an active model and then select an application in it so that the inspector is open. Then use the model switcher to create a new model. 

https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/components/inspector/inspector.js#L49 throws because there is no 'gui' in the state at this point.

**Comment by frankban** [comment]
I am not able to dupe this.

**Comment by frankban** [comment]
It works for me both using guiproxy and on staging.

**Comment by hatched** [comment]
I believe that this might be racey because I too am not able to always reproduce it. We probably just need to be more resilient with that object walk.

**Comment by hatched** [comment]
This appears to have been resolved.
