### ISSUE TITLE
Able to modify the model name in the header on committed models

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#3171]
To reproduce:

Switch to a committed model, in the model switcher you can modify the model name.

**Comment by frankban** [comment]
I cannot reproduce, could you please take another look and describe how to dupe?

**Comment by cassiocassio** [comment]
a. **Before** deployment the model-name in the model-switcher is editable.

b. **After** deployment, it is not.

I'm assuming this is correct behaviour, because [controllers do not support renaming models](https://bugs.launchpad.net/juju/+bug/1634262).

@hatched do you see different behaviour?

**Comment by hatched** [comment]
I do and I can reliably reproduce it. I'll fix it when I can.

**Comment by huwshimi** [comment]
This seems to be fixed now (with the new init changes).
