### ISSUE TITLE
gui does not have a logout of charmstore button

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#3198]
Once you log into the charmstore from the GUI you cannot log back out w/o manually wiping localstorage.

**Comment by hatched** [comment]
@cassiocassio can we make sure we have the proper charmstore log in/out in the new profile design.

**Comment by huwshimi** [comment]
Additionally, maybe there's a way, but I can't see anything that tells me which charmstore user I'm logged in as.

**Comment by hatched** [comment]
I thought that we stored it in the user class, but if it's not there then you can make a 'whoami' call from the charmstore api.

**Comment by huwshimi** [comment]
@hatched oh sorry I mean, after log in in the profile
