### ISSUE TITLE
Allow updating of Cloud Credentials from Account page

### ISSUE THREAD

**Issue by cassiocassio** [juju/juju-gui#3201]
**option 1** Just Add Button

- simples
- management on the right and destruction on the left - is that our convention?
- Is "update" rather than "manage" the right verb?

![img_9448](https://user-images.githubusercontent.com/4593556/30334333-3241841e-97d7-11e7-8f6a-63fbe01e0914.jpg)

**option2** Like Models

- works just like models list in *profile*
- just checking: there is any other info we have access to, about a credential, that we would/could show in the expanded card?

![img_9449](https://user-images.githubusercontent.com/4593556/30334334-3245a6c0-97d7-11e7-8df9-2cba7a2f6eb9.jpg)

**Comment by mitechie** [comment]
I'm biased as I'm very anti the model method with the expandy thing. 

I like option 1, that would expand with the proper form for the type of credential. 

I think update seems like the button you'd hit after changing the values. Edit? I don' think we'd want an update/update dual buttons.

**Comment by cassiocassio** [comment]
+1 option one, with edit.

**Comment by jamesbeedy** [comment]
+1 option #1

**Comment by hatched** [comment]
This has been implemented and will be in the next release.
