### ISSUE TITLE
new-init: the status tries to show the status for uncommitted models

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#3226]
The status for uncommitted models should show the message about not being deployed or whatever it says...

**Comment by hatched** [comment]
It does this now.

**Comment by huwshimi** [comment]
I discovered how to reproduce this:
- start a new model
- add an app
- open status, it'll have the proper message about not being connected
- set the model name (either in the header or by opening and closing the deployment flow)
- open the status again
- the status will be shown with some undefined vars
