### ISSUE TITLE
Error when deploying models 

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#3252]
Trying to deploy a model fails with `Uncaught TypeError: Cannot read property 'replace' of undefined` from the post deployment panel I think.

**Comment by Lukewh** [comment]
@huwshimi can you check if https://github.com/juju/juju-gui/pull/3256 fixes this? If not was it for any charm/ bundle or specifics?

**Comment by huwshimi** [comment]
@Lukewh no change. On staging I added `trusty/apache2` twice and related them, removed the two units (not the apps) and clicked deploy and got the same error.

**Comment by Lukewh** [comment]
Hmm @huwshimi I've tried a few different charms and bundles and still don't get the error. Are you running this from a clean-all?

**Comment by Lukewh** [comment]
@hatched can you give this a go and see if you get errors, cheers.

**Comment by hatched** [comment]
@Lukewh I can reproduce this following the steps @huwshimi mentioned. Did you try the apache2/apache2 combo?

**Comment by hatched** [comment]
Sorry I am not able to reproduce this issue, I was however able to still reproduce #3228
