### ISSUE TITLE
Cannot set config option to empty string in inspector

### ISSUE THREAD

**Issue by makyo** [juju/juju-gui#3298]
Setting a config value to an empty string (away from the default) does not make the change in the model. This occurs both for uncommitted and committed services.

For instance, deploy ~yellow/jujushell and change juju-cert to an empty string during deploy. It will revert to from-unit on refresh. Change it again once deployed, the same will happen. run `juju config jujushell juju-cert=''` from the CLI and refresh the GUI; the config setting will be an empty string.

**Comment by huwshimi** [comment]
The RPC call made is `{"type":"Application","request":"Deploy","params":{"applications":[{"application":"jujushell-a","charm-url":"cs:~yellow/jujushell-2","constraints":{},"num-units":0,"resources":{"jujushell":"0b034d4f-5987-454a-8f6d-02b170f09664","termserver":"34ff3d50-aaf2-4b5d-81ba-99bbc9cb798e"},"config":{"juju-addrs":"","juju-cert":"","log-level":"info","port":"8047","snap_proxy":""},"series":"xenial"}]},"version":4,"request-id":16}`

This has juju-cert set to a blank string. Is it possible Juju is not reading/setting these values correctly?

**Comment by hatched** [comment]
Thanks @huwshimi 

Yes this does appear to be a Juju bug https://bugs.launchpad.net/juju/+bug/1513466

Also related: https://github.com/juju/juju-gui/issues/2486
