### ISSUE TITLE
addPendingResources not cleared when charm parent record is cleared.

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#3304]
To reproduce add the 'jujushell' charm to a new canvas. Before deploying, hit the "destroy" button in the inspector. You'll now get an error in the console where the application in the `application.get('icon')` is null.

```js
        case '_addPendingResources':
          const applicationName = change.command.args[0].applicationName;
          const application = services.getServiceByName(applicationName);
          changeItem.icon = application.get('icon');
```

**Comment by huwshimi** [comment]
I wasn't able to reproduce this. I pointed guiproxy to prod and added ~yellow/jujushell to the canvas. When I clicked Destroy in the inspector it removed it correctly with no errors in the console.

**Comment by hatched** [comment]
After checking this out again I wasn't able to reproduce it using these instructions, however if I add 'jujushell' then destroy it. There are still pendingResources trying to be added in the DF which throws the same error. It appears that the destroy ecs command doesn't clear related resources.
