### ISSUE TITLE
deploying my own from from the profile loads the store after I hit "add to model X"

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#3313]
After finding my charm, hitting View to load the details, when I hit "Add to xxxx" it does add it to the GUI but I end up looking at the store page. 

Link to video walkthrough
https://photos.app.goo.gl/U27ElI3YXIsSKvLJ2

**Comment by mitechie** [comment]
This happens more than just my own charms. I clicked on the kubernetes bundle and when I hit add to model...it also opened the store UI and I had to close it to get back to the canvas.

**Comment by huwshimi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix store state when deploying/viewing entities from a profile.](https://trello.com/c/yTaUhsVS/21-fix-store-state-when-deploying-viewing-entities-from-a-profile)
