### ISSUE TITLE
destroying deploy page lacks context and feels like nothing is getting done

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#3314]
I destroyed my k8s applications from my model in the GUI and when I hit deploy it looks so empty even though I'm destroying 6 applications. 

It's all hidden in the drop down and not obvious and feels like we can/should do a better job of assuring the user things are on the right path. In a deploy there's a count of new machines, but when the change is not a deploy there's a lack of any hand holding. 

![ondestroy](https://user-images.githubusercontent.com/75915/32554593-5025908e-c468-11e7-9fac-60e897da7328.jpg)

**Comment by hatched** [comment]
@cassiocassio can you be sure the new DF design handles the 'existing model changes' to address this issue plz.

**Comment by huwshimi** [comment]
At the very least we should probably default the list of changes to being open on commit.

**Comment by huwshimi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix store state when deploying/viewing entities from a profile.](https://trello.com/c/yTaUhsVS/21-fix-store-state-when-deploying-viewing-entities-from-a-profile)
