### ISSUE TITLE
getstarted.md only shows when it's a brand new model

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#3316]
if I have an existing model and deploy a charm or bundle with a getstarted.md it doesn't load the getstarted.md contents. It only does so when it's a fresh new model that I walk through the longer deployment flow pattern.

**Comment by hatched** [comment]
Thanks for filing this @mitechie. @Lukewh is currently working on updating this so that it can persist through refresh.

**Comment by hatched** [comment]
Sorry I misread the original issue. This is indeed a separate bug not an enhancement.

**Comment by mitechie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [getstarted.md only shows when it's a brand new model](https://trello.com/c/h8B1TOs0/30-getstartedmd-only-shows-when-its-a-brand-new-model)

**Comment by mitechie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [getstarted.md only shows when it's a brand new model](https://trello.com/c/h8B1TOs0/30-getstartedmd-only-shows-when-its-a-brand-new-model)
