### ISSUE TITLE
Inspector: Get started and About links for charm

### ISSUE THREAD

**Issue by cassiocassio** [juju/juju-gui#3321]
prototype these designs

Phase 1- Update existing inspector layout with Get started and About links#305
https://github.com/CanonicalLtd/juju-design/issues/305

**Comment by mitechie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Phase 1- Update existing inspector layout with Get started and About links](https://trello.com/c/uRyiE8Ye/31-phase-1-update-existing-inspector-layout-with-get-started-and-about-links)

**Comment by mitechie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Phase 1- Update existing inspector layout with Get started and About links](https://trello.com/c/uRyiE8Ye/31-phase-1-update-existing-inspector-layout-with-get-started-and-about-links)
