### ISSUE TITLE
Cookies message completely blocks deploy button in deployment flow

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#3348]
https://github.com/CanonicalLtd/jujucharms.com/issues/502

Looks like this is a regression with the new cookie design (https://github.com/juju/juju-gui/issues/2467)

See attached image. For new users, they don't really know what the next step should be.

<img width="1243" alt="cookies blocking deploy" src="https://user-images.githubusercontent.com/8036113/33017163-9087049a-cdf1-11e7-8e7f-18d428e9bc30.png">

**Comment by anthonydillon** [comment]
The cookie policy notification has always been along the bottom. The controls were shifted up when it's was displayed. You could put a timeout to auto destroy the cookie notification after a few seconds.

On the other hand, I still feel the app does not need a cookie notification as users should have seen it in the store and we could simply add a link to the help drop down menu.
