### ISSUE TITLE
Empty application name isn't rejected, causes issues

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#3349]
https://github.com/CanonicalLtd/jujucharms.com/issues/500

Steps to reproduce

Add a charm to the canvas (I started with PostgreSQL but verified with K8S)
Configure one of the applications and empty the "Application name"
At this point, I expect a validation error, but it didn't complain... so:

Click deploy changes
Note that nothing happened, but look in your browser's console and see an error - http://paste.ubuntu.com/26003939/

**Comment by makyo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Empty application name isn't rejected](https://trello.com/c/FXucWf6D/66-empty-application-name-isnt-rejected)
