### ISSUE TITLE
Profile page charm listing generates invalid visit urls.

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#3354]
I logged into jaas, went to my profile, opened the charm details view for my private charm. I then took that url and went into a new tab and pasted the url. I ended up at

So I entered: https://jujucharms.com/store/u/rharding/grafana/4

and ended up at: https://jujucharms.com/u/rharding

**Comment by hatched** [comment]
it looks like your path is incorrect. See: https://jujucharms.com/u/rharding/grafana/4

**Comment by hatched** [comment]
It turns out that the profile page is generating the incorrect urls. To get that url visit /u/rharding then click on 'view' for the grafana charm.
