### ISSUE TITLE
juju-gui doesn't use autocert-dns-name url

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#3375]
% juju bootstrap google jujushow-dns --config autocert-dns-name=show.jujugui.org
    % juju gui
    GUI 2.10.2 for model "admin/default" is enabled at:
     https://35.185.31.72:443/gui/u/admin/default

The url should be available to the user with the ssl cert in place.

**Comment by frankban** [comment]
This fix must be done in Juju itself, so closing the bug here.
The patch is at https://github.com/juju/juju/pull/8427
