### ISSUE TITLE
Log in message is not aligned correctly

### ISSUE THREAD

**Issue by barrymcgee** [juju/juju-gui#3378]
## Actual

<img width="824" alt="screen shot 2017-11-08 at 16 40 22" src="https://user-images.githubusercontent.com/505570/33717251-23519cce-db51-11e7-814f-ae75e5ca5a66.png">

## Expected

These messages should align.

**Comment by frankban** [comment]
Is this fixed @barrymcgee ?

**Comment by barrymcgee** [comment]
@frankban No, AFAIK this page is not hosted in either blues or GUI codebase but returned from the identity service?

**Comment by frankban** [comment]
Indeed, ok will close the bug here then. Thanks!

**Comment by barrymcgee** [comment]
@frankban Where should it be tracked though?

**Comment by frankban** [comment]
Moved to https://github.com/CanonicalLtd/candid/issues/39
