### ISSUE TITLE
Models' last accessed times are not available

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#3381]
If you load the gui and open the model switcher dropdown the last accessed times all say "Never accessed".

**Comment by huwshimi** [comment]
For some reason thee last accessed times are returned by the RPC call on prod, but not staging. Could this be a JEM issue?

**Comment by hatched** [comment]
The last-accessed times returned by JAAS for the users list of `ModelInfo` are `null` so we're not able to display them.

**Comment by cassiocassio** [comment]
We had this in the previous profile design, no? Are we using a new method to get the data? Should we remove the last accessed column from the design until we can show the data?

**Comment by hatched** [comment]
@cassiocassio we have this information available when using your own bootstrapped controller so we'll hide the column in the profile and hide the element in the model switcher if we do not have the data for all models.

**Comment by frankban** [comment]
Closing this as this is not a GUI bug.
