### ISSUE TITLE
Can't get back to models from new profile

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#3387]
Now that the profile doesn't disconnect when going to the profile we need a way to get back to the current model (needs to allow getting back to an uncommitted/new model too).

**Comment by cassiocassio** [comment]
hmm

1. The current or uncommitted model should be **listed at the top of all your models** (the default sort order by most recently accessed woudl put it there), and the value would be "now" or "uncommitted"

2. We might want **either** (a) a **back button** in the way that the inspector has the concept of back, or (b) a **close X**, which has the concept of dismiss this profile. 

Now the model remains connected it's possible to imagine profile as a floating modal, with the model continuing to do whatever it does in the background, but I honestly think that's not as useful having max area for data and the ability to return to that model quickly... 

I wonder if there's **value in** putting the **number of uncommitted changes** and some visual indication of that "**blue" state** in the model list...?
