### ISSUE TITLE
Editing then removing charm changes doesn't remove the 'changed' indicator in Firefox

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#3402]
To reproduce:

Add Nagios to the canvas, scroll down to an input that is empty. Add a character and delete it. The blue indicator should disappear (as it does in Chrome).

**Comment by makyo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Editing and changed indicator in FF](https://trello.com/c/hLwdO38X/169-editing-and-changed-indicator-in-ff)
