### ISSUE TITLE
new profile - title text link colour - models, charms and bundles

### ISSUE THREAD

**Issue by cassiocassio** [juju/juju-gui#3438]
(_despite_ what the designs _may_ have shown, _now_ we get to play with the elements interactively - @spencerbygraves and I propose...)

for consistency across models, bundles, charms, and any other open-close cards in profile:

for the **title** e.g modelname, bundlename, charmname, keyname, credentialname....

**closed state**
_"link"_, (in vanilla) blue, light font weight, underline on mouseover. (so users know they can go straight to the model canvas, or entity page, bypassing the open card)

**open state**
_"strong link"_  (in vanilla) , font weight regular, colour #111111, underline on mouseover, (because it's got to serve as a **title** to the whole open card..., which can have other blue links and other subtitles...)

https://docs.vanillaframework.io/en/patterns/links

**Comment by barrymcgee** [comment]
Strong links in expanded card - https://cl.ly/2S0d3o0I0a0f

Blue links in expanded cards - https://cl.ly/1d1I1Q1Y1D2O

**Comment by barrymcgee** [comment]
Strong links - https://github.com/juju/juju-gui/tree/3438-title-colors

Blue links - https://github.com/juju/juju-gui/tree/3438-title-colors-blue

**Comment by spencerbygraves** [comment]
@barrymcgee In your video, the expanded title looks like a soft link rather than strong. Also, Bugs and Homepage would remain blue. We thought the strong style would make sense to keep the title at the same prominence as the other titles on the card.

![image](https://user-images.githubusercontent.com/9105999/35524644-12090c5c-051a-11e8-95c0-ec1f79397a0c.png)

**Comment by barrymcgee** [comment]
@spencerbygraves I've made those changes: https://cl.ly/3o1v3M3H2Q2A

My only issue is that now in the 'Charms' tab, the title of the charm and the values under the 'Series' heading are the same unless you roll over the title when you then see the underline. In my opinion, links should be immediately distinguishable from the text that surrounds them.

**Comment by cassiocassio** [comment]
quick experiment:
- Readable: and Writeable: work as headings without the font-weight because of their Capitalisation and ":"
- nothing says blue link like a blue link, but upping the font weight there is a bit ugly, was worth a try..
 
<img width="1119" alt="screen shot 2018-01-30 at 10 30 21" src="https://user-images.githubusercontent.com/4593556/35564161-29022618-05b1-11e8-96b5-a1928041b5be.png">
