### ISSUE TITLE
charms and bundles look very prominent in the profile but empty and of no use to me

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#3496]
If I'm not logged into the charmstore than the charms/bundles links in GIJOE are of no use to me. We should either remove them, bury them at the bottom, or grey them out in some way to deprioritize behind models and credentials which everyone will always have. 

![distance-models-charms](https://user-images.githubusercontent.com/75915/36047840-429a1d40-0dab-11e8-8312-90237e78425c.jpg)

**Comment by hatched** [comment]
Yes this was an oversight in the initial implementation, but we'll be adding a button to log into the charmstore https://github.com/juju/juju-gui/issues/3485

**Comment by mitechie** [comment]
I still think though that if I've not yet logged into the charmstore why push them up so? I think this is apart from the button to login existing.

**Comment by hatched** [comment]
Alright, I'm going to move this into the design discussion as there isn't really anything actionable here atm.
