### ISSUE TITLE
head icon is confusing and unclear

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#3497]
I was hovering over the heads on each model row and it says "admin" and it wasn't clear what this was. At first I thought this was telling me it was my model, but there's an Owner column. Then I thought maybe this is part of the last-accessed but it's equal spaced from the time as the trash icon and so seems like it's own thing. in a GIJOE case there's nothing but the same head icon that will show here which makes it impossible to search/make use of that name there. I think we should rethink this part of the table data. 

![owner-heads-confusing](https://user-images.githubusercontent.com/75915/36048000-ca9823b8-0dab-11e8-9798-fe46fda1ce54.jpg)

**Comment by hatched** [comment]
In this implementation of the table, it's in a "collapsed" form, which hides some larger titles like "permissions". This will be remedied in a following release.

**Comment by cassiocassio** [comment]
We wanted to make the table responsive, and show the full details of
"permissions" with text as well as the icon.

That wasn't possible in the fixed width table we used in the first
iteration.

Other solutions - such as the double=decker designs were discussed.

The fixed width required the icons-with-tooltips solutions in this
implementation.
