### ISSUE TITLE
is "juju home" the right profile link in GIJOE?

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#3499]
It seems odd to me to have the juju home link in the upper right of a GIJOE profile. There's the help link and docs and charms/etc. Should this be something else? I guess i'm not sure what else it would go to but this is definitely not where I'd expect a link for a public/marketing juju url. 

![juju-home](https://user-images.githubusercontent.com/75915/36048304-c78e3c7e-0dac-11e8-9548-dc6883292b6a.jpg)

**Comment by hatched** [comment]
Yeah having links to help would be a good addition here.
