### ISSUE TITLE
updating GCE credentials does not work

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#3501]
I can click the input, pick my json file, but then when I hit open the field still appears blank.

![2018-02-09_15-40-05](https://user-images.githubusercontent.com/75915/36049146-c22da474-0daf-11e8-9352-0c9ea01d5e51.gif)

**Comment by mitechie** [comment]
When I add a credential is says it worked but I can't tell for sure.

**Comment by cassiocassio** [comment]
the add-and-then upload "has it done it yet" pattern is an inherent problem
with all of the browser upload functionalityt,

how about

- do more to set expectations that it's a 2-step process
- change the cues from "upload" to "select..." or "pick.."
- not lighting up the update button until some creds file is selected
- your selection was valid
- you *still* need to click the "update" button
- provide some kind of "done" feedback.
