### ISSUE TITLE
sort order on the charm listing in new profile isn't clear

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#3507]
I'm not sure what the sort order for the charms/bundles are at the moment. Should it default to alphabetical? 

![charm-sort-order](https://user-images.githubusercontent.com/75915/36208310-aac32b46-1166-11e8-93a6-f27e6ad7a02f.jpg)

**Comment by hatched** [comment]
It is displayed in the order that the charmstore returns the query, we'll be adding the ability to sort the columns by the headers eventually.

**Comment by mitechie** [comment]
Right, but even if you have the ability to sort manually I feel like this
is a bug worth keeping we can close when we have sorting fixed up. I don't
get why it's closed? There's no sorting and the current order makes no user
sense. That's the bug.

**Comment by cassiocassio** [comment]
User-sortable tables throughout the profile was always the plan ; I would choose alpha sorting on charm name if I had to choose.

what's the logic of the CLI output?

cassio@benbecula-2:~/Code/ubuntu/charms_and_bundles/ceph $ charm list -u rharding
cs:~rharding/grafana-4
cs:~rharding/gypsy-danger-6
cs:~rharding/bundle/gypsy-danger-testing-2
cs:~rharding/jujushell-8
cs:~rharding/prometheus-2
cs:~rharding/telegraf-0
cs:~rharding/precise/vsm-0

**Comment by mitechie** [comment]
I definitely agree that the cli output doesn't meet any desired form
either. It's using the same "what the server tells me I just use" method. I
was hoping to get a simple name sort in to start with as that's a couple of
lines through a sort function call until we have the sorting table tooling
in place.
