### ISSUE TITLE
The profile does not always register that you're logged in

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#3514]
If you visit the gui and click the logout link in the header the gui will reload and log you in again. It'll load your profile and if you click on charms it'll have the message about needing to log into the charmstore, but if you click on bundles and then back on charms they'll load.

**Comment by hatched** [comment]
Was this on JAAS or a self-bootstrapped controller?  

If this is in JAAS you're seeing this issue because you're using guiproxy and not embedded in the website. Feel free to close if that's the case.

**Comment by huwshimi** [comment]
Thanks @hatched, it was JAAS so this ain't no problem.
