### ISSUE TITLE
Controller info unnecessary on other user's profile

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#3516]
The details about which controller you're connected to doesn't seem to be relevant to viewing another user's profile.
![which_jaas](https://user-images.githubusercontent.com/361637/36235373-4511100e-1244-11e8-800c-45cc275195e7.png)

**Comment by hatched** [comment]
@cassiocassio something for you to consider.

**Comment by cassiocassio** [comment]
@huwshimi @hatched I'm working on some sketches to address this - and broader issues -  about jass/not-jass your model/mymodel, your profile, another profile, which i'll share soon.
