### ISSUE TITLE
tooltip doesn't cover icon above it

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#3527]
In the model profile hovering over the eyeball for "read" is then hidden by the icon above it. 

![icon-overlay](https://user-images.githubusercontent.com/75915/36279649-b8900fb4-1265-11e8-9023-130ac2942446.jpg)

**Comment by mitechie** [comment]
Assigning to @barrymcgee because I wonder if this is something vanilla-y

**Comment by hatched** [comment]
I think it's more something z-indexy but we'll see ;)

**Comment by huwshimi** [comment]
This is something I broke so I'll fix it.
