### ISSUE TITLE
cannot delete models from the GUI UI in trunk

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#3541]
I cannot delete a model from the GUI profile page. I have added new models and I get the popup, hit destroy, and the list refreshes. In looking at the wss traffic to the controller this looks legit but it's not working. 

I did a destroy-model from the cli and that does indeed work. 

Controller is on GCE with juju 2.3.3.

    {"type":"ModelManager","request":"DestroyModels","params":{"entities":[{"tag":"model-a9efed53-d224-49a7-8335-4defc9359346"}]},"version":4,"request-id":14}
    {"request-id":14,"response":{"results":[]}}
    {"type":"ModelManager","request":"ListModels","params":{"tag":"user-admin@local"},"version":4,"request-id":15}
    {"request-id":15,"response":{"user-models":[{"model":{"name":"controller","uuid":"3307f912-d60d-4332-80f1-21b1b5054fcc","owner-tag":"user-admin"},"last-connection":"2018-02-19T13:23:12Z"},{"model":{"name":"default","uuid":"5d862ab8-6c0a-468a-8edc-f95498bc8add","owner-tag":"user-admin"},"last-connection":"2018-02-19T13:23:12Z"},{"model":{"name":"deleteme","uuid":"a9efed53-d224-49a7-8335-4defc9359346","owner-tag":"user-admin"},"last-connection":"2018-02-19T13:23:12Z"}]}}

**Comment by frankban** [comment]
This is due to the API change at https://github.com/juju/juju/commit/5bbe0ea15b77effb2b991fd016a8d537fcd42e2e

The facade version has been bumped, so the GUI must support that logic.
