### ISSUE TITLE
Store the facade versions and issue warnings if they aren't supported

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#3544]
re #3541 

Hard code the supported facade versions for each API and then issue a warning to the user if the version of Juju they are using is not supported by the version of the GUI.

**Comment by rogpeppe** [comment]
I'm not sure this is worth a warning. Are there any bad consequences for the user when this warning is issued? It seems more like this could be a developer option so GUI developers can see when this is happening.

**Comment by hatched** [comment]
The idea behind the warning would be because it is very likely going to fail if Juju doesn't support the versions of the facade the GUI is trying to use.

**Comment by hatched** [comment]
Once we switch to the generated version of the Juju JS API this will no longer be an issue.
