### ISSUE TITLE
exporting a modified bundle breaks relation data

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#3548]
I have my bundle cs:~rharding/bundle/gypsy-danger-testing-2

I add that to my model and it loads up in uncomitted state. 

I then click on mysql and click destroy so that I do not have mysql as part of it any more. When I export it I properly have the lack of mysql in my applications but the relation is still there but replaced with a strange variable

      - - '90041383$:db'
        - 'gypsy-danger:db'

**Comment by hatched** [comment]
Thanks for the bug report @mitechie.

That strange variable, for who may be investigating, if it's not me, is the temporary id that is assigned to applications before they are deployed and we have a definite application id.

@mitechie could you please add the bundle yaml to this bug.

**Comment by mitechie** [comment]
series: xenial
    applications: 
      mysql: 
        charm: "cs:mysql-57"
        num_units: 1
        annotations: 
          "gui-x": "700"
          "gui-y": "658.2050807568877"
      "gypsy-danger": 
        charm: "cs:~rharding/gypsy-danger-5"
        num_units: 1
        annotations: 
          "gui-x": "1100"
          "gui-y": "658.2050807568877"
      grafana: 
        charm: "cs:~rharding/grafana-3"
        num_units: 1
        options: 
          admin_password: testing
        expose: true
        annotations: 
          "gui-x": "900"
          "gui-y": "311.79491924311225"
    relations: 
      - - "gypsy-danger:grafana-source"
        - "grafana:grafana-source"
      - - "mysql:db"
        - "gypsy-danger:db"

**Comment by huwshimi** [comment]
From what I can track down, when it deletes the uncomitted model, the [app's relations property is empty](https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/utils/environment-change-set.js#L806).

It looks to me that these [relation changes events](https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/models/models.js#L208) aren't firing.
