### ISSUE TITLE
Weird placement issues in JAAS

### ISSUE THREAD

**Issue by buggtb** [juju/juju-gui#3556]
So I launch 3 ZK nodes and 1 apache-drill charm and relate them. In the gui I leave manual placement selected but then select the auto placement button from the machines swim lanes.

When I hit deploy it spins up 4 nodes with nothing deployed on them, 2 zk nodes on machines that haven't been deployed and no sign of the other ZK node or Apache Drill.....

![untitled](https://user-images.githubusercontent.com/103544/36568808-46ab323e-1823-11e8-88f1-b033509cc7bb.png)

the finished output from juju status looks like:

https://gist.github.com/buggtb/5d291982ea66dd0a700bb0a97b22e589

**Comment by hatched** [comment]
Thanks for the bug report.

In trying to reproduce this I cannot find the `apache-drill` charm in the charmstore, is this a local charm?

**Comment by buggtb** [comment]
Try again, i hadn't bothered to grant access.

**Comment by hatched** [comment]
Got it thanks, and I have confirmed the issue. I'll get on fixing it.

**Comment by hatched** [comment]
I have found a resolution to the issue and was able to successfully deploy the model so a fix will be coming in the next release (2.12.2)

**Comment by hatched** [comment]
@buggtb Sorry, no it hasn't yet been released, we've been tightening up a few things around but plan to get it cut this week and out early next.

**Comment by buggtb** [comment]
No worries, wasn't grumbling, just ensuring it wasn't a reoccurrance!

**Comment by buggtb** [comment]
This is still open I assume? because I see it daily.

**Comment by hatched** [comment]
I'm not able to reproduce it any longer but I'll keep going. I am assuming that this is a race condition of sorts and that it will hopefully be resolved with the jujulib update.
