### ISSUE TITLE
Input carrot out of place in FireFox in Inspector scale-up UI

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#3557]
<img width="308" alt="screen shot 2018-02-22 at 5 00 28 pm" src="https://user-images.githubusercontent.com/532033/36569091-f7cb2434-17f1-11e8-93fb-613b757fcff2.png">

**Comment by hatched** [comment]
If you leave the tab then go back, it's in the correct spot

**Comment by cassiocassio** [comment]
# 🥕?

**Comment by huwshimi** [comment]
@hatched are you still seeing this?

**Comment by hatched** [comment]
I'm no longer able to reproduce this, maybe it was a bug in that specific version? 🤷‍♂️
