### ISSUE TITLE
"cores" constraint not working

### ISSUE THREAD

**Issue by galgalesh** [juju/juju-gui#3560]
On VMWare vsphere 6.5.0.13000, Juju 2.3.3, Juju GUI 2.12.1

Steps to reproduce:

1. Create controller on VMWare vsphere
2. Go to "machines" tab, click on the middle hamburger menu and choose "add machine"
3. Type in "4" in the "Cores" field and click "create"

What should happen: a machine with 4 cores is made
What happens: the default machine is created (2 cores)

**Comment by hatched** [comment]
Thanks for the report.

Are you able to confirm that this works as expected in the CLI?

**Comment by galgalesh** [comment]
Yes, this works in the CLI.

**Comment by hatched** [comment]
This is not just an issue on VMWare, it also happens on other cloud providers.

**Comment by hatched** [comment]
This is an issue with how Juju is handling the cpu-cores constraint https://bugs.launchpad.net/juju/+bug/1755580 .

We can probably update the GUI to use the not-so-new 'cores' constraint keyword as it's been there for over 2 years now. I'll investigate further before making the change.

https://github.com/juju/juju/blob/65bc411fb786ac7a621d4290a762d896c3317ce4/constraints/constraints.go#L27
