### ISSUE TITLE
Deleting apps sometimes removes the wrong one

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#3565]
To reproduce:
- add two apps
- click on one, then click on the other
- click Destroy in the inspector
- the first app you clicked on will get removed

**Comment by cassiocassio** [comment]
good find.

• It only seems to be an issue with un-deployed, uncommitted canvas items. Once you create the model deleting apps seems better behaved.

• Perhaps **it's the last-but one app that you click on that gets deleted?**: I tried with four charms:

https://cl.ly/2h3E3E3K003y
