### ISSUE TITLE
Store home layout problem

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#3584]
On gijoe (at least) and firefox (at least) the home of the store is not visualized correctly:
<img width="1416" alt="screen shot 2018-03-14 at 09 39 28" src="https://user-images.githubusercontent.com/1408172/37391571-da2ba94c-276b-11e8-8dcb-729c88c073d4.png">

**Comment by huwshimi** [comment]
Thanks @frankban, good find. Anyone have any thoughts on which block we should drop to make way for the experts or should we not show experts for gijoe?
