### ISSUE TITLE
Placement of icons when machine are provisioned gets broken

### ISSUE THREAD

**Issue by urosj** [juju/juju-gui#3632]
When deploying https://jujucharms.com/u/tengu-team/create-custom-data-flows/bundle/3 the layout gets broken after machines start to get provisioned like this:

![screenshot from 2018-04-26 09-29-25](https://user-images.githubusercontent.com/8036113/39291877-ab2f4014-4934-11e8-9ee7-881d0f3786b5.png)

**Comment by urosj** [comment]
You have to deploy it.

**Comment by frankban** [comment]
Ok, problem confirmed, thanks:
<img width="1573" alt="screen shot 2018-04-26 at 13 05 07" src="https://user-images.githubusercontent.com/1408172/39302308-7ea95340-4952-11e8-9274-e9d86ab1b617.png">

**Comment by makyo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Placement bug](https://trello.com/c/0Ke6hCZV/565-placement-bug)

**Comment by hatched** [comment]
Fixed by #3646
