### ISSUE TITLE
direct deploy has loading loop

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#3641]
If you visit the direct deploy e.g. /new/?dd=cs:bundle/canonical-kubernetes-76 then the direct deploy will load, then the normal deployment flow will appear and then it will loop.

This doesn't happen every time for me, but most times.

**Comment by hatched** [comment]
It loops a number of times but it will then eventually stop once the changeset import is complete.

**Comment by hatched** [comment]
It looks like this issue was introduced by https://github.com/juju/juju-gui/pull/3637 (guess it shouldn't have landed without a qa 😉 )
