### ISSUE TITLE
Unable to run development.ini from pycharm/unix command line

### ISSUE THREAD

**Issue by immu95** [juju/juju-gui#3652]
Have installed pycharm using which have cloned juju-gui in my IDE. After which I ran setup.py which was successful. Now when I try to run development.ini from the IDE am receving below error:

C:\Users\CG3\venv\juju-gui-2\Scripts\python.exe C:/Users/CG3/PycharmProjects/juju-gui/development.ini
  File "C:/Users/CG3/PycharmProjects/juju-gui/development.ini", line 6
    [app:main]
        ^
SyntaxError: invalid syntax
Process finished with exit code 1

**Comment by hatched** [comment]
Hello @immu95 the GUI isn't a typical python project, it really only uses the pyramid code as a webserver in certain environments. 

Is your goal to develop on the GUI or would you like to simply run it locally?

**Comment by hatched** [comment]
Ahh ok so I assume you want to get the GUI running to modify it then...
The hacking docs should provide you the information you need to get the GUI running on your machine. 

https://github.com/juju/juju-gui/blob/develop/docs/hacking.md

However I notice that you're using Windows, the GUI requires Make and a linux environment to be built at the moment.
