### ISSUE TITLE
Destroy model silently fails with external storage

### ISSUE THREAD

**Issue by cassiocassio** [juju/juju-gui#3659]
Destroying a model in the GUI silently fails

Clicking on the < trash> icon: 
<img width="848" alt="screen shot 2018-05-18 at 11 03 27" src="https://user-images.githubusercontent.com/4593556/40229237-8f787fd0-5a8b-11e8-90f1-0120f3f26522.png">

... leads to the confirm dialog:

<img width="430" alt="screen shot 2018-05-18 at 11 03 24" src="https://user-images.githubusercontent.com/4593556/40229259-a42dc5ca-5a8b-11e8-9236-f2980f3e9643.png">

Clicking <Destroy>

--

With @mhilton - Initially I thought this was when Juju controller requires destroyStorage to be true:

```
cassio@benbecula-2:~ $ juju destroy-model testk8s
WARNING! This command will destroy the "testk8s" model.
This includes all machines, applications, data and other resources.

Continue [y/N]? y
Destroying model
ERROR failed to destroy model "testk8s"
ERROR cannot destroy model: this Juju controller requires destroyStorage to be true
cassio@benbecula-2:~ $ juju destroy-model testk8s --destroy-storage
WARNING! This command will destroy the "testk8s" model.
This includes all machines, applications, data and other resources.

Continue [y/N]? y
Destroying model
```

but I fear also seems to be a problem in the general case. This needs further investigation.

**Proposals: (in the case of the storage failure)**

1.  Improve the error language for the juju CLI

'ERROR cannot destroy model: use --destroy-storage option to force.

2. If attached storage is also destroyed, make it clear in the dialog.

![destroy all](https://user-images.githubusercontent.com/4593556/40230615-0ab8356a-5a90-11e8-8f22-f7bdc5a83c76.png)

**Comment by frankban** [comment]
Isn't this also a problem in current API client system always selecting most recent facade version?

**Comment by hatched** [comment]
I think it's a combination of two things. We always select the latest facade version, and that we aren't sending that configuration option when destroying. We'll need to revisit this once the new jujulib stuff has been implemented.
