### ISSUE TITLE
deploy button is disabled when deploying charms with plans

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#3755]
In the deployment flow, with pay and expert flags active, and after providing a stripe key, after adding mattermost to the canvas, the deployment flow does not allow for committing the changes.

**Comment by huwshimi** [comment]
Thanks @frankban. I'm having a little trouble reproducing.

Using my local GUI and `guiproxy -env prod -flags pay,experts -config '"paymentURL": ..., "stripeKey": ...'` (I also tried on staging) I added `cs:~cmarstech/mattermost` and open the deployment flow, once I selected creds the big green deploy button at the bottom became enabled.

Is there step I'm missing or is my setup different to yours in some way?

**Comment by frankban** [comment]
In staging, having payment already setup, deploy mattermost, then click to open the deployment flow, and there is no way to enable the deploy button. Maybe that's because there is no way to accept terms? I don't know, somethign to be investigated.

**Comment by frankban** [comment]
If you want we can have a chat about this

**Comment by huwshimi** [comment]
Ah, maybe I've already accepted the terms at some stage...

**Comment by huwshimi** [comment]
@frankban did you have any luck reproducing this on staging now that it is fixed? With the `cs:~yellow/docker-registry` charm I do see the terms checkbox.
