### ISSUE TITLE
Inspector tries to fetch plans for service fail

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#3773]
To reproduce, deploy CDK and while it is deploying open the inspector for `kubernetes-master` and you'll get a 404.

`https://api.jujucharms.com/omnibus/v3/plan/model/aa6684e6-541a-463b-86b5-6ad823040c93/service/kubernetes-worker`

`{"code":"not found","error":"service not found","message":"service not found"}`

**Comment by cmars** [comment]
This API request provides the current and available plans for the given deployed application. There is no pricing plan released for kubernetes-master, so a 404 response from Omnibus is appropriate.

In general I'd possibly report failures like this back silently as telemetry but would not surface them to the user as there's nothing the user can do about them.

**Comment by frankban** [comment]
Yes I agree, this does not seem to be an error, assuming the GUI handles gracefully the 404 response.

**Comment by clagom** [comment]
@hatched @huwshimi Is this still relevant?
