### ISSUE TITLE
GISF property not set in GIJ

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#3825]
A bunch of components expect the gisf prop to be set, but it's not in gij.

I suspect this is due to the props passed to app.js rather than a problem with the individual components. Either way the errors were discovered in the following locations:

Login screen:
- Warning: Failed prop type: The prop `gisf` is marked as required in `HeaderLogo`, but its value is `undefined`.
- Warning: Failed prop type: The prop `gisf` is marked as required in `Login`, but its value is `undefined`.

Store home:
- Warning: Failed prop type: The prop `gisf` is marked as required in `Charmbrowser`, but its value is `undefined`.
- Warning: Failed prop type: The prop `gisf` is marked as required in `Store`, but its value is `undefined`.

Profile:
- Warning: Failed prop type: The prop `gisf` is marked as required in `Store`, but its value is `undefined`.

Help:
- Warning: Failed prop type: The prop `gisf` is marked as required in `Help`, but its value is `undefined`.

**Comment by clagom** [comment]
@huwshimi Is this still relevant?

**Comment by huwshimi** [comment]
I believe so, but won't be an issue with the new gui.
