### ISSUE TITLE
State update issue in the deployment flow

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#3826]
Opening the deployment flow (in my case it was in commit mode, but might be in both) I got the following warning:
```
Warning: Render methods should be a pure function of props and state; triggering nested component updates from render is not allowed. If necessary, trigger nested updates in componentDidUpdate.

Check the render method of App.
```

**Comment by frankban** [comment]
Related to https://github.com/juju/juju-gui/issues/3794 ?

**Comment by clagom** [comment]
@huwshimi Is this still relevant?

**Comment by hatched** [comment]
I'm no longer able to reproduce this. Closing.
