### ISSUE TITLE
Profile close button out of place

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#3827]
Opening my profile on gij showed the close button and address as broken as show below:

<img width="297" alt="screen shot 2018-10-02 at 10 45 23 am" src="https://user-images.githubusercontent.com/361637/46326438-10641080-c640-11e8-8fe1-e9753ebed949.png">

**Comment by hatched** [comment]
Are you sure you're using the latest develop? This was fixed in #3821 .

**Comment by huwshimi** [comment]
Oh, maybe not, looks like my fetch didn't get the latest somehow.
