### ISSUE TITLE
Redirected to blank page when loading https://jujucharms.com while logged in

### ISSUE THREAD

**Issue by cmars** [juju/juju-gui#3834]
If I'm logged in to jujucharms.com and I try to open https://jujucharms.com in a new tab, I get redirected to https://jujucharms.com/u/cmars and then redirected to https://jujucharms.com/login/u/cmars, which is a blank page.

I'm able to work around this by either:
- Opening https://jujucharms.com in a private browsing window and logging in
- Loading https://jujucharms.com/logout in a new tab and logging back in

However, a short time after being logged in (10-15 minutes?) I get redirected to the same blank page.
 
I am using Firefox 62.0.3 with uBlock disabled on jujucharms.com, so I don't think the issue is being caused by content blockers.

**Comment by cmars** [comment]
@dhenrich We're looking into it!

**Comment by cmars** [comment]
Ok, I've learned a bit more about the nature of, and scope of this issue.

It still manifests in Firefox if I restart the browser in safe-mode, with extensions disabled. That rules out my extensions (Multi-Account Containers and uBlock Origin).

If I start Firefox as if I were a new user, however, I _cannot_ reproduce the issue. I simulate this with `HOME=$(mktemp -d) firefox &`.

In my normal browsing, I have the privacy setting "Accept third-party cookies and site data" set to "Never". If I then set this same setting in my "pristine" Firefox session, after a few minutes I am able to reproduce the same "blank screen" issue described above.

So, I think this issue may be limited to users with similar content settings, possibly only Firefox users?

**Comment by hatched** [comment]
Thanks for continuing to investigate this @cmars .

The good news is that this issue is probably less widespread than we originally thought. We should however be much more resilient to browsers refusing cookies and fail gracefully by making them log in again or refreshing the token if we can.

**Comment by frankban** [comment]
We need to investigate this more, and handle invalid cookies more gracefully, as I remember seeing blank /login pages even with other browsers sometimes.

**Comment by hatched** [comment]
As the whole login flow (from the code side) will be changing with the jujulib change I'll revisit this once that change has been completed to see if it's not remedied as a side effect of those changes.
