### ISSUE TITLE
Follow-up issues from #3831

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#3841]
There were a few small QA issues in #3831 this is to track those.

---

~~Visited models are a slightly different colour than the others:~~
<img width="130" alt="screen shot 2018-10-19 at 2 02 50 pm" src="https://user-images.githubusercontent.com/532033/47390037-9a4d4980-d6d3-11e8-9161-1028547dbf66.png">

---

- [x] Username section is too narrow and wraps instead of re-flowing table:
<img width="749" alt="screen shot 2018-10-19 at 12 08 54 pm" src="https://user-images.githubusercontent.com/532033/47390065-ae914680-d6d3-11e8-9d33-12b667d4be52.png">

---

- [x] Dropdown menu in credentials section is way larger than the text within it:
<img width="321" alt="screen shot 2018-10-19 at 12 10 28 pm" src="https://user-images.githubusercontent.com/532033/47390099-c49f0700-d6d3-11e8-8e21-29ef789c00a5.png">

---

- [x] Profile header links link within active GUI but instead should open new windows:
<img width="216" alt="screen shot 2018-10-19 at 12 11 09 pm" src="https://user-images.githubusercontent.com/532033/47390113-d2ed2300-d6d3-11e8-9700-cc21eedb0853.png">

---

- [x] Destroy confirmation dialogue UI layout is broken:
<img width="398" alt="screen shot 2018-10-23 at 3 25 41 pm" src="https://user-images.githubusercontent.com/532033/47391784-fc0fb280-d6d7-11e8-8ca0-49d86b002ad7.png">

**Comment by barrymcgee** [comment]
Visited links being darker shade is an accessibility feature of Vanilla.

**Comment by barrymcgee** [comment]
Username col breaks onto two lines: PR: https://github.com/juju/juju-gui/pull/3843

**Comment by barrymcgee** [comment]
Destory model pop-up layout: PR: https://github.com/juju/juju-gui/pull/3844

**Comment by barrymcgee** [comment]
Dropdown menu for credentials actions: PR https://github.com/juju/juju-gui/pull/3845
