### ISSUE TITLE
all the elements except the charms go missing

### ISSUE THREAD

**Issue by buggtb** [juju/juju-gui#3851]
No idea of the cause, refresh doesn't fix it either:

<img width="1739" alt="screenshot 2018-10-26 at 16 40 28" src="https://user-images.githubusercontent.com/103544/47577126-09c67180-d93e-11e8-850e-fdcc3350a701.png">

**Comment by hatched** [comment]
From our discussion this was caused by the `s.addresses is undefined` error which has been resolved in the upcoming release.
