### ISSUE TITLE
ports list is duplicated... sometimes

### ISSUE THREAD

**Issue by buggtb** [juju/juju-gui#3852]
Ports list in the juju status page is a bit dodgy

<img width="1623" alt="screenshot 2018-10-26 at 13 29 19" src="https://user-images.githubusercontent.com/103544/47577159-24004f80-d93e-11e8-9263-d5bc9f96350a.png">

**Comment by hatched** [comment]
While I can't reproduce exactly what is there I was able to reproduce the duplication easily by just deploying and exposing `apache-drill`.

![screen shot 2018-10-26 at 10 16 54 am](https://user-images.githubusercontent.com/532033/47579105-568f5580-d908-11e8-8e5f-ff173d305afd.png)

**Comment by hatched** [comment]
The data from the parseUnit in maraca is returning the proper value but the data in the valueStore is incorrect. It appears to be caused by the deepmerge in maraca's _updateStore duplicating entries in the port range array.
