### ISSUE TITLE
relations go missing....

### ISSUE THREAD

**Issue by buggtb** [juju/juju-gui#3857]
<img width="2992" alt="screenshot 2018-10-29 at 16 18 44" src="https://user-images.githubusercontent.com/103544/47664145-5c9a6600-db96-11e8-9c56-b273d8e20de2.png">

Trying to relate drill to plugin and this happens...

**Comment by hatched** [comment]
Neither I nor @buggtb have been able to reproduce this, I'm going to leave this open in case someone else has an idea what might have caused it and can reproduce it.

If it doesn't come up again we can close this.
