### ISSUE TITLE
juju shell wraps onto the same line

### ISSUE THREAD

**Issue by buggtb** [juju/juju-gui#3859]
If your shell text wraps to the next line it will wrap to the same line and overwrite whatever you'd just typed.
<img width="1167" alt="screenshot 2018-10-29 at 22 07 13" src="https://user-images.githubusercontent.com/103544/47683270-02fe5f80-dbc7-11e8-873d-f855e7a7a67e.png">

**Comment by hatched** [comment]
There have been some updates to xterm, we should apply those then see if we can reproduce.
