### ISSUE TITLE
charmstoreURL juju provides is not honored by config template

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#3885]
Juju has the ability to specify a customized charm store when bootstrapping. But currently, the GUI as served by the controller does not honor that value, and instead always points to prod cs (see [1]).
I expect the change to be something similar to [2], but of course we need to be backward compatible and handle the case charmestoreURL is not in the template context.

[1] https://github.com/juju/juju-gui/blob/develop/jujugui/templates/config.js.go#L12
[2] https://github.com/juju/juju-gui/compare/develop...frankban:honor-charmstore-url

**Comment by hatched** [comment]
This no longer applies to the new architecture
