### ISSUE TITLE
Juju Controller/GUI SSL certificate

### ISSUE THREAD

**Issue by michaeleino** [juju/juju-gui#3887]
related #2553 #1599 
How we can set a ready SSL certs, so the juju controller and juju gui make use of them..
There is no clear documentation illustrate that. Please don't tell me this is not possible.. 
also the `autocert-dns-name` is not clear! ... how letsencrypt will validate the ownershop of the dns ? which method? and what if the juju is only accessible from private network?

I know the option to set `ca-cert` on the juju controller config, but this will require to install the CA on each client browser.

Simply, can't we generate the cert, sign it, and just install it to the juju controller?
[juju gui charm](https://jujucharms.com/juju-gui/) have the option to set  `ssl-cert-contents` and `ssl-key-contents` can we pass those to bootstrap configs? how?

**Comment by jamesbeedy** [comment]
related: https://discourse.jujucharms.com/t/options-for-production-controllers/187/4

**Comment by jamesbeedy** [comment]
I agree with you (as you can see from the top of the discourse issue there). This stuff needs to get into the juju docs legit somehow.
