### ISSUE TITLE
Bundle rendering with empty readme.md broken

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#3892]
When viewing a bundle entity with a `README.md` but the file is empty then the UI and layout breaks.

**Comment by huwshimi** [comment]
@hatched can you reproduce this in the GUI? I can see the breakage in jujucharms.com, but seems fine for the GUI (I tested with `/u/hatch/large-ghost/bundle/1`).

**Comment by hatched** [comment]
I'm not able to reproduce this in the GUI.
