### ISSUE TITLE
service unhighlight references svgs that don't exist

### ISSUE THREAD

**Issue by huwshimi** [juju/juju-gui#3896]
Not sure if this code is used, but it references svgs that don't exist. See https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/init/topology/service.js#L1780

**Comment by hatched** [comment]
New file location: https://github.com/juju/juju-gui/blob/develop/gui/src/app/init/topology/service.js#L1786

**Comment by clagom** [comment]
@hatched @huwshimi Is this still relevant?

**Comment by huwshimi** [comment]
This is just some unused code cleanup, won't be an issue for the new gui.
