### ISSUE TITLE
Broken layout in profile / cloud credentials

### ISSUE THREAD

**Issue by clagom** [juju/juju-gui#3897]
In Juju GUI, the profile page displays a broken layout in the cloud credentials section, edit cloud credentials, then:
<img width="1680" alt="screenshot 2019-01-24 at 14 53 37" src="https://user-images.githubusercontent.com/1953388/51686362-29764000-1fe8-11e9-823b-b288844ea723.png">
<img width="1680" alt="screenshot 2019-01-24 at 14 53 43" src="https://user-images.githubusercontent.com/1953388/51686372-2c713080-1fe8-11e9-8de8-208b69c91898.png">

**Comment by huwshimi** [comment]
This has been fixed by #3868 and will be available in the next release.
