### ISSUE TITLE
Charm detail page on mobile, page jumps up

### ISSUE THREAD

**Issue by clagom** [juju/juju-gui#3898]
Got this feedback from a user through Usabilla, on jujucharms.com:
"On mobile android chrome -Samsung s8+, when you open a charm or bundle from store to read more information. Example: https://jujucharms.com/canonical-kubernetes/ The page behaviour when I scroll down and the top ribbon expands to show the extra information makes the page suddenly jump up and down, making top paragraphs of information inaccessible."

I couldn't replicate on my smartphone (the top sticky element does not create jumpy page on iPhone), but we might want to investigate this issue.

@barrymcgee @hatched @anthonydillon

**Comment by hatched** [comment]
We discussed this offline and we'll remove the sticky headers from the GUI & jujucharms.com.
