### ISSUE TITLE
CORS error when searching for charms

### ISSUE THREAD

**Issue by mlda065** [juju/juju-gui#3910]
Whenever I try to search for a charm from the GUI it says:

> Something went wrong

> For some reason the search failed. You could try searching at http://jujucharms.com or go back

This happens every time I search for anything.

My Juju controller machine has internet access. I can `wget` http://jujucharms.com from the machine.

The issues are:

1. The search fails
2. The error message is not descriptive enough to be helpful

**Comment by mlda065** [comment]
I just openned the console. I can see a flood of error messages.

They are all about Cross-Origin warnings.

> Search request failed. no entity data returned, can you access the charmstore? combo:1:445025
>
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.jujucharms.com/charmstore/v5/search?text=haproxy&tags&limit=150&autocomplete=1&include=charm-metadata&include=supported-series&include=bundle-metadata&include=extra-info&include=owner. (Reason: CORS request did not succeed).

There are infinite retries with no wait in between, so while I am reading the error message, the page is maxing out a whole CPU trying the same thing again and again. There should be a delay between retries, ideally with exponential backoff.

But the core issue is CORS a error.

I am accessing the Juju GUI from another machine, so the URL in my browser is https://10.58.2.36:17070/gui/u/admin/contrail 
I am using Firefox 66.0.2.

**Comment by hatched** [comment]
I'm not able to reproduce this, are you still able to reproduce this issue?

**Comment by mlda065** [comment]
I found [the cause](https://github.com/juju/juju-gui/issues/3913#issuecomment-483520556).

It was a particular browser extension I use. (Privacy Badger)

The log messages in the console happen to look like CORS errors, so I thought it was a CORS issue.
