### ISSUE TITLE
GUI shows application as OK when it has an ERROR

### ISSUE THREAD

**Issue by mlda065** [juju/juju-gui#3922]
The circles in the graph sometimes appear red when there is an error for that unit.
However not always.

As you can see in this printscreen, there are two units which have a status "error", yet no circles are marked as red in the GUI, and only one application in the GUI list is marked as red.

![noerr-juju-graph](https://user-images.githubusercontent.com/7035647/56011864-0af12c80-5d2d-11e9-882b-bde45bd28a99.png)

**Comment by hatched** [comment]
Thanks for filing this issue, it appears that these are subordinates that are in error?
- Are you able to reproduce this?
- Are there any errors in the browser console?

#### Dev investigation needed 
Does a hook failure in a subordinate cause the icon to change state?

**Comment by mlda065** [comment]
This particular charm was a proprietary one I can't share.

I've played around and it's not in that state right now.

If I see this behavior again, I'll let you know.

It seems to be that when a hook fails on a dependent charm, it doesn't show. Maybe we could try deliberately writing a bad hook on a dependent charm and see what happens?

**Comment by hatched** [comment]
Thanks, I have a charm specifically for testing failure states https://jujucharms.com/u/hatch/failtester/ I'll have to update it and create  subordinate version :-)

**Comment by clagom** [comment]
@hatched any updates?

**Comment by hatched** [comment]
I'm going to close this issue as this will be rewritten as part of the new GUI.
