### ISSUE TITLE
Tell the users that the site is still loading if it takes too long

### ISSUE THREAD

**Issue by clagom** [juju/juju-gui#3923]
At the moment the UI doesn't tell anything to the users, and the website being too slow to load the page gives the idea that it's broken. When this is the case (e.g. taking more than 10secs to load) we should tell the users: hey, we're still here.
https://app.usabilla.com/member/#/websites/buttons/feedback/5caced80a6404f4a851011ab

**Comment by hatched** [comment]
We're going to prioritize fixing the performance issues over implementing something to track the resources loading.

**Comment by anthonydillon** [comment]
This is an issue for all applications and websites. Even optimised applications need to consider show connections. There is also a number of ways to improve this from further optimisations, user feedback, precieved performance, etc. 

This is a consideration for the squad and the wider team. Therefore, this issue should be moved to the squad repo to devise a performance budget and best practises for tackling loading in general.
