### ISSUE TITLE
UI issues on the GUI profile page, credential tab

### ISSUE THREAD

**Issue by clagom** [juju/juju-gui#3939]
Action menu buttons look strange, not sure we are using the right one. Anyway this would be a good chance to get rid of the menu, and surface directly the actions edit and delete. We could use labels, or bin/pen Vanilla icons.
![Screenshot 2019-04-24 at 14.15.10.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/2d27d501-0b44-4b5a-b7f6-bad699e053cd)

Spacing and layout need adjustments
![Screenshot 2019-04-24 at 14.15.03.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/bbd2c362-c983-4637-be67-3d9045671d75)

@spencerbygraves could you have a look please
CC @hatched

**Comment by spencerbygraves** [comment]
@clagom @hatched we can use the two icons as below:

![image](https://user-images.githubusercontent.com/9105999/56672047-a11e3e80-66ad-11e9-871b-39727b7f07ad.png)

**Comment by clagom** [comment]
The icons would be preferable instead of the contextual menu, we use them across products. Closing for now, as the new gui would consider this.
