### ISSUE TITLE
[GUI] The ordering of the labels in the drop-down doesn't reflect the order in the list

### ISSUE THREAD

**Issue by clagom** [juju/juju-gui#3947]
@hughesjordan noticed this during the QA on staging:
![unnamed.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/b169f5df-29da-43ad-b5a4-d92d8060cec3)
"the order in which the tags are displayed within the 'supports' column change, I would expect this to follow a rule so that tags always display in a set order."
Opened the same one for jaas.ai here https://app.zenhub.com/workspaces/juju-squad-593fe9c0b747921fa7ecd561/issues/canonical-web-and-design/jaas.ai/251

**Comment by anthonydillon** [comment]
I suspect we could map the names to version numbers and sort based on the version but display the name.

**Comment by hatched** [comment]
See https://github.com/canonical-web-and-design/jaas.ai/issues/251#issuecomment-492758249 for why this is not a technical issue.
