### ISSUE TITLE
Login leads to 404

### ISSUE THREAD

**Issue by nottrobin** [juju/juju-gui#3948]
See [this video](https://drive.google.com/file/d/1a1N4LysYW7oPM-8unwBcnllYp5MNOszS/view?usp=sharing)

After going to https://jujucharms.com/new (pointing my `/etc/hosts` file at the new flask application), and clicking "login" in the top right, end up at:

https://api.jujucharms.com/identity/v1/login?waitid=dfe9b302db6d7c525637857f2a7781e5

Which is a 404.

(This is either through clicking the "click here" on the modal, or through letting it open the popup automatically)

This doesn't seem to be happening on the old version of the site.

**Comment by hatched** [comment]
After discussion this is not able to be reproduced. Closing for now.
