### ISSUE TITLE
Multi-cloud controller shows units from several models in GUI

### ISSUE THREAD

**Issue by seffyroff** [juju/juju-gui#3980]
Juju version 2.6.2-bionic-amd64
Clouds/Controllers:
Controller deployed to Azure/westus2
LAN LXD cloud added to controller
Azure<>LXD Cloud connected via SDN
Models:
1 Model in Azure Cloud
1 Model in LXD Cloud

Browsing the GUI hosted at the Azure controller, looking at the model on the LXD Cloud, I see units from the Model in the Azure Cloud in the Status tab.

**Comment by hatched** [comment]
The GUI will only display the data that's being provided to it from the controller so this may be a bug in the controller. 

Does it always display these units even if it was the only model you've viewed in that session?

Steps:
 - load the GUI
 - view model
 - shows units from the wrong model?

**Comment by clagom** [comment]
@hatched Is this still relevant? Sounds like a bug that would affect also the new gui

**Comment by hatched** [comment]
Closing as we haven't received any feedback about this issue.
