### ISSUE TITLE
Add 'Kubernetes' in the drop-down filter

### ISSUE THREAD

**Issue by clagom** [juju/juju-gui#3996]
Ideally we would implement the same drop-down filter we have in jaas.ai, but at least we could include 'Kubernetes' in the list:
![Screenshot 2019-06-21 at 13.41.54.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/289fc21a-be14-41de-8c74-3ac008f36f5d)

I remember we discussed to align the two drop-down, content wise.

**Comment by anthonydillon** [comment]
This would be great for you to look at Caleb, I will try get you access.

**Comment by huwshimi** [comment]
It looks like maybe I did this already: https://github.com/juju/juju-gui/commit/5cf79af57f48f01cd596134cf3192b4884800d0b#diff-8b9ae5452604ae06b81d60d27e635dd2

Might just need to be released. @hatched anything stopping us from doing that?

**Comment by clagom** [comment]
Updates on this, too?

**Comment by huwshimi** [comment]
@clagom this is also now released to production.
