### ISSUE TITLE
Align 'k8s' tag in the GUI store with 'Kubernetes' tag in jaas.ai store

### ISSUE THREAD

**Issue by clagom** [juju/juju-gui#3997]
![Screenshot 2019-06-21 at 13.41.49.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/5eda581c-0ec1-409e-b22e-244af2b93ab2)
They should not be different

**Comment by anthonydillon** [comment]
This is just updating the tag from k8s to Kubernetes

**Comment by huwshimi** [comment]
This is already done, just needs to be release. I'll check with @hatched if we can do so.

**Comment by clagom** [comment]
Hi @huwshimi @hatched any updates on this?

**Comment by huwshimi** [comment]
@clagom this is now released to production.
