### ISSUE TITLE
Email popup module instead of 'join us' JAAS expert page 

### ISSUE THREAD

**Issue by clagom** [juju/juju-gui#3998]
We have the new module pop-up contact form in https://jaas.ai/experts/spicule
Would be useful to open the same form in https://jaas.ai/experts/ page instead of the 'join us' mailto link that seems to be less compatible with browsers and email clients.

![Screenshot 2019-07-01 at 11.51.34.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/932b3538-a04e-4002-8e80-5a8542afb4e5)

![Screenshot 2019-07-01 at 11.51.42.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/5f23cf66-7847-4a7a-ba47-6a8a206eb300)

Would be without the contact info on top, just the form:
![Screenshot 2019-07-01 at 11.54.20.png](https://images.zenhubusercontent.com/5b0d889d89d5dc41604fa14c/75a970b3-6c23-4311-8a12-b5984249b124)

**Comment by huwshimi** [comment]
Looks like this is about jaas.ai, I've moved it here: https://github.com/canonical-web-and-design/jaas.ai/issues/344
