### ISSUE TITLE
Broken logo

### ISSUE THREAD

**Issue by buggtb** [juju/juju-gui#4016]
There appears to be a broken logo in the embed card thing...

<img width="477" alt="Screenshot 2019-08-16 at 22 21 22" src="https://user-images.githubusercontent.com/103544/63198953-4782bb00-c074-11e9-9d93-775bc1dee94f.png">

**Comment by mitechie** [comment]
Tossing this over to @anthonydillon and @hatched to peek at.

**Comment by anthonydillon** [comment]
A logo now appears for all versions of the Juju-cards
