### ISSUE TITLE
The entity details are not loading

### ISSUE THREAD

**Issue by anthonydillon** [juju/juju-gui#4017]
Production works fine but getting an error loading an entity details on `develop`.

To reproduce:
- Run `./run`
- Visit http://0.0.0.0:8032/new
- Navigate the store to a charm details page (for example, http://0.0.0.0:8032/new/nagios)
- See that the entity details do not load

**Comment by anthonydillon** [comment]
Error I get is: `cannot fetch the entity no entity data returned, can you access the charmstore?`

**Comment by anthonydillon** [comment]
It was still loading `revision-info`. It's working now by pulling the latest. Doh...

**Comment by eperezf** [comment]
Hi! I am getting the same issue along with several 401 (Unauthorized) calls to the jujucharms API. 

Also I'm getting 

`cannot retrieve default cloud name: no such request - method Cloud(5).DefaultCloud is not implemented`

which is referenced in #4000 

I am running Juju 2.6.6 and GUI 2.14.0.

**Comment by eperezf** [comment]
Removing the `revision-info` from the request to the API seems to fix the problem. But the stable version 2.6.6 (GUI v2.14.0) is still including it. Is there any release soon?

**Comment by anthonydillon** [comment]
@eperezf We are working on allowing `revision-info` requests from the API. This should resolve older GUI versions.

**Comment by eperezf** [comment]
I saw the most recent version of juju GUI is 2.14.1 but when doing `juju upgrade-gui` it says the most recent stable version is 2.14.0. Is there any way of updating to 2.14.1? Or that version does not fix the issue?

**Comment by hatched** [comment]
Sorry you're running into this @eperezf, I'll be creating a new GUI release for non-JAAS controllers today which will contain this fix. I'll comment here when it's ready to go.

**Comment by hatched** [comment]
A new version of the GUI has been released. 2.15.0 will now be available when you run `juju upgrade-gui` or bootstrap a new controller.

**Comment by eperezf** [comment]
Upgraded to 2.15.0. Problem gone. Still getting some 401's from the API but I can see the bundles.
<img width="1680" alt="Screen Shot 2019-08-23 at 2 02 53 AM" src="https://user-images.githubusercontent.com/6854338/63570204-5c66bf00-c54a-11e9-9309-0371c782225b.png">

**Comment by hatched** [comment]
Glad to hear it's working for you. It looks like some of the icon paths need to be updated. Thanks
