### ISSUE TITLE
Juju shell unavailable

### ISSUE THREAD

**Issue by dbwest** [juju/juju-gui#4025]
GUI Version: 
JAAS: undefined
Location: https://192.168.0.124:17070/gui/u/admin/mymodel/i/inspector/jujushell
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

**Comment by hatched** [comment]
Sorry there isn't enough information here to determine what the issue is. Can you please elaborate?
