### ISSUE TITLE
Juju shell unavailable

### ISSUE THREAD

**Issue by dbwest** [juju/juju-gui#4026]
GUI Version: 
JAAS: undefined
Location: https://192.168.1.248:17070/gui/u/admin/mymodel
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

**Comment by hatched** [comment]
Closing as duplicate of: https://github.com/juju/juju-gui/issues/4022
